### ISSUE TITLE
Logging encoding error

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#1882]
I got the following when running update_store against Afrikaans

2011-03-07 08:27:42,452 WARNING Data integrity error while importing unit Last Update: %S:
(1062, "Duplicate entry '16389-0d70483aacbb3d4b79c59db5955d3c67' for key 'store_id'")
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/__init__.py", line 791, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 98: ordinal not in range(128)
2011-03-07 08:27:42,456 WARNING Data integrity error while importing unit Connected: %S:
(1062, "Duplicate entry '16389-8c2a3e55a6c611635fb7db482bd5ad81' for key 'store_id'")
2011-03-07 08:27:42,458 WARNING Data integrity error while importing unit Disconnected:
(1062, "Duplicate entry '16389-ef70e46fd3bbc21e3e1f0b6815e750c0' for key 'store_id'")
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/__init__.py", line 791, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 84: ordinal not in range(128)
2011-03-07 08:27:42,461 WARNING Data integrity error while importing unit Mobile Bookmarks:
(1062, "Duplicate entry '16389-02f7a9ebf6b7e8df6c130920d067c4af' for key 'store_id'")
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/__init__.py", line 791, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 102: ordinal not in range(128)
2011-03-07 08:27:42,465 WARNING Data integrity error while importing unit Sync your other computers again to access their tabs:
(1062, "Duplicate entry '16389-eea7484f421f2394ab03139390323dd1' for key 'store_id'")
2011-03-07 08:27:42,467 WARNING Data integrity error while importing unit All remote tabs are already open:

**Comment by julen** [comment]
`update_stores` went through lots of changes in years, this is not relevant anymore.
