### ISSUE TITLE
Pootle becomes broken on upgrade because of postgres error

### ISSUE THREAD

**Issue by booxter** [translate/pootle#1915]
*See also:*
 * http://bugs.locamotion.org/show_bug.cgi?id=2369

*Version: 2.1.x*

It seems that upgrade process for postgresql is broken. If I update my pootle installation from svn and it detects the need to upgrade database, I get the following python error in apache log and site broken:

```
2011-04-23 14:35:13,527 INFO Creating missing database tables
2011-04-23 14:35:13,670 WARNING something broke while creating new database tables:
current transaction is aborted, commands ignored until end of transaction block

[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] mod_python (pid=20682, interpreter='pootle', phase='PythonHandler', handler='django.core.handlers.modpython'): Applicat
ion error
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] ServerName: 'mounik.org'
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] DocumentRoot: '/home/ubuntu/public_html/mounik/'
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] URI: '/pootle/be/gnome3/glib.glib-2-28.po/translate/'
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] Location: '/pootle'
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] Directory: None
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] Filename: '/home/ubuntu/public_html/mounik/pootle/be'
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] PathInfo: '/gnome3/glib.glib-2-28.po/translate/'
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] Traceback (most recent call last):
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_ha
ndler, arg=req, silent=hlist.silent)
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_
target(config, req, object, arg)
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/python2.6/dist-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(ar
g)
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/pymodules/python2.6/django/core/handlers/modpython.py", line 228, in handler\n    return ModPythonHand
ler()(req)
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/pymodules/python2.6/django/core/handlers/modpython.py", line 219, in __call__\n    for chunk in respon
se:
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/pymodules/python2.6/django/http/__init__.py", line 408, in next\n    chunk = self._iterator.next()
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/home/ubuntu/public_html/mounik/pootle/local_apps/pootle_misc/dbupdate.py", line 276, in staggered_update\n    
for language in Language.objects.iterator():
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/pymodules/python2.6/django/db/models/query.py", line 269, in iterator\n    for row in compiler.results
_iter():
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/pymodules/python2.6/django/db/models/sql/compiler.py", line 672, in results_iter\n    for rows in self
.execute_sql(MULTI):
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/pymodules/python2.6/django/db/models/sql/compiler.py", line 727, in execute_sql\n    cursor.execute(sq
l, params)
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230]   File "/usr/lib/pymodules/python2.6/django/db/backends/postgresql_psycopg2/base.py", line 44, in execute\n    return s
elf.cursor.execute(query, args)
[Sat Apr 23 14:35:13 2011] [error] [client 66.249.72.230] DatabaseError: current transaction is aborted, commands ignored until end of transaction block\n
```

And here is what we get in postgresql error log:

```
2011-04-23 12:35:13 UTC ERROR:  relation "pootlecache" already exists
2011-04-23 12:35:13 UTC STATEMENT:  CREATE TABLE "pootlecache" (
            "cache_key" varchar(255) NOT NULL PRIMARY KEY,
            "value" text NOT NULL,
            "expires" timestamp with time zone NOT NULL
        );
2011-04-23 12:35:13 UTC ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

I dropped pootlecache table through psql cmdline client and then upgrade process ran successful.

I assume there is something wrong with upgrade process for pootlecache tables.

**Comment by dwaynebailey** [comment]
Closing as we've sorted out postgress testing a d support post 2.5.0
