### ISSUE TITLE
Pootle Error Saying: too many SQL variables

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1932]
_See also:_
- https://code.djangoproject.com/ticket/16426

_Version: 2.1.x_

_Originally posted by Altin Ukshini:_

Everytime I try to delete a Project or a Language or whatever I keep getting this error.

``` pytb
pootle@myserver:~/Pootle-2.1.6$ python2.6 ./PootleServer
Starting server, listening on port 8080.
2011-05-22 00:02:19,313 INFO Starting Django server, listening on port 8080
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/__init__.py:19: DeprecationWarning: settings.DATABASE_* is deprecated; use settings.DATABASES instead.
  DeprecationWarning
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/__init__.py:60: DeprecationWarning: Short names for ENGINE in database configurations are deprecated. Prepend default.ENGINE with 'django.db.backends.'
  DeprecationWarning
/home/pootle/Pootle-2.1.6/external_apps/djblets/util/fields.py:72: DeprecationWarning: A Field class whose get_db_prep_value method hasn't been updated to take `connection` and `prepared` arguments.
  class Base64Field(models.TextField):
/home/pootle/Pootle-2.1.6/external_apps/djblets/util/fields.py:136: DeprecationWarning: A Field class whose db_type method hasn't been updated to take a `connection` argument.
  class JSONField(models.TextField):
/home/pootle/Pootle-2.1.6/external_apps/djblets/util/fields.py:136: DeprecationWarning: A Field class whose get_db_prep_save method hasn't been updated to take a `connection` argument.
  class JSONField(models.TextField):
2011-05-22 00:02:24,422 WARNING Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/fields/subclassing.py:80: DeprecationWarning: A Field class whose get_db_prep_lookup method hasn't been updated to take `connection` and `prepared` arguments.
  new_class = super(SubfieldBase, cls).__new__(cls, name, bases, attrs)
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/fields/subclassing.py:80: DeprecationWarning: A Field class whose get_db_prep_value method hasn't been updated to take `connection` and `prepared` arguments.
  new_class = super(SubfieldBase, cls).__new__(cls, name, bases, attrs)
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/contrib/csrf/middleware.py:6: DeprecationWarning: This import for CSRF functionality is deprecated.  Please use django.middleware.csrf for the middleware and django.views.decorators.csrf for decorators.
  DeprecationWarning
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/middleware/csrf.py:262: DeprecationWarning: CsrfResponseMiddleware and CsrfMiddleware are deprecated; use CsrfViewMiddleware and the template tag instead (see CSRF documentation).
  DeprecationWarning
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/core/context_processors.py:27: DeprecationWarning: The context processor at `django.core.context_processors.auth` is deprecated; use the path `django.contrib.auth.context_processors.auth` instead.
  DeprecationWarning
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loaders/filesystem.py:58: DeprecationWarning: 'django.template.loaders.filesystem.load_template_source' is deprecated; use 'django.template.loaders.filesystem.Loader' instead.
  DeprecationWarning
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loaders/app_directories.py:71: DeprecationWarning: 'django.template.loaders.app_directories.load_template_source' is deprecated; use 'django.template.loaders.app_directories.Loader' instead.
  DeprecationWarning
/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/contrib/auth/models.py:393: DeprecationWarning: The user messaging API is deprecated. Please update your code to use the new messages framework.
  category=DeprecationWarning)
[22/May/2011 00:02:25] "GET / HTTP/1.1" 200 4026
[22/May/2011 00:02:27] "GET /admin/ HTTP/1.1" 200 2523
[22/May/2011 00:02:30] "GET /admin/projects.html HTTP/1.1" 200 4393
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/pootle/Pootle-2.1.6/local_apps/pootle_app/views/admin/util.py", line 40, in decorated_f
    return f(request, *args, **kwargs)
  File "/home/pootle/Pootle-2.1.6/local_apps/pootle_app/views/admin/adminprojects.py", line 76, in view
    form=ProjectForm, exclude='description', can_delete=True)
  File "/home/pootle/Pootle-2.1.6/local_apps/pootle_app/views/admin/util.py", line 177, in edit
    formset, msg, objects = process_modelformset(request, model_class, queryset=queryset, **kwargs)
  File "/home/pootle/Pootle-2.1.6/local_apps/pootle_app/views/admin/util.py", line 161, in process_modelformset
    formset.save()
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/forms/models.py", line 482, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/forms/models.py", line 595, in save_existing_objects
    obj.delete()
  File "/home/pootle/Pootle-2.1.6/local_apps/pootle_project/models.py", line 93, in delete
    super(Project, self).delete(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/base.py", line 580, in delete
    collector.collect([self])
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/deletion.py", line 170, in collect
    field.rel.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/deletion.py", line 19, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/deletion.py", line 170, in collect
    field.rel.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/deletion.py", line 19, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/deletion.py", line 170, in collect
    field.rel.on_delete(self, field, sub_objs, self.using)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/deletion.py", line 19, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/deletion.py", line 168, in collect
    if not sub_objs:
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/query.py", line 113, in __nonzero__
    iter(self).next()
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/query.py", line 107, in _result_iter
    self._fill_cache()
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/query.py", line 772, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/query.py", line 273, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/sql/compiler.py", line 680, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/backends/sqlite3/base.py", line 234, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: too many SQL variables
```

**Comment by rvalle** [comment]
I am new to Pootle, following the installation guide, and I fall into this issue.

Trying to test pootle with --pre and not pre.

So, I arrived to this issue.

Even if this is an issue in Django, how do I get pootle to work? 

Does anybody have a workarround?

**Comment by phlax** [comment]
hi @rvalle this is very very old bug - so im wondering which docs you are following

if you jump onto https://gitter.im/translate/pootle we can probably help further
