### ISSUE TITLE
Sanitize search queries

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2048]
We don't currently sanitise search queries before using indexing, which can cause a user to inadvertently use Lucene/Xapian syntax, possibly resulting in a traceback (in the case of incorrect syntax). Here is a Lucene traceback when searching for "width:" (with the colon):

org.apache.lucene.queryParser.ParseException: Cannot parse 'width:*': '*' or '?' not allowed as first character in WildcardQuery

File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/core/handlers/base.py", line 111, in get_response
  response = callback(request, *callback_args, **callback_kwargs)
File "Pootle/local_apps/pootle_app/views/language/view.py", line 58, in decorated_f
  return f(request, translation_project, *args, **kwargs)
File "Pootle/local_apps/pootle_app/views/language/view.py", line 68, in decorated_f
  return f(request, translation_project, *args, **kwargs)
File "Pootle/local_apps/pootle_app/views/language/view.py", line 80, in translate
  return translate_page(request, units_query)
File "Pootle/local_apps/pootle_store/views.py", line 356, in translate_page
  step_queryset = get_search_step_query(request.translation_project, search_form, units_queryset)
File "Pootle/local_apps/pootle_store/views.py", line 198, in get_search_step_query
  textquery = translation_project.indexer.make_query(word_querylist, False)
File "Pootle/translate/search/indexing/PyLuceneIndexer.py", line 184, in make_query
  return super(PyLuceneDatabase, self).make_query(*args, **kwargs)
File "Pootle/translate/search/indexing/CommonIndexer.py", line 177, in make_query
  analyzer=analyzer))
File "/var/www/sites/pootle/Pootle/translate/search/indexing/PyLuceneIndexer.py", line 273, in _create_query_for_field
  return qp.parse(value)
JavaError: org.apache.lucene.queryParser.ParseException: Cannot parse 'width:*': '*' or '?' not allowed as first character in WildcardQuery
    Java stacktrace:
org.apache.lucene.queryParser.ParseException: Cannot parse 'width:*': '*' or '?' not allowed as first character in WildcardQuery
  at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:205)
Caused by: org.apache.lucene.queryParser.ParseException: '*' or '?' not allowed as first character in WildcardQuery
  at org.apache.lucene.queryParser.QueryParser.getWildcardQuery(QueryParser.java:1010)
  at org.apache.lucene.queryParser.QueryParser.Term(QueryParser.java:1434)
  at org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1337)
  at org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1265)
  at org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1254)
  at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:200)

**Comment by dwaynebailey** [comment]
Pootle ``master`` has dropped all support for Xapian and Lucene so this is no longer an issue.
