### ISSUE TITLE
Handle too large form submits

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2057]
If we get a very large form upload in Pootle, it might surprise us a bit, and cause a lot of memory use. This is not extensively tested/verified, but from munin it looks as if our memory use went up by a few hundred megabytes at about the time when we got this traceback:

``` pytb
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/views/decorators/cache.py", line 79, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/sites/pootle/Pootle/local_apps/pootle_store/views.py", line 526, in translate
    return translate_page(request, store.units, store=store)
  File "/var/www/sites/pootle/Pootle/local_apps/pootle_store/views.py", line 384, in translate_page
    form.save()
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/forms/models.py", line 363, in save
    fail_message, commit, construct=False)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/forms/models.py", line 85, in save_instance
    instance.save()
  File "/var/www/sites/pootle/Pootle/local_apps/pootle_store/models.py", line 201, in save
    super(Unit, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/base.py", line 460, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/base.py", line 526, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/query.py", line 491, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/sql/compiler.py", line 869, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/models/sql/compiler.py", line 735, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/db/backends/mysql/base.py", line 86, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.6/dist-packages/MySQL_python-1.2.3-py2.6-linux-i686.egg/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.6/dist-packages/MySQL_python-1.2.3-py2.6-linux-i686.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1153, "Got a packet bigger than 'max_allowed_packet' bytes")
```

**Comment by jleclanche** [comment]
mstoning this to review as part of the new import feature
