### ISSUE TITLE
Tracebacks with Azeri locale

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2098]
_Version: 2.1.x_

It seems that the Azeri locale has the same or similar problems as the Turkish locale in Pootle. It seems trivially reproducable by setting the browser's accept-lang to Azeri (az). It causes some tracebacks like this:

unknown encoding: ANSI_X3.4-1968

``` pytb
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/sites/pootle/Pootle/local_apps/pootle_app/views/language/view.py", line 58, in decorated_f
    return f(request, translation_project, *args, **kwargs)
  File "/var/www/sites/pootle/Pootle/local_apps/pootle_app/views/language/view.py", line 68, in decorated_f
    return f(request, translation_project, *args, **kwargs)
  File "/var/www/sites/pootle/Pootle/local_apps/pootle_translationproject/views.py", line 233, in tp_overview
    context_instance=RequestContext(request))
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/shortcuts/__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loader.py", line 188, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/base.py", line 123, in render
    return self._render(context)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/base.py", line 117, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/base.py", line 744, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/base.py", line 757, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py", line 105, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loader_tags.py", line 102, in get_parent
    return get_template(parent)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loader.py", line 157, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loader.py", line 134, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loaders/filesystem.py", line 60, in load_template_source
    return _loader.load_template_source(template_name, template_dirs)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/template/loaders/filesystem.py", line 37, in load_template_source
    file = open(filepath)
LookupError: unknown encoding: ANSI_X3.4-1968
```

unknown encoding: ANSI_X3.4-1968

``` pytb
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/Django-1.3-py2.6.egg/django/views/static.py", line 46, in serve
    if os.path.isdir(fullpath):
  File "/usr/lib/python2.6/genericpath.py", line 41, in isdir
    st = os.stat(s)
LookupError: unknown encoding: ANSI_X3.4-1968
```

**Comment by Pike** [comment]
We're hitting this problem on verbatim, which is on 2.5.

Maybe this has something to do with the python version?
