### ISSUE TITLE
Do dependency checking in PootleServer

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#2155]
*Version: 2.1.x*

With missing dependencies, Pootle can report less than ideal error messages, which might not make it optimally easy for someone to fix their problem. Here is one example:

./PootleServer          
```pytb  
Traceback (most recent call last):
  File "./PootleServer", line 30, in <module>
    from pootle import PootleServer
  File "/home/main/Pootle-2.1.6/pootle/PootleServer.py", line 28, in <module>
    from django.core.servers.basehttp import AdminMediaHandler
  File "/usr/local/lib/python2.6/dist-packages/django/core/servers/basehttp.py", line 28, in <module>
    from django.contrib.staticfiles import handlers
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/staticfiles/handlers.py", line 8, in <module>
    from django.contrib.staticfiles.views import serve
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/staticfiles/views.py", line 15, in <module>
    from django.contrib.staticfiles import finders
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/staticfiles/finders.py", line 11, in <module>
    from django.contrib.staticfiles.storage import AppStaticStorage
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/staticfiles/storage.py", line 10, in <module>
    from django.core.cache import (get_cache, InvalidCacheBackendError,
  File "/usr/local/lib/python2.6/dist-packages/django/core/cache/__init__.py", line 76, in <module>
    if not settings.CACHES:
  File "/usr/local/lib/python2.6/dist-packages/django/utils/functional.py", line 185, in inner
    self._setup()
  File "/usr/local/lib/python2.6/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.6/dist-packages/django/conf/__init__.py", line 92, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'pootle.settings' (Is it on sys.path?): No module named translate.lang
```

**Comment by jleclanche** [comment]
No longer relevant, we have depchecks for the cases that are.
