### ISSUE TITLE
mozilla.l.org traceback - OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2468]
The following relates to bug #2467

The issue is the same this came about when working on Pootle and the underlying files had been inadvertently removed.

2

Traceback (most recent call last):
  File "/var/www/sites/mozilla/env/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_app/views/language/view.py", line 58, in decorated_f
    return f(request, translation_project, *args, **kwargs)
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_app/views/language/view.py", line 68, in decorated_f
    return f(request, translation_project, *args, **kwargs)
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_translationproject/views.py", line 192, in overview
    view_obj(request, translation_project, directory),
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_app/lib/view_handler.py", line 81, in __call__
    *args, **kwargs))
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_app/lib/view_handler.py", line 107, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_translationproject/views.py", line 682, in do_upload
    translation_project.scan_files()
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_translationproject/models.py", line 331, in scan_files
    self.real_path, self.directory)
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_app/project_tree.py", line 198, in add_files
    files, dirs = split_files_and_dirs(ignored_files, ext, podir_path, file_filter)
  File "/var/www/sites/mozilla/pootle/pootle/apps/pootle_app/project_tree.py", line 115, in split_files_and_dirs
    for child_path in [child_path for child_path in os.listdir(real_dir)
OSError: [Errno 2] No such file or directory: '/var/www/sites/mozilla/podirectory/firefox/sm'

<WSGIRequest
path:/sm/firefox/user4/browser/crashreporter/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'upload_to_dir': [u''], u'do_upload': [u'Upload'], u'csrfmiddlewaretoken': [u't4tm1oMAYJwyiyngsSPWGKdHbUpsztS1'], u'upload_to': [u''], u'overwrite': [u'merge']}>,
COOKIES:{'apertium_pairs': '%5B%7B%22source%22%3A%22ro%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22fr%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22gl%22%7D%2C%7B%22source%22%3A%22oc%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22ro%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22ca_valencia%22%7D%2C%7B%22source%22%3A%22mk%22%2C%22target%22%3A%22bg%22%7D%2C%7B%22source%22%3A%22fr%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22oc_aran%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22pt%22%2C%22target%22%3A%22gl%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22an%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22eu%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22fr%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22gl%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22pt%22%7D%2C%7B%22source%22%3A%22nb%22%2C%22target%22%3A%22nn_a%22%7D%2C%7B%22source%22%3A%22mk%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22en_US%22%7D%2C%7B%22source%22%3A%22pt%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22is%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22fr%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22gl%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22gl%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22oc_aran%22%7D%2C%7B%22source%22%3A%22nn%22%2C%22target%22%3A%22nb%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22oc%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22pt%22%7D%2C%7B%22source%22%3A%22oc_aran%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22oc%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22cy%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22fr%22%7D%2C%7B%22source%22%3A%22br%22%2C%22target%22%3A%22fr%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22bg%22%2C%22target%22%3A%22mk%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22oc_aran%22%7D%2C%7B%22source%22%3A%22sv%22%2C%22target%22%3A%22da%22%7D%2C%7B%22source%22%3A%22nn%22%2C%22target%22%3A%22nn_a%22%7D%2C%7B%22source%22%3A%22pt%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22pt_BR%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22oc%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22an%22%7D%2C%7B%22source%22%3A%22da%22%2C%22target%22%3A%22sv%22%7D%2C%7B%22source%22%3A%22it%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22gl%22%2C%22target%22%3A%22pt%22%7D%2C%7B%22source%22%3A%22eo%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22en_US%22%7D%2C%7B%22source%22%3A%22nn_a%22%2C%22target%22%3A%22nn%22%7D%2C%7B%22source%22%3A%22nb%22%2C%22target%22%3A%22nn%22%7D%5D',
 'csrftoken': 't4tm1oMAYJwyiyngsSPWGKdHbUpsztS1',
 'sessionid': '44037e474ab55c62cc6cce562a0271c3'},
META:{'CONTENT_LENGTH': '2456',
 'CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------7dc26f29a0d9e',
 'CSRF_COOKIE': 't4tm1oMAYJwyiyngsSPWGKdHbUpsztS1',
 'DOCUMENT_ROOT': '/htdocs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/html, application/xhtml+xml, */*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_COOKIE': 'sessionid=44037e474ab55c62cc6cce562a0271c3; apertium_pairs=%5B%7B%22source%22%3A%22ro%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22fr%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22gl%22%7D%2C%7B%22source%22%3A%22oc%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22ro%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22ca_valencia%22%7D%2C%7B%22source%22%3A%22mk%22%2C%22target%22%3A%22bg%22%7D%2C%7B%22source%22%3A%22fr%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22oc_aran%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22pt%22%2C%22target%22%3A%22gl%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22an%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22eu%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22fr%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22gl%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22pt%22%7D%2C%7B%22source%22%3A%22nb%22%2C%22target%22%3A%22nn_a%22%7D%2C%7B%22source%22%3A%22mk%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22en_US%22%7D%2C%7B%22source%22%3A%22pt%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22is%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22fr%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22gl%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22gl%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22oc_aran%22%7D%2C%7B%22source%22%3A%22nn%22%2C%22target%22%3A%22nb%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22oc%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22pt%22%7D%2C%7B%22source%22%3A%22oc_aran%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22oc%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22cy%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22fr%22%7D%2C%7B%22source%22%3A%22br%22%2C%22target%22%3A%22fr%22%7D%2C%7B%22source%22%3A%22en%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22bg%22%2C%22target%22%3A%22mk%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22eo%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22oc_aran%22%7D%2C%7B%22source%22%3A%22sv%22%2C%22target%22%3A%22da%22%7D%2C%7B%22source%22%3A%22nn%22%2C%22target%22%3A%22nn_a%22%7D%2C%7B%22source%22%3A%22pt%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22pt_BR%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22oc%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22an%22%7D%2C%7B%22source%22%3A%22da%22%2C%22target%22%3A%22sv%22%7D%2C%7B%22source%22%3A%22it%22%2C%22target%22%3A%22ca%22%7D%2C%7B%22source%22%3A%22gl%22%2C%22target%22%3A%22pt%22%7D%2C%7B%22source%22%3A%22eo%22%2C%22target%22%3A%22en%22%7D%2C%7B%22source%22%3A%22ca%22%2C%22target%22%3A%22es%22%7D%2C%7B%22source%22%3A%22es%22%2C%22target%22%3A%22en_US%22%7D%2C%7B%22source%22%3A%22nn_a%22%2C%22target%22%3A%22nn%22%7D%2C%7B%22source%22%3A%22nb%22%2C%22target%22%3A%22nn%22%7D%5D; csrftoken=t4tm1oMAYJwyiyngsSPWGKdHbUpsztS1',
 'HTTP_HOST': 'mozilla.locamotion.org',
 'HTTP_REFERER': 'http://mozilla.locamotion.org/sm/firefox/user4/browser/crashreporter/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)',
 'PATH': '/usr/local/bin:/usr/bin:/bin',
 'PATH_INFO': u'/sm/firefox/user4/browser/crashreporter/',
 'PATH_TRANSLATED': '/var/www/sites/mozilla/pootle/pootle.wsgi/sm/firefox/user4/browser/crashreporter/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '202.4.58.113',
 'REMOTE_PORT': '10748',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/sm/firefox/user4/browser/crashreporter/',
 'SCRIPT_FILENAME': '/var/www/sites/mozilla/pootle/pootle.wsgi',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '109.74.197.18',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'mozilla.locamotion.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '<address>Apache/2.2.14 (Ubuntu) Server at mozilla.locamotion.org Port 80</address>\n',
 'SERVER_SOFTWARE': 'Apache/2.2.14 (Ubuntu)',
 'mod_wsgi.application_group': 'mozilla.locamotion.org|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '80',
 'mod_wsgi.process_group': 'mozilla',
 'mod_wsgi.reload_mechanism': '1',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (2, 8),
 'wsgi.errors': <mod_wsgi.Log object at 0xba90b300>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0xba85d5c0>,
 'wsgi.input': <mod_wsgi.Input object at 0xba7e7cf0>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by dwaynebailey** [comment]
Same issues as #3783
