### ISSUE TITLE
Commit to VCS twice when no change has been made trigger error

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2860]
*Version: 2.5.0*

*Originally posted by Florent:*

Scenario :

-Change the localization value of a language
-Click on "Commit to VCS" link
-It will say : "Committed file pumpfacesystem/en-gb.po to version control"
-Click on the link "Commit to VCS" again without modifying the localization, it will trigger an error: 

```pytb
2013-04-18 11:04:17,307 ERROR Failed to commit file: [Mercurial] Error running '['hg', '-R', u'/usr/local/lib/python2.7/dist-packages/pootle/repos/pumpfacesystem', 'commit', '-m', u'Commit from Localization Server by user admin.: 506 of 506 strings translated (0 fuzzy).', '--user', u'admin', u'/usr/local/lib/python2.7/dist-packages/pootle/repos/pumpfacesystem/en-gb.po']': 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/views/language/view.py", line 47, in decorated_f
    return f(request, translation_project, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/views/language/view.py", line 63, in decorated_f
    return f(request, translation_project, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/views/language/view.py", line 115, in commit_file
    result = translation_project.commit_file(request.user, store, request)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_translationproject/models.py", line 727, in commit_file
    'filename': filename,
NameError: global name 'filename' is not defined
```

```
pootle@hudson:/var/log$ pootle --version
Pootle 2.5.0-rc1
Translate Toolkit 1.10.0
Django 1.4.1
```

Florent Valdelievre

**Comment by wthielen** [comment]
Happens to me too.
Mine is "Pootle 2.5.1.1 is powered by Translate Toolkit 1.12.0"

**Comment by julen** [comment]
The VCS feature has been taken away from Pootle, hence closing. It might come back at a certain point in time in the future but with a completely different shape.
