### ISSUE TITLE
Update against ALL templates link(in Administrate section) fails

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#2862]
*Version: 2.5.0*

*Originally posted by Florent Valdelievre:*

*Created [attachment 903](http://bugs.locamotion.org/attachment.cgi?id=903)*

screenshot

Pootle 2.5.0-rc1
Translate Toolkit 1.10.0
Django 1.4.1

Scenario:

-Click on 'Administrate' in your project
-Tick the box 'Update against templates' to select ALL languages
-Click on Save Changes

Stacktrace:

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_project/views.py", line 269, in project_admin
    exclude=('description',))
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/views/admin/util.py", line 223, in edit
    queryset=queryset, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/views/admin/util.py", line 204, in process_modelformset
    if formset.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 269, in is_valid
    err = self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 247, in _get_errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 290, in full_clean
    self._errors.append(form.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 115, in _get_errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 272, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 309, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 51, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 454, in save_form_data
    setattr(instance, self.name, data)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 362, in __set__
    (instance._meta.object_name, self.field.name))
ValueError: Cannot assign None: "TranslationProject.language" does not allow null values.
```

Explanation:

I think it is because it is sending the default value of the select box ( ------ ) as well. It should be omitted

Screenshot attached

**Comment by julen** [comment]
Update against templates is gone, closing.
