### ISSUE TITLE
Error when running createcachetable pootlecache: missing file

### ISSUE THREAD

**Issue by unho** [translate/pootle#3093]
Here is the traceback:

$ pootle createcachetable pootlecache
Loading custom settings from '/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/settings/90-local.conf'...

```pytb
Traceback (most recent call last):
  File "/srv/www/htdocs/pootle/env/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.5.0', 'console_scripts', 'pootle')()
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/runner.py", line 199, in main
    django_settings_module='pootle.settings')
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/runner.py", line 187, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 217, in execute
    translation.activate('en-us')
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 105, in activate
    return _trans.activate(language)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 194, in activate
    _active.value = translation(language)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 183, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 160, in _fetch
    app = import_module(appname)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_autonotices/__init__.py", line 24, in <module>
    from pootle_language.models import Language
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_language/models.py", line 30, in <module>
    from pootle_store.models import Unit
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 47, in <module>
    from pootle_store.filetypes import factory_classes, is_monolingual
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/filetypes.py", line 123, in <module>
    supported_formats = get_supported_formats()
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/filetypes.py", line 107, in get_supported_formats
    from translate.storage.subtitles import (SubRipFile, MicroDVDFile,
  File "/srv/www/htdocs/pootle/env/lib/python2.7/site-packages/translate/storage/subtitles.py", line 35, in <module>
    from aeidon import Subtitle
  File "/usr/lib/python2.7/site-packages/aeidon/__init__.py", line 120, in <module>
    from aeidon import languages
  File "/usr/lib/python2.7/site-packages/aeidon/languages.py", line 59, in <module>
    _init_languages()
  File "/usr/lib/python2.7/site-packages/aeidon/languages.py", line 33, in _init_languages
    for element in ET.parse(path).findall("iso_639_entry"):
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1183, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/usr/share/gaupol/iso-codes/iso_639.xml'
```

Probably this is because aeidon was installed, but not iso-codes.

**Comment by unho** [comment]
Closing since we no longer use `createcachetable pootlecache`.
