### ISSUE TITLE
Missing zip command

### ISSUE THREAD

**Issue by unho** [translate/pootle#3168]
Copied from http://sourceforge.net/mailarchive/forum.php?thread_name=CAFziTtFzTUqgC%2B-5HR40AYXQMm32VWzgb5SYFN-jBeb%3DW5a59w%40mail.gmail.com&forum_name=translate-pootle

On my server run (with apache and mod_wsgi) Pootle 2.5.1 installed by
pip. I can download a single file from a lang project but i recive an
error when i try to download a zip file whit all file inside.

An Example:
1) foo is a project
2) en is the language
3) file.po and pippo.po are 2 file inside en/foo/

I can download file.po or pippo.po one for time if i am on page:
en/foo/file.po or en/foo/pippo.po

But if im on en/foo/ and i try to download the zip file with inside
file.po and pippo.po i recive this message: Error accessing None,
Filesystem sent error: No such file or directory

```pytb
Traceback (most recent call last):
  File "/usr/pkg/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/pkg/lib/python2.7/site-packages/pootle/core/decorators.py", line 87, in wrapped
    return func(request, path_obj, *args, **kwargs)
  File "/usr/pkg/lib/python2.7/site-packages/pootle/core/decorators.py", line 180, in _wrapped
    return func(request, *args, **kwargs)
  File "/usr/pkg/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/views.py", line 783, in export_zip
    translation_project.get_archive(stores, abs_export_path)
  File "/usr/pkg/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/models.py", line 873, in get_archive
    cwd=self.abs_real_path)
  File "/usr/pkg/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/pkg/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by unho** [comment]
Not applicable anymore.
