### ISSUE TITLE
Long-running UI actions time out and cause data loss

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3228]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/__init__.py", line 776, in emit
    msg = self.format(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 654, in format
    return fmt.format(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 436, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.6/logging/__init__.py", line 306, in getMessage
    msg = msg % self.args
  File "/var/www/pootle/env/src/pootle-dev/pootle/apps/pootle_store/models.py", line 1407, in __str__
    store = self.convert(storeclass)
  File "/var/www/pootle/env/src/pootle-dev/pootle/apps/pootle_store/models.py", line 1900, in convert
    for unit in self.units.iterator():
  File "/var/www/pootle/env/src/pootle-dev/pootle/apps/pootle_store/models.py", line 1355, in units
    self.require_units()
  File "/var/www/pootle/env/src/pootle-dev/pootle/apps/pootle_store/models.py", line 1456, in require_units
    self.parse()
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/transaction.py", line 431, in inner
    return func(*args, **kwargs)
  File "/var/www/pootle/env/src/pootle-dev/pootle/apps/pootle_store/models.py", line 1536, in parse
    self.save()
  File "/var/www/pootle/env/src/pootle-dev/pootle/apps/pootle_store/models.py", line 1412, in save
    super(Store, self).save(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/pootle/env/src/pootle-dev/pootle/apps/pootle_store/models.py", line 1412, in save
    super(Store, self).save(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/pootle/env/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/var/www/pootle/env/lib/python2.6/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/pootle/env/lib/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '/nl/software/nl.po' for key 'pootle_path'")
```

**Comment by jleclanche** [comment]
RQ should fix this
