### ISSUE TITLE
null value in column "unit_id" violates not-null constraint

### ISSUE THREAD

**Issue by ralphvanetten** [translate/pootle#3258]
Hi, I installed Pootle using pip and I got version 2.6.0-rc1

When I select "Update against templates" for a language I get the error below. What does it mean?
I have another project in pootle and if I press update there I do not get this error. What could be wrong?

Thanks. 

```pytb
2014-09-04 17:51:56,362 WARNING Data integrity error while importing unit app_name\x04MEDsafe:

null value in column "unit_id" violates not-null constraint
DETAIL:  Failing row contains (312, unchanged, null, 60, Consider translating, f).

2014-09-04 17:51:56,367 ERROR Error while updating translation project against latest templates
Traceback (most recent call last):
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/views.py", line 110, in update_against_templates
    translation_project.update_against_templates()
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/models.py", line 558, in update_against_templates
    monolingual)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_app/project_tree.py", line 406, in convert_template
    store=output_file, fuzzy=True)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 431, in inner
    return func(*args, **kwargs)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1578, in update
    self.parse(store=store)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 431, in inner
    return func(*args, **kwargs)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1530, in parse
    self.unit_set.all().delete()
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 467, in delete
    collector.collect(del_query)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/deletion.py", line 166, in collect
    reverse_dependency=reverse_dependency)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/deletion.py", line 77, in add
    if not objs:
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 100, in __nonzero__
    self._fetch_all()
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/pootle/pootle/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by unho** [comment]
Not applicable anymore.
