### ISSUE TITLE
Invalid XLIFF file breaks template update

### ISSUE THREAD

**Issue by ambroisemaupate** [translate/pootle#3277]
We can't update our template file to add new units. Here is the way to reproduce:

* Go to our project
* Templates
* Clicked on *Upload*
* Choosed our new message.xlf file
* Choose *Override* => OK
* Boum, 

```pytb
Traceback (most recent call last):
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/core/decorators.py", line 110, in wrapped
    return func(request, path_obj, *args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/core/decorators.py", line 274, in _wrapped
    return func(request, *args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/core/decorators.py", line 241, in wrapped
    return func(request, path_obj, dir_path=dir_path, filename=filename, *args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_tagging/decorators.py", line 61, in wrapper
    return func(request, *args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/views.py", line 319, in overview
    'upload_form': _handle_upload_form(request, translation_project),
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/views.py", line 268, in _handle_upload_form
    store=upload_to)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/views.py", line 1013, in upload_file
    overwrite_file(request, relative_root_dir, django_file, upload_path)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/views.py", line 915, in overwrite_file
    store.update(update_structure=True, update_translation=True)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1598, in update
    self.parse(store=store)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1529, in parse
    store = self.file.store
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/fields.py", line 170, in store
    self._update_store_cache()
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/fields.py", line 191, in _update_store_cache
    classes=factory_classes)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/translate/storage/factory.py", line 188, in getobject
    store = storeclass.parsefile(storefile)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/translate/storage/base.py", line 829, in parsefile
    newstore = cls.parsestring(storestring)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/translate/storage/xliff.py", line 781, in parsestring
    xliff = super(xlifffile, cls).parsestring(storestring)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/translate/storage/base.py", line 728, in parsestring
    newstore.parse(storestring)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/translate/storage/lisa.py", line 341, in parse
    self.document = etree.fromstring(xml, parser).getroottree()
  File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70691)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106689)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105478)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:100105)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94543)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:96003)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95050)
XMLSyntaxError: Opening and ending tag mismatch: trans-unit line 57 and body, line 251, column 16
```

**Comment by julen** [comment]
Update from templates feature is gone, therefore closing.
