### ISSUE TITLE
Unknown error after submitting a unit

### ISSUE THREAD

**Issue by ambroisemaupate** [translate/pootle#3280]
![capture d ecran 2014-10-02 a 15 58 53](https://cloud.githubusercontent.com/assets/380026/4491892/c6a39840-4a3c-11e4-92ca-7fd32116a06c.png)

```pytb
Traceback (most recent call last):
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_misc/util.py", line 141, in wrapper
    return f(request, *args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/decorators.py", line 112, in decorated_f
    return f(request, unit, *args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/views.py", line 1095, in toggle_qualitycheck
    bool(request.POST.get("mute")), request.user)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1177, in toggle_qualitycheck
    self.store.save()
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1413, in save
    super(Store, self).save(*args, **kwargs)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) > 0
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 510, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/pootle/www/pootle/env/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
IntegrityError: ERREUR:  la nouvelle ligne viole la contrainte de vérification « pootle_store_store » de la relation « ck_failing_critical_count_pstv_235c09fc80c3a263 »
```

**Comment by unho** [comment]
This should be gone with the new stats.
