### ISSUE TITLE
[Core] Missing 'pootle/log' directory 

### ISSUE THREAD

**Issue by arky** [translate/pootle#3309]
The syncdb fails with following error "ValueError: Unable to configure handler 'log_action': [Errno 2] No such file or directory: '/home/arky/src/pootle/pootle/log/pootle-activity.log'. 

Here is a work-around:
```bash
$ mkdir pootle/log 
```

```pytb
$ python manage.py syncdb --noinput
Traceback (most recent call last):
  File "manage.py", line 32, in <module>
    cmd_log(*sys.argv)
  File "/home/arky/src/pootle/pootle/core/log.py", line 70, in cmd_log
    fn = settings.LOGGING.get('handlers').get('log_action').get('filename')
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/conf/__init__.py", line 50, in _setup
    self._configure_logging()
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/conf/__init__.py", line 80, in _configure_logging
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'log_action': [Errno 2] No such file or directory: '/home/arky/src/pootle/pootle/log/pootle-activity.log'
```

**Comment by dwaynebailey** [comment]
This was fixed in 5e66a967b

The directory exists in the repo.  Pootle will fail if the directory does not exist, so no we don't automatically create anything.
