### ISSUE TITLE
Updating languages in project causes traceback

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#333]
_Version: 0.6.3_

To reproduce:
Create new project, click on "Update languages"

Traceback (most recent call last):
  File "/home/fwolff/python//lib/python/jToolkit/web/simplewebserver.py", line
172, in serve_request
    thepage = self.server.handle(self, self.pathwords, argdict)
  File "/home/fwolff/python//lib/python/jToolkit/web/simplewebserver.py", line
369, in handle
    return self.jtoolkitserver.handle(req, pathwords, argdict)
  File "/home/fwolff/download/translate/src/Pootle/users.py", line 167, in handle
    return self.getpage(pathwords, session, argdict)
  File "/home/fwolff/download/translate/src/Pootle/pootle.py", line 185, in getpage
    return adminpages.ProjectAdminPage(self.potree, projectcode, session, argdict)
  File "/home/fwolff/download/translate/src/Pootle/adminpages.py", line 379, in
**init**
    raise ValueError("No languagecode given in doupdatelanguage")
ValueError: No languagecode given in doupdatelanguage

**Comment by linuxjackto1** [comment]
thanks www.movied.org
