### ISSUE TITLE
Bring back LDAP authentication under allauth

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3337]

**Comment by Akarienta** [comment]
+1 

I really need this feature, we cannot use Pootle without LDAP. Actually I have to keep using version 2.5.1. Do you have any idea when will LDAP come back?

**Comment by phlax** [comment]
@clementhk @akarienta we are going to try and get this back for the next release

**Comment by akarienta** [comment]
@phlax Thanks. Is there any way how to allow users to log in without password until they can use theirs LDAP passwords? We run Pootle in environment where is possible to have this setup.

**Comment by wiese** [comment]
This seemingly can be worked around by using django_auth_ldap.backend.LDAPBackend

pootle.conf
```
...

import ldap
from django_auth_ldap.config import LDAPSearch

AUTHENTICATION_BACKENDS = [
        'django_auth_ldap.backend.LDAPBackend',
        'django.contrib.auth.backends.ModelBackend',
        'allauth.account.auth_backends.AuthenticationBackend'
]

AUTH_LDAP_SERVER_URI = 'ldaps://ldap.mycompany.net:636'
AUTH_LDAP_BIND_DN = ""
AUTH_LDAP_BIND_PASSWORD = ""
AUTH_LDAP_USER_SEARCH = LDAPSearch("ou=user,dc=mycompany,dc=net", ldap.SCOPE_SUBTREE, "(uid=%(user)s)")

AUTH_LDAP_USER_ATTR_MAP = {
        'dn': 'uid',
        'first_name':'givenName',
        'last_name':'sn',
        'email':'mail'
}
```

**Comment by swoopdk** [comment]
@wiese 
I tried this but i get this error 

```(env)root@pootle:/opt/pootle# pootle runfcgi verbosity=3 debug=true outlog=/tmp/outlog errlog=/tmp/errlog host=127.0.0.1 port=8080
2016-05-20 14:15:55,215 INFO Loading custom settings from '/root/.pootle/pootle.conf'...
Traceback (most recent call last):
  File "/opt/pootle/env/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.7.3', 'console_scripts', 'pootle')()
  File "/opt/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 319, in main
    django_settings_module='pootle.settings')
  File "/opt/pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 275, in run_app
    caches = settings.CACHES.keys()
  File "/opt/pootle/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/opt/pootle/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/pootle/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'pootle.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named ldap```

**Comment by jleclanche** [comment]
You don't have the appropriate library installed.

**Comment by jleclanche** [comment]
@dwaynebailey if as @wiese says this can be recovered by just messing with settings, then it's just a documentation fix.

**Comment by wiese** [comment]
@swoopdk, @jleclanche Indidated the need to install python-ldap.

This is not to propagate this as a solution. It is clearly a work-around/hack (import in conf file) until a core developer verifies this as a viable solution.

**Comment by swoopdk** [comment]
Any workaround will be fine for me since i really need the LDAP auth or some central login like google apps for work. However i hav enever used python so the documentation for allauth is not helping me unfortunately :(

**Comment by jleclanche** [comment]
@wiese LDAP support itself is out of scope for Pootle, but it's important that Pootle isn't straight up incompatible with LDAP libraries (because of issues in the way we rewrote the auth stack).

If the settings changes you posted work as expected, then that's the extent Pootle supports LDAP - what remains is adding it to the documentation :)

**Comment by swoopdk** [comment]
After also doing a 
```pip install django-auth-ldap``` 

I could start it. However login doesn't work. Anybody know what logs i could check for any possible errors regarding this ?

Never did find any logs regarding the login failing.

**Comment by swoopdk** [comment]
Update:
I managed to get so far as to get a error log when i started the pootle server like this

```
(env)root@pootle:/opt/pootle/env/lib/python2.7# pootle runfcgi verbosity=90000 debug=true outlog=/tmp/outlog errlog=/tmp/errlog host=127.0.0.1 port=8000```

In my error log i get this now

```2016-05-23 13:01:33,221 WARNING Caught LDAPError while authenticating test: INVALID_CREDENTIALS({'desc': 'Invalid credentials'},)```
This is despite checking many times the values are correct. It seems it's the bind with ldap itself that fails as i get the same error regarless of login credentials used both in the pootle.conf file and the login window.

**Comment by dwaynebailey** [comment]
Only saw this update now.

@wiese thanks for posting those findings. And I agree with @jleclanche this is likely just a matter of converting this to docs.

My own tests I didn't get very far in that I kept struggling to get authenticated even though it had worked previously, but my LDAP knowledge is also very small.  Its also really difficult to test these things without a real LDAP instance.

**Comment by swoopdk** [comment]
I managed to get as far as this

`2016-05-23 14:06:08,116 DEBUG search_s('ou=People,dc=example,dc=com', 2, '(uid=%s)') returned 0 objects:
`
Or this

`2016-05-23 14:05:21,480 DEBUG search_s('ou=People,dc=example,dc=com', 2, '(uid=%(user)s)') returned 0 objects:`

Depending on what i have in my pootle.conf file. However if i replace the %(user)s or %s with a valid ldap username so that it reads '(uid=validLDAPUsername)' it gives me a 
`returned 1 objects
`
So i'm thinking i'm close here. But apparently the intered name variable is wrong or something ?

**Comment by dwaynebailey** [comment]
@swoopdk I'd suggest you drop into https://gitter.im/translate/pootle and ask there.

First glance is that I'm not sure how `%(users)s` would map to `AUTH_LDAP_USER_ATTR_MAP`, I'd assume it would need to be a key in that dict().

**Comment by swoopdk** [comment]
Seems i was too fast or tired when testing. The above does in fact work with a valid username and password. Also it seems with valid username and faulty password. 

So i would approve the above to be a valid way of doing ldap. Of course i'm just happy to have a workaroud that works. Thanks @wiese !

**Comment by wiese** [comment]
Hi @swoopdk,
my pleasure - we have a reproducible workaround. 
Here comes the question: Are you familiar enough with the original (pootle) ldap implementation to vouch for the fact that the full feature set previously present is restored by this configuration? Or can we find someone that does? Otherwise I am reluctant to call this a _solution_. 
Furthermore, the _import_ within the configuration file remains a smell and should be avoided. This is where we need the help (very limited effort) from the core developers to make this good...

Regards
wiese

**Comment by phlax** [comment]
hi @wiese i didnt use the original pootle ldap implementation, but i had a quick look at the current situation a while back.

From memory, it wasnt too difficult getting authentication working, but we need to add some code to get user data for session info. Im not clear if there was more to the original implementation than that.

If you drop into the the dev channel (https://gitter.im/translate/dev) i would be more than happy to discuss how best to get this feature back.

**Comment by swoopdk** [comment]
@wiese i'm not familiar with pootle at all to be honest. This install and LDAP setup is my first encounter so i cannot say if everything is working.

But feel free to tag me if you need me to test out anything regarding it.

**Comment by wiese** [comment]
Hi @jleclanche, @dwaynebailey,

adressing you because of your previous involvement... Given we have a second source to confirm the alternative configuration is indeed working, could you please advise on how we should proceed with this? Unfortunately my day job will not allow me to come up with a qualified PR any time soon.

Cheers

**Comment by dwaynebailey** [comment]
@wiese PR is always best.

At the moment we can't take these working examples and turn them into documentation on how to setup LDAP.  I don't think that's fair on Pootle users who're wanting to use LDAP or who are migrating from versions that did have LDAP support.

We do want to recover this feature but to land this I see LDAP needing:

- Code
- Documentation
- Getting other data from LDAP, not just authentication
- Testing on Travis

This requires time and effort.  Done right it means that LDAP is back, supported, tested and reliable.  The one way to make this happen is if @wiese and @swoopdk you contracted Translate to implement this properly.  You can contact me on https://gitter.im/translate/dev if that's an option for you.

Otherwise this issue will need to serve as the documentation for now.

**Comment by glensc** [comment]
2.5 has nice page how to do LDAP:

https://pootle.readthedocs.io/en/stable-2.5.1/features/authentication.html

but 2.7 doesn't even mention it's not possible:

http://docs.translatehouse.org/projects/pootle/en/stable-2.7.6/server/auth.html

should at least in documentation point to this ticket and say SORRY.

**Comment by glensc** [comment]
http://docs.translatehouse.org/projects/pootle/en/stable-2.7.6/releases/2.7.0.html
> `VCS_DIRECTORY` is now deprecated as the integrated Version Control feature has been removed to come back at a later date.

uh, seems LDAP dropping is not the only feature missing that I desperately need. seems i should migrate to 2.5.1 instead of 2.7 (i'm using 2.1.6 now as Pootle upgrade has always been pain)

**Comment by phlax** [comment]
hi @glensc this is unrelated to ldap. please file a separate bug, or add to a relevant ticket.

I would be more than happy to discuss the status of both of the issues that you have raised on our chat channel https://gitter.im/translate/pootle if that would be helpful

**Comment by glensc** [comment]
VCS is already addressed: #3341

moved discussion to gitter:
https://gitter.im/translate/pootle?at=57683481f0528c4c5bbae060
