### ISSUE TITLE
Uploading file without browsing causes traceback

### ISSUE THREAD

**Issue by friedelwolff** [translate/pootle#334]
_Version: 0.6.3_

To reproduce:
In a new language in a new project, click "upload file" without first browsing.

Traceback (most recent call last):
  File "/home/fwolff/python//lib/python/jToolkit/web/simplewebserver.py", line
172, in serve_request
    thepage = self.server.handle(self, self.pathwords, argdict)
  File "/home/fwolff/python//lib/python/jToolkit/web/simplewebserver.py", line
369, in handle
    return self.jtoolkitserver.handle(req, pathwords, argdict)
  File "/home/fwolff/download/translate/src/Pootle/users.py", line 167, in handle
    return self.getpage(pathwords, session, argdict)
  File "/home/fwolff/download/translate/src/Pootle/pootle.py", line 264, in getpage
    return indexpage.ProjectIndex(project, session, argdict)
  File "/home/fwolff/download/translate/src/Pootle/indexpage.py", line 267, in
**init**
    self.handleactions()
  File "/home/fwolff/download/translate/src/Pootle/indexpage.py", line 326, in
handleactions
    raise ValueError(self.localize("Cannot upload file, no file attached"))
ValueError: Cannot upload file, no file attached

**Comment by linuxjackto1** [comment]
thanks www.movied.org
