### ISSUE TITLE
Rescanning project directory files fails when the same key name exists in different files.

### ISSUE THREAD

**Issue by jason-p-pickering** [translate/pootle#3347]
```pytb
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
2014-11-13 09:44:29,980 WARNING Data integrity error while importing unit edit_profile:
(1062, "Duplicate entry '175-d445af6ff723ac6da265f6ec2ce20db9' for key 'pootle_store_unit_store_id_1f16b986f8b3b0db_uniq'")
2014-11-13 09:44:29,982 ERROR Error while rescanning translation project files
Traceback (most recent call last):
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/views.py", line 91, in rescan_files
    store.update(update_structure=True, update_translation=True)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1598, in update
    self.parse(store=store)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1550, in parse
    self.unit_set.all().delete()
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 467, in delete
    collector.collect(del_query)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/deletion.py", line 166, in collect
    reverse_dependency=reverse_dependency)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/deletion.py", line 77, in add
    if not objs:
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 100, in __nonzero__
    self._fetch_all()
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/backends/util.py", line 47, in execute
    self.db.validate_no_broken_transaction()
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/backends/__init__.py", line 372, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by dwaynebailey** [comment]
Rescan is no longer an available option
