### ISSUE TITLE
'RelatedManager' object has no attribute 'with_obsolete'

### ISSUE THREAD

**Issue by unho** [translate/pootle#3358]
Hit this when trying to upload a file on current master branch:

```pytb
Traceback (most recent call last):
  File "/home/leo/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/leo/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/leo/Escritorio/repos/pootle/pootle/core/decorators.py", line 110, in wrapped
    return func(request, path_obj, *args, **kwargs)
  File "/home/leo/Escritorio/repos/pootle/pootle/core/decorators.py", line 274, in _wrapped
    return func(request, *args, **kwargs)
  File "/home/leo/Escritorio/repos/pootle/pootle/core/decorators.py", line 241, in wrapped
    return func(request, path_obj, dir_path=dir_path, filename=filename, *args, **kwargs)
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_tagging/decorators.py", line 61, in wrapper
    return func(request, *args, **kwargs)
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_translationproject/views.py", line 318, in overview
    'upload_form': _handle_upload_form(request, translation_project),
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_translationproject/views.py", line 254, in _handle_upload_form
    translation_project.scan_files(vcs_sync=False)
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_translationproject/models.py", line 616, in scan_files
    file_filter,
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_app/project_tree.py", line 250, in add_files
    fs_subdir, db_subdir, file_filter)
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_app/project_tree.py", line 250, in add_files
    fs_subdir, db_subdir, file_filter)
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_app/project_tree.py", line 250, in add_files
    fs_subdir, db_subdir, file_filter)
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_app/project_tree.py", line 233, in add_files
    lambda name: create_or_resurrect_store(
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_app/project_tree.py", line 175, in add_items
    item = create_or_resurrect_db_item(name)
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_app/project_tree.py", line 237, in <lambda>
    translation_project=translation_project,
  File "/home/leo/Escritorio/repos/pootle/pootle/apps/pootle_app/project_tree.py", line 189, in create_or_resurrect_store
    Store.objects.with_obsolete().filter(parent=parent, name=name) \
AttributeError: 'RelatedManager' object has no attribute 'with_obsolete'
```

**Comment by unho** [comment]
Not applicable anymore.
