### ISSUE TITLE
Core: migration errors on current core

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3378]
The following [migration error](https://travis-ci.org/dwaynebailey/pootle/jobs/42280857#L1816-L1888) occurs on ``core`` after cleaning up the Travis builds. The migrations are from a scratch install.  While we might not need them they should be fixed as they're potentially masking other errors in the code which can't be found while Travis is failing.

```sql
2014-11-27 08:10:25,512 DEBUG execute "
            UPDATE staticpages_agreement as A
            JOIN auth_user AS U on A.user_id = U.id
            JOIN pootle_app_pootleprofile PP on U.id = PP.user_id
            SET A.new_user_id = PP.id;
        " with params "[]"
FATAL ERROR - The following SQL query failed: 
            UPDATE staticpages_agreement as A
            JOIN auth_user AS U on A.user_id = U.id
            JOIN pootle_app_pootleprofile PP on U.id = PP.user_id
            SET A.new_user_id = PP.id;
        
The error was: (1146, "Table 'pootle.auth_user' doesn't exist")
 ! Error found during real run of migration! Aborting.
 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.
! You *might* be able to recover with:   (migration cannot be dry-run; cannot discover commands)
 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: staticpages:0012_data__adjust_pks
```
```pytb
Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    execute_from_command_line()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/travis/build/dwaynebailey/pootle/pootle/apps/staticpages/migrations/0012_data__adjust_pks.py", line 23, in forwards
    ''')
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'pootle.auth_user' doesn't exist")
```

**Comment by unho** [comment]
@dwaynebailey Is this fixed on the new master?

**Comment by dwaynebailey** [comment]
@unho yes they're fixed, but only because ``core`` dropped all migrations.
