### ISSUE TITLE
Core: error in initdb in current core branch

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3379]
[This error](https://travis-ci.org/dwaynebailey/pootle/jobs/42280857#L1889-L1943) occurs in the ``initdb`` stage of a Pootle install on ``core`` branch.  This error occurs after some Travis cleanups to get the Travis builds working on ``core``.

```pytb
$ coverage run --parallel-mode manage.py initdb --traceback
2014-11-27 08:10:26,282 INFO Using Python PO
2014-11-27 08:10:26,537 INFO Populating the database.
Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    execute_from_command_line()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/travis/build/dwaynebailey/pootle/pootle/apps/pootle_app/management/commands/initdb.py", line 37, in handle_noargs
    initdb()
  File "/home/travis/build/dwaynebailey/pootle/pootle/core/initdb.py", line 38, in initdb
    create_revision()
  File "/home/travis/build/dwaynebailey/pootle/pootle/core/initdb.py", line 52, in create_revision
    Revision.objects.get_or_create(id=1)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/query.py", line 376, in get_or_create
    return self.get(**lookup), False
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'pootle.pootle_app_revision' doesn't exist")
```

**Comment by unho** [comment]
@dwaynebailey It seems like this is fixed, isn't it?

**Comment by jleclanche** [comment]
Yes I think so

**Comment by dwaynebailey** [comment]
@unho yes since I've run ``initdb`` on ``core`` its fixed.
