### ISSUE TITLE
Searching with non-ascii text causes crash

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#341]
_Version: 0.7a1_

Searching using this test: &#1655;&#1655;&#1655;&#1658;&#1659;&#7698;&#7699;&#7740;&#7741;&#7748;&#7749;&#7753;&#7754;&#7792;&#7793; (non-ascii text including Venda)
causes the following traceback:

2006-03-24 03:13:32: Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/jToolkit/web/simplewebserver.py", line
173, in serve_request
    thepage = self.server.handle(self, self.pathwords, argdict)
  File "/usr/lib/python2.4/site-packages/jToolkit/web/simplewebserver.py", line
445, in handle
    return self.jtoolkitserver.handle(req, pathwords, argdict)
  File "/usr/lib/python2.4/site-packages/Pootle/users.py", line 167, in handle
    return self.getpage(pathwords, session, argdict)
  File "/usr/lib/python2.4/site-packages/Pootle/pootle.py", line 273, in getpage
    return translatepage.TranslatePage(project, session, argdict, dirfilter)
  File "/usr/lib/python2.4/site-packages/Pootle/translatepage.py", line 50, in
**init**
    self.finditem()
  File "/usr/lib/python2.4/site-packages/Pootle/translatepage.py", line 260, in
finditem
    self.pofilename, self.item = self.project.searchpoitems(self.pofilename,
self.lastitem, search).next()
  File "/usr/lib/python2.4/site-packages/Pootle/projects.py", line 782, in
searchpoitems
    if pogrepfilter.filterelement(thepo):
  File "/usr/lib/python2.4/site-packages/translate/tools/pogrep.py", line 85, in
filterelement
    if self.matches(unquotedid): return True
  File "/usr/lib/python2.4/site-packages/translate/tools/pogrep.py", line 60, in
matches
    found = teststr.find(self.searchstring.decode("UTF-8")) != -1
  File "/usr/lib/python2.4/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-14:
ordinal not in range(128)

This relates to changes made to the command line version of pogrep.  We need the
ability to tell pogrep what encoding the search test is in

**Comment by linuxjackto1** [comment]
thanks www.movied.org
