### ISSUE TITLE
Pip 1.3.1 doesn't support "--allow-external"  "--allow-unverified" 

### ISSUE THREAD

**Issue by arky** [translate/pootle#3411]
Pip fails to process  "--allow-external " directive in requirements/base.txt  on on Ubuntu 14.10 

$ pip install -r requirements/dev.txt 
```pytb
------------------------------------------------------------
/home/arky/.virtualenvs/pootle/bin/pip run on Sat Dec  6 08:03:35 2014
Exception:
Traceback (most recent call last):
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 240, in run
    for req in parse_requirements(filename, finder=finder, options=options):
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1314, in parse_requirements
    for item in parse_requirements(req_url, finder, comes_from=filename, options=options):
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1314, in parse_requirements
    for item in parse_requirements(req_url, finder, comes_from=filename, options=options):
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1356, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 118, in from_line
    return cls(req, comes_from, url=url)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 43, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2510, in parse
    reqs = list(parse_requirements(s))
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2436, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/arky/.virtualenvs/pootle/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2404, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', '--allow-external pyDes', 'at', ' pyDes')
```

$ pip --version
pip 1.3.1 from /home/arky/.virtualenvs/pootle/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg (python 2.7)

$ $ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

**Comment by jleclanche** [comment]
pyDES is gone in allauth but essentially could go away now. with that said, we don't care about old versions of pip, so closing right now
