### ISSUE TITLE
Granting rights to a non-existing user returns error

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#344]
_Version: 0.7a1_

_Originally posted by Oscar Manuel Gómez Senovilla:_

When adding a user for granting rights on a language, apart from being
case-sensitive (not bad, but there could be a suggestion if there's a non-case
sensitive match before throwing error), a code error is returned:

2006-03-30 23:52:08: Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/jToolkit/web/simplewebserver.py", line
173, in serve_request
    thepage = self.server.handle(self, self.pathwords, argdict)
  File "/usr/lib/python2.4/site-packages/jToolkit/web/simplewebserver.py", line
445, in handle
    return self.jtoolkitserver.handle(req, pathwords, argdict)
  File "/usr/lib/python2.4/site-packages/Pootle/users.py", line 167, in handle
    return self.getpage(pathwords, session, argdict)
  File "/usr/lib/python2.4/site-packages/Pootle/pootle.py", line 266, in getpage
    return adminpages.TranslationProjectAdminPage(self.potree, project, session,
argdict)
  File "/usr/lib/python2.4/site-packages/Pootle/adminpages.py", line 447, in
**init**
    raise IndexError(self.localize("Cannot set rights for username %s - user
does not exist") % username)
IndexError: Cannot set rights for username xxxxx - user does not exist

I suggest to show a formal page saying something like "the user doesn't exist",
and proper navigation links.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
