### ISSUE TITLE
`pootle setup` fails on `no such table: pootlecache`

### ISSUE THREAD

**Issue by KINFOO** [translate/pootle#3446]
Hi,

Trying to setup a fresh Pootle __2.6.0-rc2__. I got the following:
```sh
$ pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
Django==1.6.9
Pootle==2.6.0-rc2
South==1.0
argparse==1.2.1
cssmin==0.2.0
diff-match-patch==20121119
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
django-allauth==0.16.1
django-assets==0.10
django-contact-form==1.0
django-taggit==0.11.1
lxml==3.4.1
oauthlib==0.7.2
python-Levenshtein==0.11.2
python-openid==2.2.5
requests==2.5.1
requests-oauthlib==0.4.2
six==1.9.0
translate-toolkit==1.13.0-rc1
webassets==0.10
wsgiref==0.1.2
$ pootle setup
2015-01-06 13:08:40,275 INFO Loading custom settings from '/home/poo/.pootle/pootle.conf'...
2015-01-06 13:08:40,453 INFO Using Python PO
2015-01-06 13:08:40,549 INFO Setting up a new Pootle installation.
Syncing...
Creating tables ...
Creating table django_session
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table django_content_type
Creating table django_site
Creating table django_admin_log
Creating table account_emailaddress
Creating table account_emailconfirmation
Creating table siteconfig_siteconfiguration
Creating table south_migrationhistory
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.sessions
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sites
 > django.contrib.admin
 > django.contrib.messages
 > django.contrib.staticfiles
 > allauth
 > allauth.account
 > djblets.siteconfig
 > django_assets
 > south

Not synced (use migrations):
 - accounts
 - pootle_app
 - pootle_store
 - pootle_language
 - pootle_project
 - pootle_translationproject
 - pootle_statistics
 - pootle_tagging
 - pootle_notifications
 - staticpages
 - allauth.socialaccount
 - taggit
(use ./manage.py migrate to migrate these)
Running migrations for accounts:
 - Migrating forwards to 0002_import_profile_data.
 > pootle_app:0001_initial
 > pootle_language:0001_initial
 > accounts:0001_initial
 > accounts:0002_import_profile_data
u'pootle_app_pootleprofile_alt_src_langs' does not exist. Creating table u'accounts_user_alt_src_langs' instead
Creating unique between u'accounts_user_alt_src_langs'.user_id<->u'accounts_user_alt_src_langs'.language_id
u'pootle_app_pootleprofile_alt_src_langs' does not exist. Creating table u'accounts_user_alt_src_langs' instead
Creating unique between u'accounts_user_alt_src_langs'.user_id<->u'accounts_user_alt_src_langs'.language_id
 - Loading initial data for accounts.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_app:
 - Migrating forwards to 0006_auto__del_suggestion.
 > pootle_translationproject:0001_initial
 > pootle_translationproject:0002_auto__del_field_translationproject_description_html__chg_field_transla
 > pootle_project:0001_initial
 > pootle_translationproject:0003_add_m2ms
 > pootle_translationproject:0004_auto__add_field_translationproject_total_wordcount__add_field_translat
 > pootle_translationproject:0005_auto__add_field_translationproject_disabled
 > pootle_translationproject:0006_auto__add_field_translationproject_failing_critical_count
 > pootle_store:0001_initial
 > pootle_app:0002_add_m2ms
 > pootle_store:0002_auto__add_tmunit
 > pootle_store:0003_add_m2ms
 > pootle_store:0004_auto__add_field_unit_creation_time
 > pootle_store:0005_auto__del_field_store_tm__del_field_store_pending
 > pootle_store:0006_auto__add_field_store_total_wordcount__add_field_store_translated_word
 > pootle_store:0007_auto__add_field_store_failing_critical_count
 > pootle_store:0008_auto__add_field_suggestion_reviewer__add_field_suggestion_translation_
 > pootle_statistics:0001_initial
 > pootle_statistics:0002_auto__add_field_submission_check
 > pootle_statistics:0003_auto__add_field_submission_suggestion
 > pootle_store:0009_move_data_from_pootle_app_suggestion
 - Migration 'pootle_store:0009_move_data_from_pootle_app_suggestion' is marked for no-dry-run.
2015-01-06 13:10:52,879 INFO {'PAS_LESS_THAN_PSS': 0, 'NO_PSS_FOR_PENDING_PAS': 0, 'NO_SUB_FOR_PAS': 0, 'DEL_REJECTED_PAS': 0, 'ONE_TO_ONE_COPY': 0, 'NO_PAS_FOR_PSS': 0, 'SUG_CREATED_FROM_SUB': 0, 'NO_UNIT_FOR_PAS': 0, 'MANY_TO_MANY_COPY': 0, 'PSS_LESS_THAN_PAS': 0, 'DUPLICATED_SUG': 0}
 > pootle_statistics:0004_auto__del_field_submission_from_suggestion
 > pootle_app:0003_auto__add_pootleconfig
 > pootle_app:0004_auto__add_pootlesite
 > pootle_app:0005_auto__add_field_permissionset_user
 > pootle_app:0006_auto__del_suggestion
 - Loading initial data for pootle_app.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_store:
 - Migrating forwards to 0011_update_user_to_profile.
 > pootle_store:0010_populate_translation_project_field
 - Migration 'pootle_store:0010_populate_translation_project_field' is marked for no-dry-run.
 > pootle_store:0011_auto__add_field_store_last_submission__add_field_store_last_unit
 > pootle_store:0011_update_user_to_profile
 - Migration 'pootle_store:0011_update_user_to_profile' is marked for no-dry-run.
 - Loading initial data for pootle_store.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_language:
 - Migrating forwards to 0002_auto__del_field_language_description_html__chg_field_language_descript.
 > pootle_language:0002_auto__del_field_language_description_html__chg_field_language_descript
 - Loading initial data for pootle_language.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_project:
 - Migrating forwards to 0006_auto__add_field_project_disabled.
 > pootle_project:0002_auto__del_field_project_description_html__chg_field_project_descriptio
 > pootle_project:0003_add_m2ms
 > pootle_project:0004_auto__del_field_project_report_target
 > pootle_project:0005_auto__add_field_project_report_email
 > pootle_project:0006_auto__add_field_project_disabled
 - Loading initial data for pootle_project.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_translationproject:
 - Migrating forwards to 0007_auto__add_field_translationproject_last_submission__add_field_translat.
 > pootle_translationproject:0007_auto__add_field_translationproject_last_submission__add_field_translat
 - Loading initial data for pootle_translationproject.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_statistics:
- Nothing to migrate.
 - Loading initial data for pootle_statistics.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_tagging:
 - Migrating forwards to 0001_initial.
 > pootle_tagging:0001_initial
 - Loading initial data for pootle_tagging.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pootle_notifications:
 - Migrating forwards to 0001_initial.
 > pootle_notifications:0001_initial
 - Loading initial data for pootle_notifications.
Installed 0 object(s) from 0 fixture(s)
Running migrations for staticpages:
 - Migrating forwards to 0011_auto__chg_field_legalpage_modified_on__chg_field_staticpage_modified_o.
 > staticpages:0001_initial
 > staticpages:0002_rename_app
 > staticpages:0003_auto__del_field_legalpage_body_html__chg_field_legalpage_body
 > staticpages:0004_auto__add_field_legalpage_virtual_path
 > staticpages:0005_data__slug_to_virtual_path
 - Migration 'staticpages:0005_data__slug_to_virtual_path' is marked for no-dry-run.
 > staticpages:0006_auto__del_field_legalpage_slug__chg_field_legalpage_virtual_path
 > staticpages:0007_auto__add_unique_legalpage_virtual_path
 > staticpages:0008_auto__del_field_legalpage_display_on_register
 > staticpages:0009_auto__add_staticpage
 > staticpages:0010_auto__add_agreement__add_unique_agreement_user_document__add_field_sta
2015-01-06 13:11:45,801 WARNING /home/poo/.local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.modified_on received a naive datetime (2015-01-06 13:11:45.800637) while time zone support is active.
  RuntimeWarning)

2015-01-06 13:11:45,802 WARNING /home/poo/.local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.modified_on received a naive datetime (2015-01-06 13:11:45.802407) while time zone support is active.
  RuntimeWarning)

2015-01-06 13:11:46,562 WARNING /home/poo/.local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.modified_on received a naive datetime (2015-01-06 13:11:46.561949) while time zone support is active.
  RuntimeWarning)

2015-01-06 13:11:47,731 WARNING /home/poo/.local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:903: RuntimeWarning: DateTimeField FakeModel.modified_on received a naive datetime (2015-01-06 13:11:47.731611) while time zone support is active.
  RuntimeWarning)

 > staticpages:0011_auto__chg_field_legalpage_modified_on__chg_field_staticpage_modified_o
 - Loading initial data for staticpages.
Installed 0 object(s) from 0 fixture(s)
Running migrations for socialaccount:
 - Migrating forwards to 0012_auto__chg_field_socialtoken_token_secret.
 > socialaccount:0001_initial
 > socialaccount:0002_genericmodels
 > socialaccount:0003_auto__add_unique_socialaccount_uid_provider
 > socialaccount:0004_add_sites
 > socialaccount:0005_set_sites
 - Migration 'socialaccount:0005_set_sites' is marked for no-dry-run.
 > socialaccount:0006_auto__del_field_socialapp_site
 > socialaccount:0007_auto__add_field_socialapp_client_id
 > socialaccount:0008_client_id
 - Migration 'socialaccount:0008_client_id' is marked for no-dry-run.
 > socialaccount:0009_auto__add_field_socialtoken_expires_at
 > socialaccount:0010_auto__chg_field_socialtoken_token
 > socialaccount:0011_auto__chg_field_socialtoken_token
 > socialaccount:0012_auto__chg_field_socialtoken_token_secret
 - Loading initial data for socialaccount.
Installed 0 object(s) from 0 fixture(s)
Running migrations for taggit:
 - Migrating forwards to 0002_unique_tagnames.
 > taggit:0001_initial
 > taggit:0002_unique_tagnames
 - Loading initial data for taggit.
Installed 0 object(s) from 0 fixture(s)
2015-01-06 13:12:23,586 INFO Populating the database.
2015-01-06 13:12:27,038 WARNING /home/poo/.local/lib/python2.7/site-packages/pootle/core/managers.py:30: DeprecationWarning: The "depth" keyword argument has been deprecated.
Use related field names instead.
  .select_related(depth=1)

Traceback (most recent call last):
  File "/home/poo/.local/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.6.0-rc2', 'console_scripts', 'pootle')()
  File "/home/poo/.local/lib/python2.7/site-packages/pootle/runner.py", line 171, in main
    django_settings_module='pootle.settings')
  File "/home/poo/.local/lib/python2.7/site-packages/pootle/runner.py", line 150, in run_app
    management.execute_from_command_line([runner_name] + remainder)
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/poo/.local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/setup.py", line 48, in handle_noargs
    call_command('initdb')
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/poo/.local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/initdb.py", line 37, in handle_noargs
    initdb()
  File "/home/poo/.local/lib/python2.7/site-packages/pootle/core/initdb.py", line 48, in initdb
    create_template_languages()
  File "/home/poo/.local/lib/python2.7/site-packages/pootle/core/initdb.py", line 255, in create_template_languages
    fullname=u'Templates')
  File "/home/poo/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/home/poo/.local/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get_or_create
    six.reraise(*exc_info)
  File "/home/poo/.local/lib/python2.7/site-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/home/poo/.local/lib/python2.7/site-packages/pootle/apps/pootle_language/models.py", line 160, in save
    cache.delete(CACHE_KEY)
  File "/home/poo/.local/lib/python2.7/site-packages/django/core/cache/backends/db.py", line 157, in delete
    cursor.execute("DELETE FROM %s WHERE cache_key = %%s" % table, [key])
  File "/home/poo/.local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/poo/.local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/poo/.local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/poo/.local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 452, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: pootlecache
```
Is there a possible fix?

Kevin

**Comment by KINFOO** [comment]
This problem may be similar to #3093.

So I tried, the following:
```sh
$ pootle createcachetable pootlecache
$ pootle setup
```
Seems to work.

**Comment by unho** [comment]
@KINFOO 2.6 releases are no longer meant to be installed. Please use 2.5.1.1 instead.
