### ISSUE TITLE
update_against_templates DoesNotExist: Unit matching query does not exist.

### ISSUE THREAD

**Issue by dreasvandonselaar** [translate/pootle#3507]
When running update_against_templates  from my commandline (2.5.1.1):

```pytb
2015-01-19 17:07:38,960 INFO Loading custom settings from '/root/.pootle/pootle.conf'...
2015-01-19 17:19:42,450 ERROR Failed to run update_against_templates over /nl/project/.
Traceback (most recent call last):
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 51, in do_translation_project
    self.handle_translation_project(tp, **options)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/update_against_templates.py", line 32, in handle_translation_project
    translation_project.update_against_templates()
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/models.py", line 416, in update_against_templates
    monolingual)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_app/project_tree.py", line 407, in convert_template
    store=output_file, fuzzy=True)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 224, in inner
    return func(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1305, in update
    unit.save()
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 352, in save
    super(Unit, self).save(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/base.py", line 486, in save_base
    signals.pre_save.send(sender=origin, instance=self, raw=raw, using=using)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 172, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_autonotices/signals.py", line 109, in unit_updated
    dbcopy = Unit.objects.get(id=instance.id)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 366, in get
    % self.model._meta.object_name)
DoesNotExist: Unit matching query does not exist.
```

**Comment by unho** [comment]
This can be avoided with:

```diff
diff --git a/pootle/apps/pootle_autonotices/signals.py b/pootle/apps/pootle_autonotices/signals.py
index 99a5cc0..1a90f9a 100644
--- a/pootle/apps/pootle_autonotices/signals.py
+++ b/pootle/apps/pootle_autonotices/signals.py
@@ -106,7 +106,11 @@ def unit_updated(sender, instance, raw=False, **kwargs):
         return
 
     if instance.id is not None and instance.istranslated():
-        dbcopy = Unit.objects.get(id=instance.id)
+        try:
+            dbcopy = Unit.objects.get(id=instance.id)
+        except Exception:
+            return
+
         if dbcopy.istranslated():
             # Unit state didn't change, let's quit.
             return
```

**Comment by dreasvandonselaar** [comment]
That appears to have solved the issue indeed.

**Comment by unho** [comment]
Fixed by referenced commit.
