### ISSUE TITLE
refresh_stats creates this traceback on sqlite

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3540]
I get the following traceback when running ``refresh_stats`` on a sqlite database:

```pytb
2015-01-23 17:37:08,351 ERROR Failed to run refresh_stats over /zu/tutorial/'s files
Traceback (most recent call last):
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/__init__.py", line 74, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 101, in handle_all_stores
    **options)
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 228, in process
    self._set_last_updated_stats(store_fk_filter)
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 458, in _set_last_updated_stats
    del self.cache_values[key]['get_last_updated']
KeyError: 'get_last_updated'
```

**Comment by dwaynebailey** [comment]
An initial fix that works around the issue is this:

```diff
diff --git a/pootle/apps/pootle_app/management/commands/refresh_stats.py b/pootle/apps/pootle_app/man
index 059f58f..37e4491 100644
--- a/pootle/apps/pootle_app/management/commands/refresh_stats.py
+++ b/pootle/apps/pootle_app/management/commands/refresh_stats.py
@@ -428,7 +428,8 @@ class Command(PootleCommand):
             logger.info('Set mtime for %s' % key)
             cache.set(iri_to_uri(key + ':get_mtime'),
                       item['max_mtime'], None)
-            del self.cache_values[key]['get_mtime']
+            if 'get_mtime' in self.cache_values[key]:
+                del self.cache_values[key]['get_mtime']
 
     def _set_last_updated_stats(self, unit_filter):
         units = Unit.objects.all()
@@ -455,7 +456,8 @@ class Command(PootleCommand):
                     'snippet': unit.get_last_updated_message()
                 }
                 cache.set(iri_to_uri(key + ':get_last_updated'), res, None)
-                del self.cache_values[key]['get_last_updated']
+                if 'get_last_updated' in self.cache_values[key]:
+                    del self.cache_values[key]['get_last_updated']
 
     def register_refresh_stats(self, path):
         """Register that stats for current path is going to be refreshed"""
```

@julen what are your thoughts on this issue and the fix I made?  I only fixed those that I hit, there are others that follow this pattern.

**Comment by julen** [comment]
Forwarding to @ta2-1. My initial impression though is that the values should be there, so the error might be somewhere else and your patch only hides it.

**Comment by ta2-1** [comment]
@dwaynebailey, how can I reproduce it? can you share your sqlite db?

**Comment by dwaynebailey** [comment]
@ta2-1 I can share my sqlite DB but I've made quite a few changes to it so it might simply not work again.  The easiest way to replicate may be to create your own.  I got this very soon after doing: syncdb, migrate, initdb.  Then I did either refresh_stats OR update_stores, refresh_stats

**Comment by jleclanche** [comment]
I don't see this anymore, was it fixed?
