### ISSUE TITLE
update_stores MemoryError on large projects

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3545]
update_stores runs out of memory on really large projects.

To reproduce:

1. Setup new instance
2. Setup ``firefox`` project based on PO files used on mlo
3. Observer project does not show stats even after ``refresh_stats``
4. Run ``update_stores``.  Observe that about 70% is updated, after which the command gets Memory related tracebacks.

We've had these errors before and assumed that they were related to stats. But it seems that they are in fact related to large imports of stores.

**Comment by julen** [comment]
>  Observe that about 70% is updated, after which the command gets Memory related tracebacks.

What's the specific traceback? In which step of `refresh_stats` does it happen?

**Comment by dwaynebailey** [comment]
@julen here is the traceback.  Only thing reported is logging related from what I can see.

This occurred running ``update_stores -v 2 --project=firefox``, it only made it to gd which is not very encouraging. 

```pytb
2015-01-26 19:15:36,313 INFO Running update_stores over /gd/firefox/browser/chrome/browser/devtools/profiler.properties.po
2015-01-26 19:15:36,754 INFO Running update_stores over /gd/firefox/browser/chrome/browser/devtools/projecteditor.properties.po
2015-01-26 19:15:38,141 INFO Running update_stores over /gd/firefox/browser/chrome/browser/devtools/responsiveUI.properties.po
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
Exception MemoryError: MemoryError() in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0xaf72b18c>> ignored
Traceback (most recent call last):
  File "./manage.py", line 34, in <module>
    execute_from_command_line()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/__init__.py", line 135, in handle_noargs
    self.handle_all(**options)
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/update_stores.py", line 68, in handle_all
    super(Command, self).handle_all(**options)
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/__init__.py", line 154, in handle_all
    self.do_translation_project(tp, self.path, **options)
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/__init__.py", line 92, in do_translation_project
    self.name, store.pootle_path)
  File "/usr/lib/python2.7/logging/__init__.py", line 1604, in exception
    error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1596, in error
    root.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1186, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 757, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 887, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 810, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/home/dwayne/.virtualenvs/pootle/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/home/dwayne/.virtualenvs/pootle/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/home/dwayne/.virtualenvs/pootle/lib/python2.7/linecache.py", line 128, in updatecache
    lines = fp.readlines()
MemoryError
```

**Comment by julen** [comment]
We have [TPs bigger than Firefox](https://translate.evernote.com/projects/kb_evernote/) and `update_stores`, but we also run update/sync cycles continuously, thus greatly reducing to go through lots of directories/stores.

I ignore your HW specs or any other environment details, but the natural intuition is the number of TPs (181!) plus a relatively big project is resulting in creating lots of ORM models, which are heavy and can make the memory greatly grow when retrieving them in batches.

Also notice that a Python process [doesn't necessarily release memory to the OS](http://effbot.org/pyfaq/why-doesnt-python-release-the-memory-when-i-delete-a-large-object.htm), so if you watch the process in htop you'll see the process always growing.

I'd advise to trace the code path of `update_stores` when passing only a project argument, and logging memory usage along the way. This will allow identifying where the major memory growth happens.

As a workaround, you can run `update_stores` with one language at a time, i.e. every TP is handled in a separate process.

**Comment by jleclanche** [comment]
@julen we had similar issues with our version of refresh_stats. It's a combination of memory leaks in python-mysql and untouchable memory management in python itself. I don't think there is anything we can do about it other than architecture the commands so that we don't end up in this situation. Does refresh_stats make use of RQ for example?

**Comment by julen** [comment]
> I don't think there is anything we can do about it other than architecture the commands so that we don't end up in this situation.

As suggested above, measure the process, at the very least.

> Does refresh_stats make use of RQ for example?

Yes it does.

**Comment by julen** [comment]
Note that we'll very likely create a bg job for syncing on-disk contents to the DB upon project creation in #3547, and we could see that being integrated as part of `update_stores` too.

@ta2-1 and I were also discussing that adding bg jobs + doing one TP at a time would greatly reduce the memory usage in this case. This is in line with what @jleclanche suggested in his previous comment.

**Comment by dwaynebailey** [comment]
@julen I've tried with your suggested logging changes, but I also disabled DEBUG mode.  No error.  I'm now not totally sure which part it was.  But I suspect the issue was having DEBUG enabled as that generated reams of logs, enough I suspect to drop the computer.

I'll need to repeat the test without the logging changes just to confirm.

**Comment by julen** [comment]
`DEBUG = True` is a highly discouraged well-known memory hog, and it makes lots of sense you've run out of memory with that turned on. Please close the issue once you've confirmed.

**Comment by dwaynebailey** [comment]
Closing this.  The issue is almost certainly ``DEBUG = True``.
