### ISSUE TITLE
Empty projects crash when accessing the units endpoint

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3562]
Trying to reproduce #3547 a new project was initialized. 
Following traceback happens if you access to translate view for this project.

```python
Traceback (most recent call last):
  File "/Users/ta2_1/.virtualenvs/pootle1.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ta2_1/projects/pootle/pootle/apps/pootle_misc/util.py", line 106, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/ta2_1/projects/pootle/pootle/apps/pootle_store/views.py", line 483, in get_units
    units_by_path = groupby(units, lambda x: x.store.pootle_path)
TypeError: 'NoneType' object is not iterable
```

**Comment by julen** [comment]
Does the TP contain any units at all?

**Comment by ta2-1** [comment]
Units haven't been added yet.

**Comment by julen** [comment]
Potentially you wouldn't be hitting a translate endpoint with no units, but the crash shouldn't happen either and it should result in 404.
