### ISSUE TITLE
Data integrity error caused by duplicate PO entries causes traceback and broken stats results

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3564]
I think we've got used to data integrity errors but now they are causing issues on Pootle.

 These ones below are, I think, specifically caused by duplicate entries in the PO file.

The files are from the default terminology project.  The following cause the same error `km/terminology/GlossaryV3Computer.csv.po`, `pt_BR/terminology/vocabulario.po` and `zu/terminology/GM_zu_20090916.po`.  All have duplicate entries in the PO files.  They are counted correctly by `pocount` without errors.  However they fail `msgfmt` because of duplicate entries.  In the case of the `km` files the entries have both source and target identical.

After the first error occurs the stats update for that and subsequent projects shows that it is still needing updated stats.

Either we need to:
1. Manage duplicate entries more gracefully
2. Allow such duplicate entries (I guess we need to with format agnostic files in future)
3. At least not break stats results when such an error occurs

The following is the traceback that occured with `km/terminology/GlossaryV3Computer.csv.po`

``` pytb
(pootle)dwayne@heather-desktop:~/dev/pootle-dwayne$ ./manage.py update_stores
2015-01-29 15:35:30,798 INFO Using Python PO
2015-01-29 15:39:33,888 WARNING Data integrity error while importing unit Abstract:
(1062, "Duplicate entry '134-e353dbe42c8654f33588d4da0b517469' for key 'pootle_store_unit_store_id_74c4f25_uniq'")
2015-01-29 15:39:33,890 WARNING /home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py:129: Warning: Some non-transactional changed tables couldn't be rolled back
  return self.cursor.execute(query, args)

2015-01-29 15:39:33,890 ERROR Failed to run update_stores over /km/terminology/GlossaryV3Computer.csv.po
Traceback (most recent call last):
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/__init__.py", line 90, in do_translation_project
    self.handle_store(store, **options)
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/update_stores.py", line 62, in handle_store
    store.update(overwrite=overwrite, only_newer=not force)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_store/models.py", line 1636, in update
    self.parse(store=store)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/dwayne/dev/pootle-dwayne/pootle/apps/pootle_store/models.py", line 1581, in parse
    self.unit_set.all().delete()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/query.py", line 556, in delete
    collector.collect(del_query)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 168, in collect
    reverse_dependency=reverse_dependency)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 79, in add
    if not objs:
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/query.py", line 145, in __nonzero__
    self._fetch_all()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 386, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by unho** [comment]
> Allow such duplicate entries (I guess we need to with format agnostic files in future)

Is there any format that allows duplicate entries? PO doesn't (thus `msgfmt` failure), properties neither. If no format actually allows duplicates then we shouldn't allow them in agnostic.

**Comment by dwaynebailey** [comment]
@unho don't really want to debate the merits of any of that in this issue to be honest.

**Comment by dwaynebailey** [comment]
This might provide some more clues.  An error occured in a file that passes both msgfmt and pocount

```po
#: publishFtp.label
msgid ""
"_: Edit box appears beside this label\n"
"_: publishFtp.label\n"
"If publishing to a FTP site, enter the HTTP address to browse to:"
msgstr ""

#: publishhtp.label
msgid ""
"_: Edit box appears beside this label\n"
"_: publishhtp.label\n"
"If publishing to a FTP site, enter the HTTP address to browse to:"
msgstr ""
```
From the below traceback you can see the somehow it hasn't picked up the middle line either ``_: publishhtp.label\n`` or ``_: publishFtp.label\n`` which would make these entries unique.  That would explain why ``msgfmt`` and ``pocount`` don't complain.  Note that the ``_: .*\n`` format is an old KDE form of ``msgctxt`` it shouldn't of course have two entries as we see here.  Likely a bad parsing of the contect could be the cause.

```pytb
2015-02-12 21:31:58,930 INFO Using Python PO
2015-02-12 21:40:09,561 WARNING Data integrity error while importing unit _: Edit box appears beside this label
If publishing to a FTP site, enter the HTTP address to browse to::
UNIQUE constraint failed: pootle_store_unit.store_id, pootle_store_unit.unitid_hash
2015-02-12 21:40:09,568 ERROR Failed to run update_stores over /zu/firefox2/editor/ui/chrome/composer/pref-publish.dtd.po
Traceback (most recent call last):
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/__init__.py", line 77, in do_translation_project
    self.handle_store(store, **options)
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_app/management/commands/update_stores.py", line 62, in handle_store
    store.update(overwrite=overwrite, only_newer=not force)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_store/models.py", line 1643, in update
    self.parse(store=store)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_store/models.py", line 1595, in parse
    self.save()
  File "/Users/dwayne/dev/pootle-dwayne/pootle/apps/pootle_store/models.py", line 1433, in save
    super(Store, self).save(*args, **kwargs)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _save_table
    forced_update)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 723, in _do_update
    return filtered._update(values) > 0
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 600, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1004, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/__init__.py", line 386, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by dwaynebailey** [comment]
Excellent.  With the PO entries listed above we can replicate the issue.

**Comment by unho** [comment]
Proposed plan of action: Skip duplicate entries on TTK so Pootle doesn't have to deal with this at all.

**Comment by unho** [comment]
Reopened since the fix in TTK has been undone.

**Comment by dwaynebailey** [comment]
Closing this.  We're on new stats, and we now handle PO files with duplicate files and error properly.  So it probably won't repeat.  Lets open in new context if needed.
