### ISSUE TITLE
Traceback on refresh_stats

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3599]
I get this on the LO database that I've migrated to master.  This error is reported on the ``rqworker`` log, but it's within RQ itself, but I can't determine what we are supplying that might be causing this issue. 

I'm guessing here, wonder if something in the project code is causing the non-ascii issue.  The underscore character is outside of 127 bytes so in UTF8 and the project is ``libo_ui``

```pytb
2015-02-23 12:15:49,120 ERROR Failed to run refresh_stats over /af/libo_ui/'s files
Traceback (most recent call last):
  File "/home/dwayne/pootle/pootle/apps/pootle_app/management/commands/__init__.py", line 66, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/home/dwayne/pootle/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 101, in handle_all_stores
    translation_project.update_parent_cache()
  File "/home/dwayne/pootle/pootle/core/mixins/treeitem.py", line 480, in update_parent_cache
    update_cache.delay(p, all_cache_methods)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/rq/decorators.py", line 41, in delay
    timeout=self.timeout, result_ttl=self.result_ttl, depends_on=depends_on)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django_rq/queues.py", line 42, in enqueue_call
    return self.original_enqueue_call(*args, **kwargs)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django_rq/queues.py", line 38, in original_enqueue_call
    return super(DjangoRQ, self).enqueue_call(*args, **kwargs)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/rq/queue.py", line 188, in enqueue_call
    timeout=timeout, id=job_id, origin=self.name)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/rq/job.py", line 131, in create
    job.description = description or job.get_call_string()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/rq/job.py", line 519, in get_call_string
    args = ', '.join(arg_list)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 26: ordinal not in range(128)
```

**Comment by dwaynebailey** [comment]
The issues has been raised against RQ already https://github.com/nvie/rq/issues/405

The workings of a fix are in https://github.com/nvie/rq/pull/406 (it was closed unfortunately because of some confusion of with a similar issue).

The issue was triggered (a guess but almost certainly correct) our code passing objects which have Unicode in repr() when ``job.get_call_string()`` is called to produce a string like this because our jobs don't pass a description:

```py
pootle.core.mixins.treeitem.update_cache(<Project: LibreOffice 4.4 – UI>, ['get_checks', 'get_fuzzy_wordcount', 'get_last_action', 'get_last_updated', 'get_mtime', 'get_suggestion_count', 'get_total_wordcount', 'get_translated_wordcount'])
```

Our issue manifests because of the '–' in the project description.

Until this is fixed in RQ, workaround could be:

1. Don't use Unicode ranges in project descriptions 
2. Add our own job description instead of relying on ``job.get_call_string()``

**Comment by dwaynebailey** [comment]
A fix has landed upstream with https://github.com/nvie/rq/pull/492

**Comment by julen** [comment]
RQ 0.5.1 is out which will be picked by default when installing django-rq, so this issue is not applicable anymore. Feel free to reopen if deemed necessary.
