### ISSUE TITLE
Get rid of syspath_override

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3608]
This was introduced IIRC to allow Pootle to easily run from a checkout.  I don't think it is needed anymore and gets in the way of other code.

**Comment by jleclanche** [comment]
I'd love to get this into 2.7 but I don't think it's realistic. There's a lot of code relying on it.

We could start moving imports and such to use "pootle.apps." though.

**Comment by Pawamoy** [comment]
So Pootle won't work in Python 3.5 until `syspath_override` is removed?

```
$ python --version
Python 3.5.3
$ pootle --version
Traceback (most recent call last):
  File "/media/pawamoy/Data/isolated/virtualenvs/pootle/bin/pootle", line 7, in <module>
    from pootle.runner import main
  File "/media/pawamoy/Data/isolated/virtualenvs/pootle/lib/python3.5/site-packages/pootle/runner.py", line 20, in <module>
    import syspath_override  # noqa
ImportError: No module named 'syspath_override'
```

**Comment by arky** [comment]
@phlax Can you please take shot at this issue? Thanks!

**Comment by phlax** [comment]
hi @arky - yep will do - its gonna take me a little to get my dev env back up tho

**Comment by arky** [comment]
Thanks @phlax for patching this. 

@dwaynebailey  Could you please let me know if this patch resolves this problem. Thanks!

**Comment by phlax** [comment]
@arky i think this needs more work, as it breaks tests even further
