### ISSUE TITLE
`update_stores` fails after renaming directory and store from uppercase to lowercase

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#3659]
```
Traceback (most recent call last):
  File "/home/l10n/pootle/pootle/apps/pootle_app/management/commands/__init__.py", line 43, in do_translation_project
    process_stores = self.handle_translation_project(tp, **options)
  File "/home/l10n/pootle/pootle/apps/pootle_app/management/commands/update_stores.py", line 41, in handle_translation_project
    translation_project.scan_files()
  File "/home/l10n/pootle/pootle/apps/pootle_translationproject/models.py", line 375, in scan_files
    file_filter,
  File "/home/l10n/pootle/pootle/apps/pootle_app/project_tree.py", line 254, in add_files
    fs_subdir, db_subdir, file_filter)
  File "/home/l10n/pootle/pootle/apps/pootle_app/project_tree.py", line 254, in add_files
    fs_subdir, db_subdir, file_filter)
  File "/home/l10n/pootle/pootle/apps/pootle_app/project_tree.py", line 254, in add_files
    fs_subdir, db_subdir, file_filter)
  File "/home/l10n/pootle/pootle/apps/pootle_app/project_tree.py", line 224, in add_files
    file_filter)
  File "/home/l10n/pootle/pootle/apps/pootle_app/project_tree.py", line 125, in split_files_and_dirs
    for child_path in [child_path for child_path in os.listdir(real_dir)
OSError: [Errno 2] No such file or directory: '/home/l10n/production/serge/po/web_evernote/ar/resources/mail/PremiumGiftSubscriptionConfirmationStencil'
```

It happened because MySQL used case insensitive collation. So probably we shouldn't use it.

**Comment by julen** [comment]
But this is a deployment-specific thing, isn't it? If so, some docs warning about possible issues of using a case-insensitive collation would suffice, as Pootle won't be able to do anything.

**Comment by iafan** [comment]
We don't want to create a hard dependency on a specific collation type in a specific database. Moreover, changing collation type might affect searching functionality.

This is a bug that I think should better be addressed from the client side: if on update_stores we detect that some folder was renamed, we need to act accordingly. The easiest way is to treat it as if the old folder is gone and the new one is created.

**Comment by ta2-1** [comment]
Seems these queries solve the problem
```SQL
ALTER TABLE pootle_store_store MODIFY pootle_path varchar(255) collate utf8_bin;
ALTER TABLE pootle_app_directory MODIFY pootle_path varchar(255) collate utf8_bin;
ALTER TABLE pootle_app_directory MODIFY name varchar(128) collate utf8_bin;
ALTER TABLE pootle_store_store MODIFY name varchar(128) collate uft8_bin;
```

**Comment by unho** [comment]
@ta2-1 So can we close this issue?

**Comment by ta2-1** [comment]
It's not easy to solve this issue without creating
> a hard dependency on a specific collation type in a specific database.
We won't do it.

That four SQL queries don't affect the whole DB and the search functionality. It's valid for EN for MySQL. I didn't tested it on other DBs. But unfortunately we can't create a migration for these specific changes or include them to `initdb` script. 
@dwaynebailey, can you please add some warnings to the docs as @julen suggested [here](https://github.com/translate/pootle/issues/3659#issuecomment-90822500) or anything else you prefer.
