### ISSUE TITLE
TypeError: Related Field got invalid lookup: disabled

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3686]
I get this after ``migrate`` followed by ``initdb``.  The site is setup and running correctly and you can browse to the overview pages and stats are 100% correct.  The error occurs if you try to go to any of the editor pages.

@ta2-1 I'm guessing because it says 'disabled' that this might be related to your changes in 151d477

```pytb
Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/dwayne/dev/pootle/pootle/apps/pootle_misc/util.py", line 95, in wrapper
    return f(request, *args, **kwargs)
  File "/Users/dwayne/dev/pootle/pootle/apps/pootle_store/views.py", line 433, in get_units
    units_qs = Unit.objects.get_for_path(pootle_path, request.profile)
  File "/Users/dwayne/dev/pootle/pootle/apps/pootle_store/models.py", line 237, in get_for_path
    store__translation_project__disabled=False,
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    lookups, value)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1577, in get_lookup_constraint
    raise TypeError('Related Field got invalid lookup: %s' % lookup_type)
TypeError: Related Field got invalid lookup: disabled
```

**Comment by julen** [comment]
Indeed, and some tests need to be adjusted too.
