### ISSUE TITLE
UnboundLocalError: local variable 'queue' referenced before assignment

### ISSUE THREAD

**Issue by DavidOliver** [translate/pootle#3698]
I've checked out the master branch and am trying to install:

    $ POOTLE_SETTINGS=/srv/www/pootle/pootle.conf ./manage.py initdb
    2015-04-29 23:22:57,529 INFO Loading custom settings from '/srv/www/pootle/pootle.conf'...
    2015-04-29 23:22:57,648 INFO Using Python PO
    Traceback (most recent call last):
      File "./manage.py", line 22, in <module>
        execute_from_command_line()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 337, in execute
        self.check()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 371, in check
        all_issues = checks.run_checks(app_configs=app_configs, tags=tags)
      File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 59, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/srv/www/pootle/project/pootle/checks.py", line 101, in check_redis
        conn_settings = queue.connection.connection_pool.connection_kwargs
    UnboundLocalError: local variable 'queue' referenced before assignment

Perhaps the underlying problem is that I need to configure Redis, but looking at the code `checks.py` it looks to my novice eyes like it should output something more descriptive if that's the case, like "Make sure Redis is running". Is the code trying to read the settings of a connection which doesn't exist, meaning that `conn_settings` won't ever be set within the exception?

**Comment by julen** [comment]
Yes you do need Redis, but here the underlying issue is you haven't installed all the required dependencies, more precisely `django-rq`. Please install the deps using `pip install -r requirements/base.txt`.

@translate/core not sure if we should warn here about missing dependencies — this situation could only happen when running via a git clone after all.

**Comment by DavidOliver** [comment]
Database initialised now that the dependencies are installed. Thanks very much for the help, and sorry for creating the non-issue.

**Comment by marksweb** [comment]
I'm seeing this with a `pootle check`, despite having the redis dependencies installed;

``` bash
(pootle)mwalker@pootle:/var/www/django/pootle$ pip install django-rq
Requirement already satisfied (use --upgrade to upgrade): django-rq in ./lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): rq>=0.5.0 in ./lib/python2.7/site-packages (from django-rq)
Requirement already satisfied (use --upgrade to upgrade): django in ./lib/python2.7/site-packages (from django-rq)
Requirement already satisfied (use --upgrade to upgrade): click>=3.0 in ./lib/python2.7/site-packages (from rq>=0.5.0->django-rq)
Requirement already satisfied (use --upgrade to upgrade): redis>=2.7.0 in ./lib/python2.7/site-packages (from rq>=0.5.0->django-rq)

(pootle)mwalker@pootle:/var/www/django/pootle$ pip freeze
click==5.1
cssmin==0.2.0
diff-match-patch==20121119
Django==1.7.10
django-allauth==0.23.0
django-assets==0.11
django-contact-form==1.0
django-overextends==0.4.0
django-redis==4.2.0
django-redis-cache==1.6.0
django-rq==0.8.0
django-taggit==0.11.1
elasticsearch==1.6.0
lxml==3.4.4
msgpack-python==0.4.6
MySQL-python==1.2.5
oauthlib==1.0.3
Pootle==2.7.0
python-memcached==1.57
python-openid==2.2.5
redis==2.10.3
requests==2.7.0
requests-oauthlib==0.5.0
rq==0.5.5
six==1.9.0
sphinx-me==0.3
translate-toolkit==1.13.0
urllib3==1.12
webassets==0.11
```

**Comment by unho** [comment]
Are you getting exactly the same traceback? Do you have Redis up and running?

**Comment by marksweb** [comment]
Yeah redis was returning `PONG` so seemed fine.

It was odd though, despite what's installed, dropping in to python `redis_cache` couldn't be imported.

The full traceback was;

```bash
Traceback (most recent call last):
  File "/var/www/django/pootle/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.7.0', 'console_scripts', 'pootle')()
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 161, in main
    django_settings_module='pootle.settings')
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 140, in run_app
    management.execute_from_command_line([runner_name] + remainder)
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/django/core/management/commands/check.py", line 39, in handle
    self.check(app_configs=app_configs, tags=tags, display_num_errors=True)
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in check
    all_issues = checks.run_checks(app_configs=app_configs, tags=tags)
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 59, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/var/www/django/pootle/local/lib/python2.7/site-packages/pootle/checks.py", line 91, in check_redis
    conn_settings = queue.connection.connection_pool.connection_kwargs
UnboundLocalError: local variable 'queue' referenced before assignment
```

Unfortunately however, I've not had time to resolve our upgrade issues & let someone drop us back to the version we had up & running (2.6 RC2). Hopefully I can push for an upgrade, or a new system setup because I wanted to get the machine translation features in.

**Comment by julen** [comment]
It seems the assumption of the check is that it'll be able to successfully get a connection to the queue. That's a bug I'd say.

So taking into account that the actual exception is being swallowed there. Can you try adding
```python
raise e
```
right before the line that says (in `pootle/checks.py:91`):
```python
conn_settings = queue.connection.connection_pool.connection_kwargs
```

That will give a better insight of what's failing in the connection to the Redis queue. I'd also advise to [double-check the Redis connection settings](https://github.com/translate/pootle/blob/0d4828098dd277f09b0d25d2eb25e6a62bd784c0/pootle/settings/20-backends.conf#L30-L44) just in case your setup differs from the defaults.
