### ISSUE TITLE
Redis failed job: 'update_cached_job' not found

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3741]
Stats stay dirty due to rqworker erroring on LXDE:

```pytb
Traceback (most recent call last):
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/rq/worker.py", line 557, in perform_job
    rv = job.perform()
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/rq/job.py", line 490, in perform
    _job_stack.push(self.id)
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/var/www/pootle/env/local/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'update_cache_job'
```

**Comment by ta2-1** [comment]
when was rqworker restarted last time?

**Comment by ta2-1** [comment]
And how is rqworker run?

**Comment by julen** [comment]
Yeah, it might perfectly be that you updated Pootle code but didn't restart rqworker.

**Comment by jleclanche** [comment]
Yep that was it.
