### ISSUE TITLE
Error trying to download files

### ISSUE THREAD

**Issue by DarioZ86** [translate/pootle#3763]
```
[Wed May 27 09:32:27.983817 2015] [:error] [pid 18745] Traceback (most recent call last):
[Wed May 27 09:32:27.983881 2015] [:error] [pid 18745]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
[Wed May 27 09:32:27.983890 2015] [:error] [pid 18745]     response = callback(request, *callback_args, **callback_kwargs)
[Wed May 27 09:32:27.983895 2015] [:error] [pid 18745]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/decorators.py", line 86, in decorated_f
[Wed May 27 09:32:27.983902 2015] [:error] [pid 18745]     return f(request, store, *args, **kwargs)
[Wed May 27 09:32:27.983908 2015] [:error] [pid 18745]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/views.py", line 146, in download
[Wed May 27 09:32:27.983914 2015] [:error] [pid 18745]     store.sync(update_translation=True)
[Wed May 27 09:32:27.983918 2015] [:error] [pid 18745]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1370, in sync
[Wed May 27 09:32:27.983922 2015] [:error] [pid 18745]     disk_store = self.file.store
[Wed May 27 09:32:27.983925 2015] [:error] [pid 18745]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/fields.py", line 170, in store
[Wed May 27 09:32:27.983928 2015] [:error] [pid 18745]     self._update_store_cache()
[Wed May 27 09:32:27.983932 2015] [:error] [pid 18745]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/fields.py", line 176, in _update_store_cache
[Wed May 27 09:32:27.983935 2015] [:error] [pid 18745]     mod_info = self.getpomtime()
[Wed May 27 09:32:27.983938 2015] [:error] [pid 18745]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/fields.py", line 145, in getpomtime
[Wed May 27 09:32:27.983942 2015] [:error] [pid 18745]     file_stat = os.stat(self.realpath)
[Wed May 27 09:32:27.983945 2015] [:error] [pid 18745] OSError: [Errno 13] Permission denied: '/var/www/pootle/env/lib/python2.7/site-packages/pootle/po/ESO/it_IT/it.lang1.csv'
[Wed May 27 09:32:27.983953 2015] [:error] [pid 18745] 
```

The permissions are 0770 as any other translation file (looked to tutorial folder for that)

Furthermore, the csv files on server seem to not receive any translation in the Target column. Am I doing something wrong translating?

**Comment by dwaynebailey** [comment]
@DarioZ86 

Double check the ownership of the files. If the webserver isn't the owner or in the correct group then it won't be able to write.

In terms of reading the data from the CSV file.  I must say I've never tested CSV as a translation format on Pootle.

**Comment by DarioZ86** [comment]
Everything is working setting ownership. I didn't knew could have been the issue.

**Comment by xperseguers** [comment]
Would you mind explaining how to activate such debugging and where to look for? Cannot find the info in the doc, only found a `DEBUG` option which goes to the screen when something bad happens in frontend.

I currently have a problem downloading zip files (they are corrupted) and I'd like to try this solution before further investigating. thanks.
