### ISSUE TITLE
sync_stores fails if the TP is missing

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3783]
I get the following traceback when running sync_stores.  The server is LO post migration.  I'm not 100% sure why the directories for this specific project where not on the testing server.  But since they were missing I get the following traceback:

```pytb
2015-06-02 15:16:59,963 ERROR Failed to run sync_stores over /zh_TW/libo44_help/'s files
Traceback (most recent call last):
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_app/management/commands/__init__.py", line 54, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_app/management/commands/sync_stores.py", line 37, in handle_all_stores
    only_newer=not force
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_translationproject/models.py", line 306, in sync
    skip_missing=skip_missing, only_newer=only_newer)
  File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_store/models.py", line 1835, in sync
    store.savefile(store_path)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/translate/storage/base.py", line 787, in savefile
    storefile = open(storefile, mode)
IOError: [Errno 2] No such file or directory: u'/var/www/sites/translations.documentfoundation.org/translations/libo44_help/zh_TW/auxiliary.po'
```

I'm not 100% sure what the correct behaviour for the new ``update_stores`` ``sync_stores`` commands are.  I know update_stores will obsolete missing folders.  Should ``sync_stores`` not recreate them if they are missing on the filesystem but not obsolete in the database?

**Comment by dwaynebailey** [comment]
@ta2-1 would appreciate your thoughts on what the correct behaviour is in this instance.

**Comment by dwaynebailey** [comment]
Note that if I mkdir for the missing TP then ``sync_stores`` operates correctly.

**Comment by ta2-1** [comment]
@dwaynebailey, you are right there is an issue if TP directory is missed.
`sync_stores` command should recreate missing store files if `--skip-missing` option is not set.

**Comment by ta2-1** [comment]
@dwaynebailey 
There is a difference if you run `sync_stores` after you just remove a `Store` file from disk. Or you run `sync_stores` after you remove a `Store` file from disk and then run `update_stores`.
If `update_stores` marked a `Store` object as obsolete it shouldn't be recreated by `sync_stores`.

**Comment by ta2-1** [comment]
I can see from the code that `sync_stores` worked incorrectly even in 2.5.0.
- it doesn't check a parent path existence before file creating;
- it ignores directories in a store file path and creates a file by its name next to a TP directory as `os.path.join(TP.abs_real_path, store.name)`;
- it saves an abs store path to a DB.
