### ISSUE TITLE
LegalAgreement change break SQLite

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3785]
Its seems that the legal agreements changes in e454aab30863744966a556f7785ccdd38157a7ec break sqlite database setups.  I didn't have time to investigate but this is straight after ``migrate`` and ``initdb`` and a clean of ``.pyc`` files.

```pytb
2015-06-02 22:44:08,346 ERROR Internal Server Error: /projects/
Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/handlers/base.py", line 117, in get_response
    response = middleware_method(request, e)
  File "/Users/dwayne/dev/pootle/pootle/middleware/errorpages.py", line 79, in process_exception
    RequestContext(request))
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/context.py", line 209, in __init__
    updates.update(processor(request))
  File "/Users/dwayne/dev/pootle/pootle/apps/pootle_misc/context_processors.py", line 49, in pootle_context
    'display_agreement': _agreement_context(request),
  File "/Users/dwayne/dev/pootle/pootle/apps/pootle_misc/context_processors.py", line 26, in _agreement_context
    LegalPage.objects.has_pending_agreement(request.user)):
  File "/Users/dwayne/dev/pootle/pootle/apps/staticpages/managers.py", line 29, in has_pending_agreement
    return len(list(agreements)) > 0
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 1535, in __iter__
    query = iter(self.query)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/query.py", line 78, in __iter__
    self._execute_query()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/query.py", line 92, in _execute_query
    self.cursor.execute(self.sql, self.params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: TRUE
```

**Comment by jleclanche** [comment]
I should have mentioned that the sql wouldn't work on SQLite, but I didn't flag it as an issue because I didn't see us using the feature (I figured we would mark it as unsupported).

We should probably raise a `NotImplemented` before the query if we are on sqlite, and in the context processor, catch it, log a warning("legal pages not supported on sqlite") and always return an empty QS.

**Comment by jleclanche** [comment]
cc @julen

**Comment by julen** [comment]
SQLite [doesn't have a boolean datatype](http://www.sqlite.org/datatype3.html) (that's why `TRUE` is Greek to it), but you can use 0/1 instead.
