### ISSUE TITLE
Duplicate emails simply hang the interface

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3796]
If your Pootle setup has duplicate emails.  Then the signin simply hangs and doesn't report any errors.  Some of these could be eliminated by cleanup but I suspect other types of errors also wouldn't be reported.  My ideal is that this type of error is communicated to the user who can ask admins to intervene.

```pytb
Traceback (most recent call last):
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/views.py", line 94, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/views.py", line 62, in dispatch
    **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 827, in wrapper
    return wrapped(*args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/views.py", line 78, in post
    response = self.form_valid(form)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/views.py", line 102, in form_valid
    return form.login(self.request, redirect_url=success_url)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/forms.py", line 144, in login
    redirect_url=redirect_url)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/utils.py", line 130, in perform_login
    send_email_confirmation(request, user, signup=signup)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/utils.py", line 304, in send_email_confirmation
    confirm=True)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/allauth/account/managers.py", line 17, in add_email
    email_address = self.create(user=user, email=email)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)  
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)  
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)  
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)  
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)  
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)  
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)  
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry 'dwayne@translate.org.za' for key 'email'")
```

**Comment by julen** [comment]
Notice having unique emails is a pre-requisite.

**Comment by dwaynebailey** [comment]
@julen except of course when the error is unrelated to duplicate emails but something else.  In which case my guess is we block like this and the user is clueless.  Cleaning up duplicates is often not much of an option to do in advance of a migration.

**Comment by julen** [comment]
> Cleaning up duplicates is often not much of an option to do in advance of a migration.

Mind elaborating this? You have access to the DB, you can detect the issues and clean that up as much as needed before any migrations. The authentication UI has nothing to do with performing it. I'm talking out of first-hand experience.

**Comment by jleclanche** [comment]
@julen I think you fixed this, right?

**Comment by jleclanche** [comment]
As in, there's an appropriate error now.

**Comment by unho** [comment]
@julen Any input on this?

**Comment by julen** [comment]
I think people are referring to different issues here. The report talks about *duplicate emails*, but then it seems the expectation is that not all errors are exposed in the UI, which is a valid issue on its own.

**Comment by julen** [comment]
I have filed #4013 for the latter.

**Comment by phlax** [comment]
This was fixed by @julen 's UI update - at least if DEBUG=False in settings.

I have added some code so that the original error is not exposed to the end user - but i really think we need some better error handling in the auth backend so ive added a ticket for that #4053
