### ISSUE TITLE
Traceback when extracting terminology

### ISSUE THREAD

**Issue by julen** [translate/pootle#3819]
If one tries to generate a terminology using the extraction feature, the result is:

```python
Traceback (most recent call last):
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "~/dev/translate/pootle/pootle/core/decorators.py", line 107, in wrapped
    return func(request, path_obj, *args, **kwargs)
  File "~/dev/translate/pootle/pootle/core/decorators.py", line 316, in _wrapped
    return func(request, *args, **kwargs)
  File "~/dev/translate/pootle/pootle/apps/pootle_terminology/views.py", line 111, in extract
    for store in translation_project.stores.live()
  File "~/dev/translate/pootle/pootle/apps/pootle_terminology/views.py", line 111, in <genexpr>
    for store in translation_project.stores.live()
AttributeError: 'Store' object has no attribute '_get_total_wordcount'
```

Guess what, it's been broken quite a bit of time.

Instead of fixing this, I'm more in favor of dropping terminology auto-generation as people already mentioned in #3656.

**Comment by unho** [comment]
I am ok with dropping terminology auto-generation if we provide some fallback.

**Comment by dwaynebailey** [comment]
@unho can you explain what you mean by fallback.  People can already use terminology if there is a pootle-terminology.po file or get it from the Terminology project.  So it isn't a case of fallback, the usage exists just people need to make their terminology lists outside of Pootle

**Comment by gterzian** [comment]
In the meantime, here is a quick fix for the missing method: https://github.com/translate/pootle/pull/3832

**Comment by unho** [comment]
By fallback I meant provide some hints on docs about how to workaround the absence of the feature. For example "Use this tool to create PO files with terminology and added them to your project as `pootle-terminology.po for each TP in the project.`"
