### ISSUE TITLE
Action logger Unicode encoding issues

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3829]
The action_logger doesn't seems to be handling Unicode correctly.  First assumption was that it occurs in string submission.  But many of the same reports exist for muting a check, accepting a suggestion, etc.

The user who seems to be generating these is user Kü

```pytb
Traceback (most recent call last):
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 711, in __iter__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 1087, in __call__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_misc/util.py", line 65, in wrapper
File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_store/decorators.py", line 76, in decorated_f
File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_store/views.py", line 910, in submit
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/forms/models.py", line 455, in save
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/forms/models.py", line 103, in save_instance
File "/var/www/sites/translations.documentfoundation.org/src/pootle/apps/pootle_store/models.py", line 462, in save
File "/var/www/sites/translations.documentfoundation.org/src/pootle/core/log.py", line 51, in action_log
```

**Comment by julen** [comment]
An interesting thing to note here is that the validator for usernames is using `\w`, which is locale-dependent. This means that depending on configuration, servers can accept different chars as valid for usernames. In our case (EN) we operate on en_US, therefore only ASCII chars were used in such logs.
