### ISSUE TITLE
Migration pootle_app::0002_unique_pootle_path fails with existing duplicate paths

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3838]
The LO database fails on this migration because it has a duplicate pootle_path.  I simply manually removed the second one when I migrated the database.  I assume we can manage this automatically before the migration or as part of the migration.

```pytb
(pootle)dwayne@indlovu:~/pootle$ ./manage.py migrate pootle_app
2015-06-17 15:59:21,714 INFO Using Python PO
Operations to perform:
  Apply all migrations: pootle_app
Running migrations:
  Applying pootle_app.0002_unique_pootle_path...
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 139, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 470, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type, old_db_params, new_db_params, strict)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 647, in _alter_field
    self.execute(self._create_unique_sql(model, [new_field.column]))
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1062, "Duplicate entry '/tn/libo_ui/extras/' for key 'pootle_app_directory_pootle_path_5df55dc70abb5874_uniq'")
```

**Comment by unho** [comment]
Closing since a fix has been merged in 284d8e44.
