### ISSUE TITLE
Encoding error on Project language admin page

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3848]
This traceback occurs on the Project's language page i.e. the one where you add new TPs to the Project.  It doesn't occur on all pages, but I guess occurs on any which have language names that are not in ascii.

```pytb
Traceback (most recent call last):
  File "/home/dwayne/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dwayne/pootle/pootle/core/decorators.py", line 107, in wrapped
    return func(request, path_obj, *args, **kwargs)
  File "/home/dwayne/pootle/pootle/core/decorators.py", line 316, in _wrapped
    return func(request, *args, **kwargs)
  File "/home/dwayne/pootle/pootle/apps/pootle_project/views.py", line 123, in project_admin
    can_delete=True, form=tp_form_class)
  File "/home/dwayne/pootle/pootle/apps/pootle_app/views/admin/util.py", line 178, in edit
    'formset_text': mark_safe(form_set_as_table(formset, link, linkfield)),
  File "/home/dwayne/pootle/pootle/apps/pootle_app/views/admin/util.py", line 130, in form_set_as_table
    return u''.join(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 52: ordinal not in range(128)
```

**Comment by jleclanche** [comment]
Fixed by b15be5e99c82cca593fb8708dd7ebca51ffce0ed
