### ISSUE TITLE
Unicode usernames break user settings page

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3855]
Sorry this is via via a user.  And can't find the TB on new relic.

One LO we have a user with username Kü - when they try to edit their settings they encounter an error which seems to be an encoding error.  So likely to replicate it just requires making such a Unicode user and checking if they can reach ``/user/Kü/edit/`` without an error.

**Comment by jleclanche** [comment]
2.7?

**Comment by jleclanche** [comment]
I can't repro: http://pootle.lxde.org/user/K%C3%BC/edit/

**Comment by dwaynebailey** [comment]
@jleclanche yeah 2.7 LibreOffice, I asked him to try again and he gets it.  I think I silenced the wrong TB in newrelic so I'm not seeing it again :/

**Comment by jleclanche** [comment]
I created a user `Kü` on lxde and I'm not seeing any errors editing the profile.

**Comment by dwaynebailey** [comment]
This is a TB on mlo which could be the issue:

http://mozilla.locamotion.org/user/J%C4%81nis/settings/

exceptions:UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 1: ordinal not in range(128)

```pytb
Traceback (most recent call last):
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/api/web_transaction.py", line 711, in __iter__
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/api/web_transaction.py", line 1087, in __call__
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
File "/var/www/sites/mozilla/src/pootle/core/views.py", line 63, in dispatch
```

**Comment by jleclanche** [comment]
Sounds like a bug in newrelic's code.

**Comment by dwaynebailey** [comment]
Mmm think you might be right, though it still doesn't explain the guys getting a TB :/

**Comment by kamotos** [comment]
Not sure where I can write tests for this though. Wasn't able to locate tests for [pootle.core.views.TestUserFieldMixin](https://github.com/translate/pootle/blob/master/pootle/core/views.py#L48)

**Comment by dwaynebailey** [comment]
@kamotos glad you where able to replicate.  We don't have tests for everything.  I'm hoping @julen may be able to give you some pointers.

**Comment by unho** [comment]
For the record:

- It is not possible to create users with usernames holding characters like those in Admin, it just ask you to provide a valid username.
- It is not possible to replicate this issue unless you log as the problematic user and you visit your own settings.
