### ISSUE TITLE
Duplicate entry '0-89' for key 'pootleprofile_id

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3856]
This is on LibreOffice deployment at this URL https://translations.documentfoundation.org/user/indrit.bsh/settings/

I'm not 100% sure what the user is doing.   But I suspect we want to make sure there is some sort of PootleProfile cleanup if we do indeed have such duplicates post migration.

```pytb
Traceback (most recent call last):
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 711, in __iter__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/api/web_transaction.py", line 1087, in __call__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
File "/var/www/sites/translations.documentfoundation.org/src/pootle/core/views.py", line 68, in dispatch
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
File "/var/www/sites/translations.documentfoundation.org/src/pootle/core/views.py", line 45, in dispatch
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 872, in wrapper
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 230, in post
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 173, in post
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 149, in form_valid
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/forms/models.py", line 455, in save
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/forms/models.py", line 104, in save_instance
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/forms/models.py", line 100, in save_m2m
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 2298, in save_form_data
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1193, in __set__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 924, in add
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1042, in _add_items
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 409, in bulk_create
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 938, in _batched_insert
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/database_dbapi2.py", line 22, in execute
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
File "/var/www/sites/translations.documentfoundation.org/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
```

**Comment by jleclanche** [comment]
Will need a better backtrace than that to figure this one out. It might be related to the previous migrations we ran which broke, no?

**Comment by unho** [comment]
Closed by accident. Reopening this.

**Comment by jleclanche** [comment]
I think we fixed this a while back.

**Comment by dwaynebailey** [comment]
@jleclanche we didn't, got this email from @EmiXLabs

```
When my friend after registration and few suggestions tried to add
suggestion language to his profile (English-en) got this error.

Exception: (1062, "Duplicate entry '0-29' for key 'pootleprofile_id'")

If you need assistance, you may refer to this error as
8521a1004a714f29bd18874a3ec13743.
```

Suggestion language here would be alt-src language

**Comment by dwaynebailey** [comment]
The error occured on http://mozilla.locamotion.org/user/halil/settings/

```pytb
Traceback (most recent call last):
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/api/web_transaction.py", line 711, in __iter__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/api/web_transaction.py", line 1087, in __call__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/hooks/framework_django.py", line 499, in wrapper
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
  File "/var/www/sites/mozilla/src/pootle/core/views.py", line 68, in dispatch
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
  File "/var/www/sites/mozilla/src/pootle/core/views.py", line 45, in dispatch
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/hooks/framework_django.py", line 872, in wrapper
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 230, in post
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 173, in post
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 149, in form_valid
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/forms/models.py", line 455, in save
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/forms/models.py", line 104, in save_instance
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/forms/models.py", line 100, in save_m2m
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 2298, in save_form_data
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1193, in __set__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 924, in add
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1042, in _add_items
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 409, in bulk_create
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 938, in _batched_insert
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/hooks/database_dbapi2.py", line 22, in execute
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
```

**Comment by dwaynebailey** [comment]
Another instance [reported against LibreOffice](https://redmine.documentfoundation.org/issues/1406) which seems to confirm that this is when a user wants to add alt-src languages to their profile.

**Comment by arky** [comment]
Found this during the on-going Mozilla localization hackathon. The bug has been verified by Jeff Beatty and Saikeo (Lao team). 

Steps to reproduce the error. 

1. Go to user preferences. 
2. Add a new locale to 'Alternative Source Languages'
3. Hit save
