### ISSUE TITLE
Build and install 2.7dev from scratch

### ISSUE THREAD

**Issue by VladMironov** [translate/pootle#3862]
I've tried all ways to install developer version from scratch using [official](http://docs.translatehouse.org/projects/pootle/en/latest/server/installation.html) documentation still have no luck. With 2.5.1.3 I've got no problem at all.

1. System info:
    Mac Os X, virtualenv with Python 2.7 (is there no Python 3 support yet?)
2. Everything is ok up to this: 
   ```
   (env) $ pootle collectstatic --noinput
   (env) $ pootle assets build
   ```

   For obvious reasons I couldn't execute this two lines. I even tried to run this commands with preinstalled pootle (which looks like meaningless move because static files are different) but it failed, so this time I'm skipping this step for sometime.
3. This is ok:
   ```
   (env) $ pip install -e .
   (env) $ pootle init
   ```

4. This is somehow is ok too, solved by `(env) $ mkdir assets`
   ```
   (env) $ pootle collectstatic --noinput
   OSError: [Errno 2] No such file or directory: '/Users/littus/work/translation_house/pootle/pootle/pootle/assets'
   ```
   
5. But the main problem is here:
   ```
   (env) $ pootle assets build
   webassets.exceptions.BundleError: '/Users/littus/work/translation_house/pootle/pootle/pootle/assets/js/editor/app.bundle.js' does not exist
   ```

Is there some bulletproof method to install latest version?

**Comment by iafan** [comment]
Try doing the following:

```
$ pootle webpack
$ pootle collectstatic --noinput --clear -i node_modules -i *.jsx
$ pootle assets build
```

**Comment by VladMironov** [comment]
Yes that solved my problem thank you!
But now I have the new one:
```
(env)stone:pootle littus$ pootle migrate
(env)stone:pootle littus$ pootle createsuperuser
(env)stone:pootle littus$ pootle start
2015-06-24 23:30:13,409 INFO Loading custom settings from '/Users/littus/.pootle/pootle.conf'...
2015-06-24 20:30:13,909 INFO Using Python PO
System check identified some issues:

WARNINGS:
?: (pootle.W004) Can't find python-levenshtein package. Updating against templates is faster with python-levenshtein.
	HINT: Try pip install python-levenshtein
?: (pootle.W006) The sqlite database backend is unsupported
	HINT: Set your default database engine to postgresql_psycopg2 or mysql
?: (pootle.W010) DEFAULT_FROM_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: DEFAULT_FROM_EMAIL is used in all outgoing Pootle email.
Don't forget to review your mail server settings.
?: (pootle.W011) POOTLE_CONTACT_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: POOTLE_CONTACT_EMAIL is the address that will receive messages sent by the contact form.
System check identified some issues:

WARNINGS:
?: (pootle.W004) Can't find python-levenshtein package. Updating against templates is faster with python-levenshtein.
	HINT: Try pip install python-levenshtein
?: (pootle.W006) The sqlite database backend is unsupported
	HINT: Set your default database engine to postgresql_psycopg2 or mysql
?: (pootle.W010) DEFAULT_FROM_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: DEFAULT_FROM_EMAIL is used in all outgoing Pootle email.
Don't forget to review your mail server settings.
?: (pootle.W011) POOTLE_CONTACT_EMAIL is using the following default setting 'info@YOUR_DOMAIN.com'.
	HINT: POOTLE_CONTACT_EMAIL is the address that will receive messages sent by the contact form.
2015-06-24 20:30:14,129 INFO Starting CherryPy server, listening on port 8000
Traceback (most recent call last):
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/views.py", line 94, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/views.py", line 62, in dispatch
    **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/views.py", line 78, in post
    response = self.form_valid(form)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/views.py", line 102, in form_valid
    return form.login(self.request, redirect_url=success_url)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/forms.py", line 144, in login
    redirect_url=redirect_url)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/utils.py", line 130, in perform_login
    send_email_confirmation(request, user, signup=signup)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/utils.py", line 304, in send_email_confirmation
    confirm=True)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/managers.py", line 20, in add_email
    signup=signup)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/models.py", line 61, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/models.py", line 138, in send
    ctx)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/allauth/account/adapter.py", line 100, in send_mail
    msg.send()
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 92, in send_messages
    new_conn_created = self.open()
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 50, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused

```

This happens after login try.

**Comment by iafan** [comment]
Looks like you have SMTP-related stuff underconfigured, and Pootle fails to send you a registration email.

I don't know what your desired SMTP setup is, but you may want to look at https://docs.djangoproject.com/en/1.8/topics/email/ and http://stackoverflow.com/questions/19264907/python-django-gmail-smtp-setup to start some troubleshooting.

(I'm not a Python guy, so if this doesn't help, you may need for other Pootle folks to chime in and give you a more professional help)

**Comment by dwaynebailey** [comment]
@VladMironov yip @iafan is correct.  You don't have SMTP.  By default Pootle is looking for SMTP running on your server.  Look inside your .pootle/pootle.conf file and you can setup SMTP

**Comment by VladMironov** [comment]
I fixed that by changing verified flag at account_emailaddress table.
Now everything is working well but some directories are missed (e.g. /admin/projects/) is it okay?

**Comment by dwaynebailey** [comment]
@VladMironov that would work but your just working around the issue.  You want to change you email backend in this as.  Have a look in ``pootle/settings/90-dev-local.conf.sample`` that uses a console backend i.e. all emails just appear as text in the logs.

You might want to elaborate on what you mean by those directories being missing, because yes it is a problem.

**Comment by VladMironov** [comment]
Well yes, I understand the reasons of that behavior but may be it would be better if superusers shouldn't verify their emails?

Anyway for /admin/projects/ GET I got this:
```
2015-06-25 14:44:56,707 ERROR Internal Server Error: /admin/projects/
Traceback (most recent call last):
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/pootle/pootle/core/views.py", line 38, in dispatch
    .dispatch(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 154, in get
    context = self.get_context_data(**kwargs)
  File "/Users/littus/work/translation_house/pootle/pootle/pootle/apps/pootle_app/views/admin/projects.py", line 32, in get_context_data
    default_language = languages[0].id
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 160, in __getitem__
    return self._result_cache[k]
IndexError: list index out of range
```

Pootle tries to load languages and failed. But I couldn't create new language neither:
```
2015-06-25 14:56:11,009 ERROR Internal Server Error: /xhr/admin/languages/
Traceback (most recent call last):
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/pootle/pootle/core/views.py", line 38, in dispatch
    .dispatch(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/pootle/pootle/core/views.py", line 190, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/pootle/pootle/core/views.py", line 228, in post
    new_object = form.save()
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/forms/models.py", line 455, in save
    construct=False)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/forms/models.py", line 103, in save_instance
    instance.save()
  File "/Users/littus/work/translation_house/pootle/pootle/pootle/apps/pootle_language/models.py", line 140, in save
    self.directory = Directory.objects.root.get_or_make_subdir(self.code)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/utils/functional.py", line 55, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/Users/littus/work/translation_house/pootle/pootle/pootle/apps/pootle_app/models/directory.py", line 35, in root
    return self.get(pootle_path='/')
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/littus/work/translation_house/pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: Directory matching query does not exist.
```

Could it be SQLite fault? What does this warning:
```
?: (pootle.W006) The sqlite database backend is unsupported
	HINT: Set your default database engine to postgresql_psycopg2 or mysql
```
mean? Is it really-really unsupported? Should I change it?

Thank you for your help.

**Comment by unho** [comment]
I doubt that SQLite is the problem. This looks like there are missing data in the DB. Have you run `pootle initdb` ?

Anyway you should use instead MySQL (InnoDB) either for developing or deploying. Or PostgreSQL, but MySQL is more widely used.

I will use the opportunity to ask again to drop SQLite. I don't think allowing to quickly deploy and test Pootle using a less performant DB, a DB that we actively encourage not to use in production, should be supported in any way.

**Comment by VladMironov** [comment]
>Have you run `pootle initdb`?
Now I do and it works charmly indeed.
Thank you!
