### ISSUE TITLE
app.bundle.js' does not exist on make assets

### ISSUE THREAD

**Issue by Leo-g** [translate/pootle#3896]
```bash
 static files copied to '/home/leo/python-scripts/pootle-2-test/pootle/pootle/assets'.
python manage.py assets build 
2015-07-13 20:42:09,143 INFO Using Python PO
Building bundle: css/common.min.%(version)s.css
2015-07-13 20:42:09,191 INFO Building bundle: css/common.min.%(version)s.css
Building bundle: js/editor/app.min.%(version)s.js
2015-07-13 20:42:09,428 INFO Building bundle: js/editor/app.min.%(version)s.js
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line()
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/django_assets/management/commands/assets.py", line 91, in handle
    retval = impl.run_with_argv(args) or 0
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/script.py", line 549, in run_with_argv
    return self.run_with_ns(ns)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/script.py", line 539, in run_with_ns
    return cmd.invoke(ns.command, args)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/script.py", line 373, in invoke
    return function(**args)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/script.py", line 172, in __call__
    bundle.build(force=True, disable_cache=no_cache)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/bundle.py", line 660, in build
    disable_cache=disable_cache))
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/bundle.py", line 597, in _build
    force, disable_cache=disable_cache, extra_filters=extra_filters)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/bundle.py", line 454, in _merge_and_apply
    resolved_contents = self.resolve_contents(ctx, force=True)
  File "/home/leo/python-scripts/pootle-2-test/venv-2.7/local/lib/python2.7/site-packages/webassets/bundle.py", line 235, in resolve_contents
    raise BundleError(e)
webassets.exceptions.BundleError: '/home/leo/python-scripts/pootle-2-test/pootle/pootle/assets/js/editor/app.bundle.js' does not exist
make: *** [assets] Error 1
```

When I do a make assets

**Comment by julen** [comment]
Sorry which version are you trying to test and following which instructions?

**Comment by Leo-g** [comment]
I cloned the current git repo and followed the instructions as per http://pootle.readthedocs.org/en/latest/server/installation.html

**Comment by julen** [comment]
Those instructions are for installations via pip.

If you wanna run Pootle via a git clone, the [hacking docs](http://pootle.readthedocs.org/en/latest/developers/hacking.html#detailed-setup) are the closer to *installation instructions* you'll find. Don't forget to run [frontend-specific steps](http://pootle.readthedocs.org/en/latest/developers/frontend.html).

Closing the issue as invalid, however don't hesitate to ask any questions you might have.

**Comment by Leo-g** [comment]
Those docs specifically mention, Can you please remove the instructions

    Installationn from Github checkout
     An alternative to installing from a package is to install directly from Github. 
    This is useful if you are  developing Pootle or if you want to have a fine control when updating a server.

**Comment by julen** [comment]
Sorry missed that. Do you have node + npm installed and did you run the following?

```bash
(env) $ cd pootle/static/js
(env) $ npm install
(env) $ cd ../../..
(env) $ make assets
```

**Comment by Leo-g** [comment]
yes, I have node installed and ran the instructions as the per the doc

**Comment by julen** [comment]
If *app.bundle.js* does not exist the `manage.py webpack` step has failed. Can you check that? Also ensure your npm version is up-to-date (`[sudo] npm install npm@latest -g`).

**Comment by Leo-g** [comment]
I referred to your hacking docs and now I get 

 pip install -e .
Obtaining file:///sites/pootle-git/pootle
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/sites/pootle-git/pootle/setup.py", line 23, in <module>
        from pootle import __version__
      File "pootle/__init__.py", line 10, in <module>
        from pootle.core.utils.version import get_version
      File "pootle/core/utils/version.py", line 20, in <module>
        from django.utils.lru_cache import lru_cache
      File "/home/kb/envs/2.6/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
        fasttypes = {int, str, frozenset, type(None)},
                        ^
    SyntaxError: invalid syntax

**Comment by julen** [comment]
[Django 1.7 requires at least Python 2.7](https://docs.djangoproject.com/en/1.7/releases/1.7/#python-compatibility); Python 2.6 won't work.

**Comment by Leo-g** [comment]
Can you please mention that as a note in your docs?

Also I am not sure where I am suppose to mention the secret key

 python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    cmd_log(*sys.argv)
  File "/sites/pootle-git/pootle/pootle/core/log.py", line 60, in cmd_log
    fn = settings.LOGGING.get('handlers').get('log_action').get('filename')
  File "/home/kb/envs/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/kb/envs/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/kb/envs/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 115, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by julen** [comment]
I have pushed some improvements to installation docs via git (the step to build assets was clearly in the wrong place), also mentioning the necessary Python version. That should get you going (just checked on my side).

**Comment by julen** [comment]
Re. the secret key, `pootle init` will take care of setting up a that for you.

**Comment by Leo-g** [comment]
What about the Key error that I got?

**Comment by Leo-g** [comment]
ok let me check

**Comment by Leo-g** [comment]
pootle init
Configuration file created at '/home/kb/.pootle/pootle.conf'
(2.7)[k]$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    cmd_log(*sys.argv)
  File "/sites/pootle-git/pootle/pootle/core/log.py", line 60, in cmd_log
    fn = settings.LOGGING.get('handlers').get('log_action').get('filename')
  File "/home/kb/envs/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/kb/envs/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/kb/envs/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 115, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by julen** [comment]
Why do you use `pootle` on the one hand and `python manage.py` on the other hand? Please follow the installation instructions and use the `pootle` command as they suggest (and not `manage.py`), otherwise Pootle won't know where your settings are.

**Comment by Leo-g** [comment]
Thats what the installation instruction says, I ran pootle init since you told me and then I ran python manage.py migrate as per your docs,  at the moment I copied the conf file from pootle init to pootle settings and that solved it. But please update your docs as I am only following the instructions in them

    (env-name) $ python manage.py migrate
    (env-name) $ python manage.py initdb

**Comment by julen** [comment]
The docs are fine now, you have mixed [instructions from installation](http://docs.translatehouse.org/projects/pootle/en/latest/server/installation.html#installing-pootle) with [hacking docs](http://docs.translatehouse.org/projects/pootle/en/latest/developers/hacking.html). The former use `pootle`, the latter `manage.py`.

Considering this is solved, so closing the issue.

**Comment by Leo-g** [comment]
No I did not mix up, I did exactly wat you said to resolve an error thrown when I followed the steps in the hacking docs The problem is that before (env-name) $ python manage.py migrate, there needs to be a step which will inform you how to generate the Secret Key, This needs to be via manage.py preferably I am not sure how, but it would be nice if you can include the command.

**Comment by julen** [comment]
Just added a dummy secret key for dev purposes in 0a377128c1db0 — no need to add extra steps in the docs.

**Comment by Leo-g** [comment]
Thanks
