### ISSUE TITLE
2.5.1.3 DatabaseError: no such table: pootlecache

### ISSUE THREAD

**Issue by aRkadeFR** [translate/pootle#3907]
Hey,
On a fresh install of the 2.5.1.3 (cause 2.6 not finished and 2.7 on dev plus 2.5.1.2 not available) from pypi, I'm facing this stacktrace after init/syncdb/migrate/start:

```
Traceback (most recent call last):
  File "/root/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_response
    response = middleware_method(request)
  File "/root/.virtualenvs/pootle/local/lib/python2.7/site-packages/pootle/middleware/baseurl.py", line 50, in process_request
    siteconfig = load_site_config()
  File "/root/.virtualenvs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_misc/siteconfig.py", line 46, in load_site_config
    siteconfig.save()
  File "/root/.virtualenvs/pootle/local/lib/python2.7/site-packages/pootle/apps/djblets/siteconfig/models.py", line 113, in save
    cache.set(self.__get_sync_cache_key(), now)
  File "/root/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/cache/backends/db.py", line 80, in set
    self._base_set('set', key, value, timeout)
  File "/root/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/core/cache/backends/db.py", line 94, in _base_set
    cursor.execute("SELECT COUNT(*) FROM %s" % table)
  File "/root/.virtualenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: pootlecache
```

**Comment by aRkadeFR** [comment]
my bad, didn't run the initdb

:)
