### ISSUE TITLE
Update from 2.5.1 to 2.6.0 fails: no migrations for taggit module

### ISSUE THREAD

**Issue by jeff1985** [translate/pootle#3960]
I'm upgrading pootle from ``2.5.1``. According to the [docs](http://pootle.readthedocs.org/en/stable-2.7.0/server/upgrading.html) it is recommeded to upgrade to 2.6.0 first:

    (env) $ pip install --upgrade "Pootle>=2.6,<2.7"
    [..]
    Successfully installed Pootle Django django-allauth django-assets django-contact-form django-taggit South argparse cssmin diff-match-patch lxml translate-toolkit python-openid requests-oauthlib requests webassets six oauthlib

the next step fails:

    (env) $ pootle setup
    2015-08-11 12:52:05,703 INFO Loading custom settings from '/root/.pootle/pootle.conf'...
    2015-08-11 10:52:05,828 INFO Using Python PO
    2015-08-11 10:52:05,977 INFO Upgrading existing Pootle installation.
    Syncing...
    Creating tables ...
    Creating table account_emailaddress
    Creating table account_emailconfirmation
    Installing custom SQL ...
    Installing indexes ...
    Installed 0 object(s) from 0 fixture(s)

    Synced:
     > django.contrib.sessions
     > django.contrib.auth
     > django.contrib.contenttypes
     > django.contrib.sites
     > django.contrib.admin
     > django.contrib.messages
     > django.contrib.staticfiles
     > allauth
     > allauth.account
     > djblets.siteconfig
     > django_assets
     > taggit
     > south

    Not synced (use migrations):
     - accounts
     - pootle_app
     - pootle_store
     - pootle_language
     - pootle_project
     - pootle_translationproject
     - pootle_statistics
     - pootle_tagging
     - pootle_notifications
     - staticpages
     - allauth.socialaccount
    (use ./manage.py migrate to migrate these)
    Traceback (most recent call last):
      File "/usr/local/bin/pootle", line 9, in <module>
        load_entry_point('Pootle==2.6.0-rc2', 'console_scripts', 'pootle')()
      File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 171, in main
        django_settings_module='pootle.settings')
      File "/usr/local/lib/python2.7/dist-packages/pootle/runner.py", line 150, in run_app
        management.execute_from_command_line([runner_name] + remainder)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in     execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
        return self.handle_noargs(**options)
      File "/usr/local/lib/python2.7/dist-    packages/pootle/apps/pootle_app/management/commands/setup.py", line 87, in handle_noargs
        call_command('migrate')
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 159, in     call_command
        return klass.execute(*args, **defaults)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 111, in     handle
        ignore_ghosts = ignore_ghosts,
      File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 200, in migrate_app
        applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
      File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 81, in     check_migration_histories
        m = h.get_migration()
      File "/usr/local/lib/python2.7/dist-packages/south/models.py", line 34, in get_migration
        return self.get_migrations().migration(self.migration)
      File "/usr/local/lib/python2.7/dist-packages/south/models.py", line 31, in get_migrations
        return Migrations(self.app_name)
      File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 64, in __call__
        self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
      File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 90, in __init__
        self.set_application(application, force_creation, verbose_creation)
      File "/usr/local/lib/python2.7/dist-packages/south/migration/base.py", line 170, in set_application
        raise exceptions.NoMigrations(application)
    south.exceptions.NoMigrations: Application '<module 'taggit' from '/usr/local/lib/python2.7/dist-    packages/taggit/__init__.pyc'>' has no migrations.

Is there a way to fix this taggit problem?

**Comment by dwaynebailey** [comment]
Mmmm taggit looks like it shouldn't be migrated by South, yet South is trying to migrate it.  Could you post the version of taggit that you have installed.

**Comment by julen** [comment]
That sounds like stale *.pyc* files.

**Comment by jeff1985** [comment]
@dwaynebailey 
My initial setup was:

    (env)root@pootle:/home/jeff# pip freeze
    Django==1.4.10
    MySQL-python==1.2.5
    Pootle==2.5.1-rc1
    South==0.7.6
    argparse==1.2.1
    cssmin==0.2.0
    distribute==0.6.24
    django-assets==0.8
    django-taggit==0.12
    django-voting==0.1
    lxml==3.3.5
    translate-toolkit==1.11.0-rc1
    webassets==0.8
    wsgiref==0.1.2

@julen 
I'm not familiar with python environments. However i tried running
 ``find -iname "*.pyc" -exec rm -f {} \;``
as recommended [here](http://stackoverflow.com/questions/27630730/best-way-to-avoid-stale-pyc-files) but the error message ist still the same.

**Comment by julen** [comment]
@jeff1985 not sure from where you did it, but make sure to run it against the directory where Pootle sources are located.

**Comment by phlax** [comment]
@jeff1985 im figuring this has been fixed.

If the problem persists please re-open the ticket and we can investigate further
