### ISSUE TITLE
Virtualfolder failure in the case of update_stores for a new language

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#3962]
On mlo I've initialised a language.  Then uploaded the language with `update_stores` as we can't initialise on Pootle now from the UI.  A few Redis jobs failed with this traceback:

```pytb
Traceback (most recent call last):
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/rq/worker.py", line 558, in perform_job
    rv = job.perform()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/var/www/sites/mozilla/src/pootle/core/mixins/treeitem.py", line 674, in update_cache_job
    instance._update_cache_job(keys, decrement)
  File "/var/www/sites/mozilla/src/pootle/core/mixins/treeitem.py", line 524, in _update_cache_job
    for p in self.get_parents():
  File "/var/www/sites/mozilla/src/pootle/apps/virtualfolder/models.py", line 400, in get_parents
    if self.parent:
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 572, in __get__
    rel_obj = qs.get()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: VirtualFolderTreeItem matching query does not exist.
```

**Comment by phlax** [comment]
@dwaynebailey - this was fixed by django-transaction-hooks

**Comment by unho** [comment]
I would be really happy if that is actually true. How can we test if it is true? Detailed list of steps to reproduce, please.

**Comment by phlax** [comment]
To ascertain that it is fixed i:

- hard reset branch to commit prior to transaction-hooks
- add language to project ttw
- saw errors
- rebased to master
- add language to project ttw
- no errors

i then repeated above a couple of times to confirm

**Comment by phlax** [comment]
...well i read the stack trace first which is what led me to test that

**Comment by unho** [comment]
Would like to hear from @dwaynebailey as well.

**Comment by phlax** [comment]
@unho and i have tried again to reproduce this on staging.

Although we didnt repro the exact bug we reproed a very similar one - and satisfied ourselves that transaction_hooks at least fixed that.

Im pretty confident this is sorted - lmk @dwaynebailey if it happens again
