### ISSUE TITLE
DistributionNotFound errors on clean 2.7 install

### ISSUE THREAD

**Issue by jleclanche** [translate/pootle#3980]
This might be a non-issue since there were libxml compilation errors during the install, but it's worth looking into. (This is after a clean `pip install pootle`)

```pytb
(pootle.env)[13:48:54] pootle@helix ~ % pootle
Traceback (most recent call last):
  File "/var/www/pootle/pootle.env/bin/pootle", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: urllib3>=1.8,<2.0
(pootle.env)[13:49:27] pootle@helix ~ % pip install urllib3
Downloading/unpacking urllib3
  Downloading urllib3-1.11-py2.py3-none-any.whl (84kB): 84kB downloaded
Installing collected packages: urllib3
Successfully installed urllib3
Cleaning up...
(pootle.env)[13:49:29] pootle@helix ~ % pootle             
Traceback (most recent call last):
  File "/var/www/pootle/pootle.env/bin/pootle", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/www/pootle/pootle.env/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: sphinx-me>=0.1.2
(pootle.env)[13:49:32] pootle@helix ~ % pip install sphinx-me
Downloading/unpacking sphinx-me
  Downloading sphinx_me-0.3-py2.py3-none-any.whl
Installing collected packages: sphinx-me
Successfully installed sphinx-me
Cleaning up...
(pootle.env)[13:49:40] pootle@helix ~ % pootle               
Configuration file does not exist at '/var/www/pootle/.pootle/pootle.conf' or 'POOTLE_SETTINGS' environment variable has not been set.
Use 'pootle init' to initialize the configuration file.
```

**Comment by julen** [comment]
Thank you for the report Jerome.

This is behavior caused by a broken pip install as you say, and is a non-issue after all: `urllib3` is a dep from `elasticsearch-py`, `sphinx-me` another dep from `django-overextends`; their installation wasn't completed as `lxml` broke. I can reproduce similar errors if I manually interrupt the install operation while `lxml` is being compiled.

I double-checked with a clean install on a fresh virtualenv that everything works correctly.

**Comment by jleclanche** [comment]
Ok. I'm currently migrating an instance so I'm hitting a few warts we didn't catch on 2.7 release.

**Comment by mweimerskirch** [comment]
Had the same error message. Installation was interrupted because "zlib1g-dev" was missing. I installed it using "apt-get install zlib1g-dev" and afterwards hat to do "pip install --upgrade --force-reinstall pootle" to get rid of the error.
