### ISSUE TITLE
Virtualfolder failure in the case of update_stores for a new language

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4044]
The following are traceback on RQ jobs when you have the following situation:

1. Project has virtual folders
2. You `update_stores` on a newly established TP

```pytb
Traceback (most recent call last):
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/rq/worker.py", line 558, in perform_job
    rv = job.perform()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/var/www/sites/mozilla/src/pootle/core/mixins/treeitem.py", line 674, in update_cache_job
    instance._update_cache_job(keys, decrement)
  File "/var/www/sites/mozilla/src/pootle/core/mixins/treeitem.py", line 524, in _update_cache_job
    for p in self.get_parents():
  File "/var/www/sites/mozilla/src/pootle/apps/virtualfolder/models.py", line 400, in get_parents
    if self.parent:
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 572, in __get__
    rel_obj = qs.get()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: VirtualFolderTreeItem matching query does not exist.
```

This creates a number of failed jobs.  Running `retry_failed_jobs` later sorts all the issues out.  So somehow these jobs are being triggered before the virtualfolder is ready.

**Comment by unho** [comment]
This is #3962 which we tested yesterday and couldn't replicate so was considered to be fixed.

Can you please provide a more detailed list of the steps you followed? Or is that all the steps?

**Comment by dwaynebailey** [comment]
Tested this on latest master and this issue does not exist there.  I made sure that Pootle had language ``bum`` defined.  Then added files for ``firefox/bum`` which was just a ``cp -rp af bum``.  Then ran ``update_stores --project=firefox --language=bum``.  No failed jobs appeared so the issue is fixed.
