### ISSUE TITLE
RQ fails jobs

### ISSUE THREAD

**Issue by JohnnyKing94** [translate/pootle#4050]
RQ keeps failing the refresh stats job when it connects to mysql.

Thank you in advance
```pytb
Traceback (most recent call last):
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 459, in refresh_stats
    super(Command, Command()).handle_noargs(**options)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 97, in handle_noargs
    self.handle_all(**options)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 130, in handle_all
    super(Command, self).handle_all(**options)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 112, in handle_all
    for project in project_query.iterator():
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/desktop/Pubblici/Envs/pootle/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')
[2015-09-09T21:01:41]   Moving job to u'failed' queue
[2015-09-09T21:01:41]
[2015-09-09T21:01:41]   *** Listening on default...
```

**Comment by dwaynebailey** [comment]
Looks like your MySQL server isn't happy.  The failed jobs can be put back into the ``default`` queue using [``pootle retry_failed_jobs``](http://docs.translatehouse.org/projects/pootle/en/stable-2.7.0/server/commands.html?highlight=retry_failed_jobs#django-admin-retry_failed_jobs)

**Comment by JohnnyKing94** [comment]
I tried, i have 6 jobs failed so far... there's surely a problem... why you close the issue if i don't reply first :|

**Comment by perseusl** [comment]
I'm also having this problem. Please reopen this

**Comment by julen** [comment]
The timeout issue is being handled in #4094.

**Comment by JohnnyKing94** [comment]
Update pootle to 2.7.1 and you've done... ;) as I did

**Comment by perseusl** [comment]
I'm already usigng 2.7.1 before this error occured but restarting my rqworker fixed my problem

**Comment by JohnnyKing94** [comment]
Weird, i don't know i'm using a Ubuntu Distribution ver. 12.04 LTS with python 2.7.3 and mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.2... and i don't have any more errors with it
