### ISSUE TITLE
2.5.0 -> 2.6.0 -> 2.7.0 postgres migration problems

### ISSUE THREAD

**Issue by romangoward** [translate/pootle#4068]
Hi guys, I am trying to update pootle from 2.5.0 to 2.7.0, but I've have errors wih PostgeSQL migration.

* 2.5.0 -> 2.5.1.3 => an upgrade works fine;
* 2.5.1.3 -> 2.6.0 => an upgrade fails at migrations stage (pootle setup)

Pootle 2.6.0 (Django 1.6.11, Translate Toolkit 1.13.0)

1. fix #3814 helps with duplicates, thanks!
2. django.db.utils.InternalError: could not find trigger 21504 -> syncdb works, migrate fails;

For the second issue I tried to do migration with a fresh pootle installation, thus I believe you can reproduce the issue easily. I also have the same problem with a production database.

**Stacktrace** 

```pytb
$ pootle setup
2015-09-15 03:23:08,569 INFO Loading custom settings from '/home/goward/.pootle/pootle.conf'...
2015-09-15 00:23:08,731 INFO Using Python PO
2015-09-15 00:23:08,842 INFO Upgrading existing Pootle installation.
Syncing...
Creating tables ...
Creating table account_emailaddress
Creating table account_emailconfirmation
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.sessions
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sites
 > django.contrib.admin
 > django.contrib.messages
 > django.contrib.staticfiles
 > allauth
 > allauth.account
 > djblets.siteconfig
 > django_assets
 > south

Not synced (use migrations):
 - accounts
 - pootle_app
 - pootle_store
 - pootle_language
 - pootle_project
 - pootle_translationproject
 - pootle_statistics
 - pootle_tagging
 - pootle_notifications
 - reports
 - staticpages
 - virtualfolder
 - allauth.socialaccount
(use ./manage.py migrate to migrate these)
Running migrations for accounts:
 - Migrating forwards to 0009_drop_registration_remnant.
 > pootle_translationproject:0003_add_m2ms
 > pootle_translationproject:0004_auto__add_field_translationproject_total_wordcount__add_field_translat
 > pootle_project:0003_add_m2ms
 > pootle_project:0004_auto__del_field_project_report_target
 > pootle_project:0005_auto__add_field_project_report_email
 > pootle_project:0006_auto__add_field_project_disabled
 > pootle_translationproject:0005_auto__add_field_translationproject_disabled
 > pootle_translationproject:0006_auto__add_field_translationproject_failing_critical_count
 > accounts:0001_initial
 > pootle_app:0002_add_m2ms
 > pootle_store:0002_auto__add_tmunit
 > pootle_store:0003_add_m2ms
 > pootle_store:0004_auto__add_field_unit_creation_time
 > pootle_store:0005_auto__del_field_store_tm__del_field_store_pending
 > pootle_store:0006_auto__add_field_store_total_wordcount__add_field_store_translated_word
 > pootle_store:0007_auto__add_field_store_failing_critical_count
 > pootle_store:0008_auto__add_field_suggestion_reviewer__add_field_suggestion_translation_
 > pootle_statistics:0002_auto__add_field_submission_check
 > pootle_statistics:0003_auto__add_field_submission_suggestion
 > pootle_store:0009_move_data_from_pootle_app_suggestion
2015-09-15 00:23:10,754 INFO {'PAS_LESS_THAN_PSS': 0, 'NO_PSS_FOR_PENDING_PAS': 0, 'NO_SUB_FOR_PAS': 0, 'DEL_REJECTED_PAS': 0, 'ONE_TO_ONE_COPY': 0, 'NO_PAS_FOR_PSS': 0, 'SUG_CREATED_FROM_SUB': 0, 'NO_UNIT_FOR_PAS': 0, 'MANY_TO_MANY_COPY': 0, 'PSS_LESS_THAN_PAS': 0, 'DUPLICATED_SUG': 0}
 > pootle_statistics:0004_auto__del_field_submission_from_suggestion
 > pootle_app:0003_auto__add_pootleconfig
 > pootle_app:0004_auto__add_pootlesite
 > pootle_app:0005_auto__add_field_permissionset_user
Migrating PermissionSet Profile data to User. This may take a while.
 > accounts:0002_import_profile_data
Importing old profile data
Importing alt_src_langs data. If you have a lot of users, this can take a while.
Renaming u'pootle_app_pootleprofile_alt_src_langs' to u'accounts_user_alt_src_langs'
 > pootle_app:0006_auto__del_suggestion
 > accounts:0003_auto__inherit_from_permissionsmixin
Renaming u'auth_user_groups' to u'accounts_user_groups'
Renaming u'auth_user_user_permissions' to u'accounts_user_user_permissions'
 > pootle_app:0007_del_suggestion_ctype
 > pootle_app:0008_drop_votes_table
Error during commit in migration: pootle_app:0008_drop_votes_table
Traceback (most recent call last):
  File "/tank/Development/virtenvs/pootle/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.6.0', 'console_scripts', 'pootle')()
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 171, in main
    django_settings_module='pootle.settings')
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 150, in run_app
    management.execute_from_command_line([runner_name] + remainder)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/setup.py", line 77, in handle_noargs
    call_command('migrate', interactive=False)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/migration/migrators.py", line 98, in run_migration
    south.db.db.commit_transaction()
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/south/db/generic.py", line 989, in commit_transaction
    transaction.commit(using=self.db_alias)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/db/transaction.py", line 139, in commit
    get_connection(using).commit()
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 171, in commit
    self._commit()
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/tank/Development/virtenvs/pootle/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 139, in _commit
    return self.connection.commit()
django.db.utils.InternalError: could not find trigger 21504
```

**Comment by romangoward** [comment]
Not sure why django's InternalErros such uninformative, but I reviwed the migrations code and just droped these tables by hands:
* votes
* pootle_tagging_goal
* pootle_tagging_itemwithgoal
* taggit_taggeditem
* taggit_tag

All tables were empty.
Servers works fine.
