### ISSUE TITLE
update_stores without --language produces traceback

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4100]
If using ``update_stores`` without a ``--language`` filter then I get this traceback

```pytb
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 1406, in __str__
    store = self.convert(storeclass)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 2155, in convert
    for unit in self.units.iterator():
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 1375, in units
    self.require_units()
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 1478, in require_units
    self.parse()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 1543, in parse
    self.save()
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 1413, in save
    super(Store, self).save(*args, **kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 386, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
Logged from file project_tree.py, line 174

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/__init__.py", line 103, in handle_noargs
    self.handle_all(**options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/update_stores.py", line 54, in handle_all
    projects=self.projects)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_translationproject/models.py", line 90, in scan_translation_projects
    create_or_resurrect_translation_project(language, project)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_translationproject/models.py", line 47, in create_or_resurrect_translation_project
    tp = create_translation_project(language, project)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_translationproject/models.py", line 62, in create_translation_project
    .get_or_create(language=language, project=project)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 424, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 457, in _create_object_from_params
    obj.save(force_insert=True, using=self.db)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_translationproject/models.py", line 286, in save
    self.scan_files()
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_translationproject/models.py", line 420, in scan_files
    file_filter,
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/project_tree.py", line 248, in add_files
    db_subdir, file_filter)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/project_tree.py", line 248, in add_files
    db_subdir, file_filter)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/project_tree.py", line 233, in add_files
    db_dir,
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/project_tree.py", line 168, in add_items
    item = create_or_resurrect_db_item(name)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/project_tree.py", line 231, in <lambda>
    translation_project=translation_project,
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/project_tree.py", line 182, in create_or_resurrect_store
    store = Store.objects.get(parent=parent, name=name)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 59, in execute
    self.db.validate_no_broken_transaction()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 386, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by phlax** [comment]
@dwaynebailey i have never seen this issue and as update_stores has been significantly re-written and tested - can we close this?

**Comment by ta2-1** [comment]
I'd close this issue since we got rid of `require_units()` already.
I guess that there were unparsed languages and  using of `require_units()` led us to parsing and error.
