### ISSUE TITLE
Read configuration error

### ISSUE THREAD

**Issue by akarienta** [translate/pootle#4103]
I have these lines in my `pootle.conf` file:

``` python
AMAGAMA_URL = ''
POOTLE_TM_SERVER = 'http://localhost:9200/translations'
```

If I understand [this doc](http://pootle.readthedocs.org/en/stable/features/translation_memory.html) page correctly, `AMAGAMA_URL = ''` is needed to turn off the official amaGama TM server (`https://amagama-live.translatehouse.org/api/v1/`). 

The second one isn't needed if my elasticsearch server runs with default settings on `http://localhost:9200/translations`. If doesn't, I can setup it by `POOTLE_TM_SERVER` option (so in fact I don't need it actually on DEV server but I'll need it on PROD server).

However with this setup I have this error when I try to run Pootle (or update TM server):

``` bash
$ pootle update_tmserver
2015-09-25 08:55:11,727 INFO Loading custom settings from '/home/pootle/.pootle/pootle.conf'...
2015-09-25 08:55:12,118 INFO Using Python PO
Traceback (most recent call last):
  File "/home/pootle/.envs/pootle/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.7.2', 'console_scripts', 'pootle')()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 309, in main
    django_settings_module='pootle.settings')
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 289, in run_app
    management.execute_from_command_line(command)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/apps/accounts/models.py", line 38, in <module>
    from pootle_store.models import SuggestionStates, Unit
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 215, in <module>
    TMServer = SearchBroker()
  File "/home/pootle/.envs/pootle/local/lib/python2.7/site-packages/pootle/core/search/broker.py", line 27, in __init__
    _module = '.'.join(self._settings[server]['ENGINE'].split('.')[:-1])
TypeError: string indices must be integers, not str
```

When I remove option `POOTLE_TM_SERVER` the error isn't presented:

``` python
AMAGAMA_URL = ''
# POOTLE_TM_SERVER = 'http://localhost:9200/translations'
```

Do I something wrong or is it a bug?

**Comment by julen** [comment]
It's not a bug, but the docs are incorrect. The format of the `POOTLE_TM_SERVER` settings is the following (from *60-translation.conf*):
```python
POOTLE_TM_SERVER = {
    'default': {
        'ENGINE': 'pootle.core.search.backends.ElasticSearchBackend',
        'HOST': 'localhost',
        'PORT': 9200,
        'INDEX_NAME': 'translations',
        # For valid values for MIN_SCORE see
        # http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/common-options.html#fuzziness
        'MIN_SCORE': 'AUTO',
    },
}
```

**Comment by akarienta** [comment]
@julen Thanks, this issue can be closed then.

**Comment by julen** [comment]
No worries, let's keep it open until the docs are fixed.
