### ISSUE TITLE
Running 'export' without any options causes this error

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4137]
I suspect we always need to supply an option for this command.  Or at least default should work.

```pytb
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/Users/dwayne/dev/pootle/pootle/apps/pootle_app/management/commands/__init__.py", line 119, in handle_noargs
    self.handle_all(**options)
  File "/Users/dwayne/dev/pootle/pootle/apps/import_export/management/commands/export.py", line 73, in handle_all
    self.do_translation_project(tp, self.path, **options)
AttributeError: 'Command' object has no attribute 'path'
```

**Comment by julen** [comment]
`.do_translation_project()` doesn't receive any `path` arguments since 34080da2, which predates the actual `export` code. This code never worked.
