### ISSUE TITLE
2.5->2.6 update: OverflowError: date value out of range

### ISSUE THREAD

**Issue by dreasvandonselaar** [translate/pootle#4150]
Trying to upgrade Pootle 2.5 to 2.6 (as intermediary step to 2.7) fails when running "pootle setup":

```pytb
> pootle_store:0019_auto__del_field_store_sync_time__add_field_store_file_mtime
Traceback (most recent call last):
  File "/var/www/pootle/env/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.6.2', 'console_scripts', 'pootle')()
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/runner.py", line 171, in main
    django_settings_module='pootle.settings')
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/runner.py", line 150, in run_app
    management.execute_from_command_line([runner_name] + remainder)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/setup.py", line 77, in handle_noargs
    call_command('migrate', interactive=False)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 113, in run
    dry_run.run_migration(migration, database)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 192, in run_migration
    self._run_migration(migration)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0019_auto__del_field_store_sync_time__add_field_store_file_mtime'! Aborting.
Traceback (most recent call last):
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/migrations/0019_auto__del_field_store_sync_time__add_field_store_file_mtime.py", line 17, in forwards
    keep_default=False)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/db/generic.py", line 411, in add_column
    sql = self.column_sql(table_name, name, field)
  File "/var/www/pootle/env/lib/python2.7/site-packages/south/db/generic.py", line 706, in column_sql
    default = field.get_db_prep_save(default, connection=self._get_connection())
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 350, in get_db_prep_save
    prepared=False)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 912, in get_db_prep_value
    return connection.ops.value_to_db_datetime(value)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 347, in value_to_db_datetime
    value = value.astimezone(timezone.utc).replace(tzinfo=None)
OverflowError: date value out of range
```

**Comment by dreasvandonselaar** [comment]
I replaced line 17 ine "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/migrations/0019_auto__del_field_store_sync_time__add_field_store_file_mtime.py" to be: 
```
self.gf('django.db.models.fields.DateTimeField')(blank=True),
```

**Comment by phlax** [comment]
@dreasvandonselaar thanks for this we'll create a new release to address this issue

**Comment by unho** [comment]
This seems to create problems on 2.7.x as the migrations provide a schema that doesn't align with 2.7.x one.

**Comment by phlax** [comment]
@unho i reckon we can set date to datetime_min from pootle.core.utils.timezone

**Comment by unho** [comment]
Closing this since no one else reported it, and the proposed workaround actually introduces some other problems.

**Comment by keppler** [comment]
Sorry for re-opening after that long time - however this might be helpful to others. (googl'ing for the error message gives exactly ONE result -> this issue :-)
I've had exactly that same error message (date value out of range) after first upgrading Debian 7 (Wheezy) to 8 (Jessie) and then upgrading Pootle from 2.5.x to 2.6.x.
Having read the warning above, I've replaced the "year" component of `datetime.datetime()` call (`1`) with `1970` to get a valid date:

    self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(1970, 1, 1, 0, 0)),

After that, the upgrade continued without errors, and the next upgrade to 2.8.2 worked without any problems.
