### ISSUE TITLE
Running initdb twice causes a traceback

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4220]
If you somehow manage to run ``initdb`` twice you will get the following error.  I'm not sure if it is possible to detect that initdb has already been run and bail out.

```pytb
(python2.7) $> pootle initdb
2015-11-25 01:02:41,471 INFO Loading custom settings from '/home/arashm/.pootle/pootle.conf'...
2015-11-24 21:32:41,699 INFO Using Python PO
Populating the database.
Traceback (most recent call last):
  File "/home/arashm/.pyenvs/python2.7/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.7.3.dev20151124100802', 'console_scripts', 'pootle')()
  File "/home/arashm/workspace/Mozilla/pootle/pootle/runner.py", line 319, in main
    django_settings_module='pootle.settings')
  File "/home/arashm/workspace/Mozilla/pootle/pootle/runner.py", line 299, in run_app
    management.execute_from_command_line(command)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/home/arashm/workspace/Mozilla/pootle/pootle/apps/pootle_app/management/commands/initdb.py", line 25, in handle_noargs
    initdb()
  File "/home/arashm/workspace/Mozilla/pootle/pootle/core/initdb.py", line 35, in initdb
    create_default_projects()
  File "/home/arashm/workspace/Mozilla/pootle/pootle/core/initdb.py", line 255, in create_default_projects
    tutorial.save()
  File "/home/arashm/workspace/Mozilla/pootle/pootle/apps/pootle_project/models.py", line 368, in save
    super(Project, self).save(*args, **kwargs)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/arashm/.pyenvs/python2.7/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: pootle_app_project.directory_id
```

**Comment by unho** [comment]
`initdb` adds some default data https://github.com/translate/pootle/blob/master/pootle/core/initdb.py#L28-L36 part of which didn't change in eons. So perhaps it is safe to check if `en` language is present on DB:

```python
from pootle_language.models import Language


initdb_already_run = True

try:
    Language.objects.get(code='en')
except Exception:
    initdb_already_run = False

if initdb_already_run:
    self.stdout.write('This command has already being run.')
else:
    self.stdout.write('Populating the database.')
    initdb()
    self.stdout.write('Successfully populated the database.')
    self.stdout.write("To create an admin user, use the `pootle "
                      "createsuperuser` command.")
```
