### ISSUE TITLE
Running Pootle with runserver doesn't serve static assets

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4406]
Looks like the documentation in master since removal of ``pootle start`` doesn't correctly allow for a test/dev setup to serve static pages.

We need to run through and adjust the documentation so that running Pootle using ``runserver`` can serve static pages.  [The runserver docs point to how this can be done](https://docs.djangoproject.com/en/1.8/ref/django-admin/#serving-static-files-with-the-development-server).

**Comment by unho** [comment]
Dwayne suggested to use `--nostart`.

**Comment by julen** [comment]
@dwaynebailey is this about static _pages_ or static _assets_? I'd be puzzled to hear it's about the former.

**Comment by unho** [comment]
It is about static assets. This is the issue for https://github.com/translate/pootle/pull/4403#issuecomment-173145026

**Comment by julen** [comment]
Thanks for confirming, @unho.

From my understanding `--nostatic` does the opposite of serving static content ([you can check the code](https://github.com/django/django/blob/stable/1.8.x/django/contrib/staticfiles/management/commands/runserver.py)). I guess you meant `--insecure`.

Also realize [passing `--insecure`](https://github.com/django/django/blob/stable/1.8.x/django/contrib/staticfiles/management/commands/runserver.py#L28) is the same as what the `start` command did [via `BaseRunCommand`](https://github.com/translate/pootle/blob/be117771a01d48739681c1526365f15a556aba9d%5E/pootle/apps/pootle_app/management/commands/__init__.py#L183).

**Comment by unho** [comment]
It doesn't matter whether I use `runserver`, `runserver --nostatic` or `runserver --insecure`. All of them fail with the same traceback multiple times:

```pytb
Traceback (most recent call last):
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/leo/Escritorio/proba/pootle/pootle/apps/pootle_app/views/index/index.py", line 27, in view
    return render(request, 'welcome.html', ctx)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/django_assets/templatetags/assets.py", line 87, in render
    for url in bundle.urls():
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/webassets/bundle.py", line 787, in urls
    urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/webassets/bundle.py", line 747, in _urls
    return [self._make_output_url(ctx)]
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/webassets/bundle.py", line 704, in _make_output_url
    version = self.get_version(ctx, refresh=ctx.auto_build)
  File "/home/leo/.virtualenvs/probaborrar/local/lib/python2.7/site-packages/webassets/bundle.py", line 315, in get_version
    'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7f0f6957c4d0>], contents=('css/style.css', 'css/actions.css', 'css/breadcrumbs.css', 'css/buttons.css', 'css/contact.css', 'css/error.css', 'css/auth.css', 'css/magnific-popup.css', 'css/navbar.css', 'css/odometer.css', 'css/popup.css', 'css/react-select.css', 'css/tipsy.css', 'css/sprite.css', 'css/select2.css', 'css/select2-pootle.css', 'css/scores.css', 'css/user.css', 'css/welcome.css')>. There is no manifest which knows the version, and it cannot be determined dynamically, because: output target has a placeholder
```

**Comment by unho** [comment]
For test deployments it is necessary to use `--insecure`, so updating installation and releasing instructions.

In development environments it would be expected for developers to follow the http://docs.translatehouse.org/projects/pootle/en/latest/developers/hacking.html instructions, specifically the paragraph that says "Now ensure that you have built the assets by following the instructions for frontend development" which combined with `DEBUG = True` allows to serve static assets using just `runserver`.

**Comment by tcitworld** [comment]
Please help me understand how I'm suppose to launch the server, since I always fall back on the
```Cannot find version of <Bundle output=css/common.min.%(version)s.css, filters=[<webassets.filter.cssmin.CSSMin object at 0x7f7844396050>]```
error

**Comment by dwaynebailey** [comment]
@tcitworld looks like you haven't built assets.  Use `make assets` but if you're testing just add this to your config:

```python
DEBUG=True
ASSETS_DEBUG=True
ASSETS_AUTO_BUILD=True
```

And run `pootle webpack --dev`

The configs are in `pootle/settings/90-dev-local.conf.sample`

You might want to ask such questions on https://gitter.im/translate/pootle in future
