### ISSUE TITLE
IntegrityError: (1062, "Duplicate entry 'xxx' for key 'store_id'")

### ISSUE THREAD

**Issue by julen** [translate/pootle#4594]
I'm performing some tests locally and I populated a TP with a new file via `update_stores`:
```bash
$ ./manage.py update_stores --language=ab --project=foo
```
Now after making some changes online, I want to overwrite the changes with the copy from disk:
```
$ ./manage.py update_stores --language=ab --project=foo --overwrite --force
```
Which triggers:
```python
Traceback (most recent call last):
  File "~/pootle/apps/pootle_app/management/commands/__init__.py", line 78, in do_translation_project
    process_stores = self.handle_translation_project(tp, **options)
  File "~/pootle/apps/pootle_app/management/commands/update_stores.py", line 48, in handle_translation_project
    force=options['force'], overwrite=options['overwrite'])
  File "~/pootle/apps/pootle_translationproject/models.py", line 353, in update_from_disk
    changed = store.update_from_disk(overwrite=overwrite) or changed
  File "~/pootle/apps/pootle_store/models.py", line 1723, in update_from_disk
    store_revision=store_revision,
  File "~/pootle/apps/pootle_store/models.py", line 1657, in update
    allow_add_and_obsolete)
  File "~/pootle/apps/pootle_store/models.py", line 1686, in update_from_diff
    update_revision=update_revision)
  File "~/pootle/apps/pootle_store/models.py", line 1953, in addunit
    newunit.save(revision=update_revision, user=user)
  File "~/pootle/apps/pootle_store/models.py", line 516, in save
    super(Unit, self).save(*args, **kwargs)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "~/.virtualenvs/pootle/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '132772-7268c2f40369e033a62a32edfebabc64' for key 'store_id'")
```
I don't think I've previously seen this one (in fact, depending on logging settings the traceback might go unnoticed), and I'm able to reproduce it consistently with the steps above.

**Comment by phlax** [comment]
@julen im wondering if this is related to #3564

which version of ttk are you using?

**Comment by julen** [comment]
TTK master, the files contain no duplicates, and `msgcat` doesn't complain about it. Checked 1.13 and works fine with that.

**Comment by unho** [comment]
@julen Can you share your logging settings changes with respect to default Pootle settings?

**Comment by unho** [comment]
@julen If you can share the files you were using it would be nice too.

**Comment by unho** [comment]
@julen I tested this several times and in several setups, and I am unable to replicate unless I use a file with duplicates. Can you please share the files you used to replicate this, your specific logging settings and any valuable detail? Does it still fail on latest TTK?

**Comment by julen** [comment]
So long as your catch-all logger writes somewhere visible (e.g. console) there's nothing special with logging configuration as far as I can tell. Here you have the file I used when I hit this error: [test.po.zip](https://github.com/translate/pootle/files/228192/test.po.zip) (as mentioned `msgcat` doesn't complain on duplicates)

**Comment by phlax** [comment]
fixed in https://github.com/translate/translate/pull/3435
