### ISSUE TITLE
UnicodeEncodeError when accepting suggestions with non-ascii symbols

### ISSUE THREAD

**Issue by ta2-1** [translate/pootle#4654]
TTK upgrade breaks an accepting suggestion with non-ascii symbols.
`translate-toolkit==1.13.0` works well
`-e git+https://github.com/translate/translate@a5ce8da75915aa3c0350e9733193c39078929090#egg=translate_toolkit-master` introduced the following traceback:

```pytb
Traceback (most recent call last):
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_misc/util.py", line 58, in wrapper
    return f(request, *args, **kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/views.py", line 674, in manage_suggestion
    return accept_suggestion(request, uid, sugg_id)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/decorators.py", line 61, in decorated_f
    return f(request, unit, *args, **kwargs)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/views.py", line 715, in accept_suggestion
    unit.accept_suggestion(suggestion, request.translation_project, request.user)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/models.py", line 1162, in accept_suggestion
    sub.save()
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_statistics/models.py", line 349, in save
    super(Submission, self).save(*args, **kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 187, in execute
    query = query % tuple([db.literal(item) for item in args])
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 278, in literal
    return self.escape(o, self.encoders)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 203, in string_literal
    return db.string_literal(obj)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc0' in position 0: ordinal not in range(128)
```

Adding new translation and suggestions wasn't affected because we use `to_db()` function when storing submission values from UI.

**Comment by julen** [comment]
As others have mentioned, I'd suggest to check for the root cause in TTK — there were already similar bugs due to the Python 3 compatibility (e.g translate/translate#3404).

**Comment by julen** [comment]
The changes from translate/translate#3428 fixed this specific traceback.
