### ISSUE TITLE
Expanding timeline causes a server error

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#4805]
See https://mozilla.locamotion.org/mni/firefox/translate/browser/chrome/browser/aboutDialog.dtd.po#unit=7407179

`exceptions:KeyError: 'datetime'`

```pytb
Traceback (most recent call last):
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 724, in __iter__
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/api/web_transaction.py", line 1100, in __call__
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 499, in wrapper
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
File "/var/www/sites/mozilla/src/pootle/apps/pootle_misc/util.py", line 57, in wrapper
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
File "/var/www/sites/mozilla/src/pootle/core/views.py", line 82, in method_wrapper
File "/var/www/sites/mozilla/src/pootle/core/views.py", line 97, in method_wrapper
File "/var/www/sites/mozilla/src/pootle/core/views.py", line 537, in dispatch
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/newrelic-2.60.0.46/newrelic/hooks/framework_django.py", line 872, in wrapper
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 117, in get
File "/var/www/sites/mozilla/src/pootle/core/views.py", line 551, in render_to_response
File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/views.py", line 373, in get_response_data
File "/var/www/sites/mozilla/src/pootle/apps/pootle_store/views.py", line 384, in get_entries_group_data
```

**Comment by phlax** [comment]
this was fixed in #4806 a further bug has also been filed around test for this #4807
