### ISSUE TITLE
[SOLVED] Running 'pootle --version' reports pkg_resources.DistributionNotFound: rq>=0.5.0,<=0.5.6

### ISSUE THREAD

**Issue by multiwebinc** [translate/pootle#4876]
The latest Pootle 2.8.0 doesn't install on Debian 7.11. It looks like it's complaining about a missing rq, but I even did a manual `pip install rq==0.5.6` before installing Pootle. The actual error is `pkg_resources.DistributionNotFound: rq>=0.5.0,<=0.5.6`. Here's the output:

```
(pootle-2.8.0)root@snail:/opt/virtualenvs# virtualenv pootle-2.8.0
New python executable in pootle-2.8.0/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...............done.
(pootle-2.8.0)root@snail:/opt/virtualenvs# source pootle-2.8.0/bin/activate
(pootle-2.8.0)root@snail:/opt/virtualenvs# deactivate 
root@snail:/opt/virtualenvs# source pootle-2.8.0/bin/activate
(pootle-2.8.0)root@snail:/opt/virtualenvs# pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz#md5=87083c0b9867963b29f7aba3613e8f4a
  Downloading pip-8.1.2.tar.gz (1.1Mb): 1.1Mb downloaded
  Running setup.py egg_info for package pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.landscape.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.github'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Installing collected packages: pip
  Found existing installation: pip 1.1
    Uninstalling pip:
      Successfully uninstalled pip
  Running setup.py install for pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.landscape.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.github'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
    Installing pip script to /opt/virtualenvs/pootle-2.8.0/bin
    Installing pip2.7 script to /opt/virtualenvs/pootle-2.8.0/bin
    Installing pip2 script to /opt/virtualenvs/pootle-2.8.0/bin
Successfully installed pip
Cleaning up...
(pootle-2.8.0)root@snail:/opt/virtualenvs# pip2.7 install requests
Collecting requests
  Using cached requests-2.10.0-py2.py3-none-any.whl
Installing collected packages: requests
Successfully installed requests-2.10.0
(pootle-2.8.0)root@snail:/opt/virtualenvs# pip install rq==0.5.6
Collecting rq==0.5.6
  Using cached rq-0.5.6-py2.py3-none-any.whl
Collecting click>=3.0 (from rq==0.5.6)
  Using cached click-6.6.tar.gz
Collecting redis>=2.7.0 (from rq==0.5.6)
  Using cached redis-2.10.5-py2.py3-none-any.whl
Installing collected packages: click, redis, rq
  Running setup.py install for click ... done
Successfully installed click-6.6 redis-2.10.5 rq-0.5.6
(pootle-2.8.0)root@snail:/opt/virtualenvs# pip install --pre Pootle
Collecting Pootle
  Using cached Pootle-2.8.0b1.tar.bz2
Collecting Django<1.9,>=1.8.13 (from Pootle)
  Using cached Django-1.8.13-py2.py3-none-any.whl
Collecting django-allauth==0.25.2 (from Pootle)
  Using cached django-allauth-0.25.2.tar.gz
Collecting django-assets==0.11 (from Pootle)
  Using cached django-assets-0.11.tar.gz
Collecting django-contact-form==1.0 (from Pootle)
  Using cached django-contact-form-1.0.tar.gz
Collecting django-contrib-comments==1.7.1 (from Pootle)
  Using cached django_contrib_comments-1.7.1-py2.py3-none-any.whl
Collecting django-overextends==0.4.1 (from Pootle)
  Using cached django_overextends-0.4.1-py2.py3-none-any.whl
Collecting django-redis==4.4.3 (from Pootle)
  Using cached django-redis-4.4.3.tar.gz
Collecting django-rq<=0.9.1,>=0.8.0 (from Pootle)
  Using cached django_rq-0.9.1-py2.py3-none-any.whl
Collecting django-transaction-hooks==0.2 (from Pootle)
  Using cached django-transaction-hooks-0.2.tar.gz
Collecting cssmin==0.2.0 (from Pootle)
  Using cached cssmin-0.2.0.tar.gz
Collecting diff-match-patch==20121119 (from Pootle)
  Using cached diff-match-patch-20121119.tar.gz
Collecting dirsync==2.2.2 (from Pootle)
  Using cached dirsync-2.2.2.zip
Collecting elasticsearch<2.0.0,>=1.0.0 (from Pootle)
  Using cached elasticsearch-1.9.0-py2.py3-none-any.whl
Collecting jsonfield==1.0.3 (from Pootle)
  Using cached jsonfield-1.0.3.tar.gz
Collecting lxml<=3.6.0,>=3.0 (from Pootle)
  Using cached lxml-3.6.0.tar.gz
Collecting python-levenshtein==0.12.0 (from Pootle)
  Using cached python-Levenshtein-0.12.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): rq<=0.5.6,>=0.5.0 in ./pootle-2.8.0/lib/python2.7/site-packages (from Pootle)
Collecting scandir==1.2 (from Pootle)
  Using cached scandir-1.2.zip
Collecting translate-toolkit==1.13.0 (from Pootle)
  Using cached translate-toolkit-1.13.0.tar.bz2
Collecting python-openid>=2.2.5 (from django-allauth==0.25.2->Pootle)
  Using cached python-openid-2.2.5.tar.gz
Collecting requests-oauthlib>=0.3.0 (from django-allauth==0.25.2->Pootle)
  Using cached requests_oauthlib-0.6.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0.3 in ./pootle-2.8.0/lib/python2.7/site-packages (from django-allauth==0.25.2->Pootle)
Collecting webassets==0.11 (from django-assets==0.11->Pootle)
  Using cached webassets-0.11.tar.gz
Collecting sphinx-me>=0.1.2 (from django-overextends==0.4.1->Pootle)
  Using cached sphinx_me-0.3-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): redis>=2.10.0 in ./pootle-2.8.0/lib/python2.7/site-packages (from django-redis==4.4.3->Pootle)
Collecting six (from dirsync==2.2.2->Pootle)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting urllib3<2.0,>=1.8 (from elasticsearch<2.0.0,>=1.0.0->Pootle)
  Using cached urllib3-1.16-py2.py3-none-any.whl
Collecting setuptools (from python-levenshtein==0.12.0->Pootle)
  Using cached setuptools-24.0.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): click>=3.0 in ./pootle-2.8.0/lib/python2.7/site-packages (from rq<=0.5.6,>=0.5.0->Pootle)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from translate-toolkit==1.13.0->Pootle)
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.3.0->django-allauth==0.25.2->Pootle)
  Using cached oauthlib-1.1.2.tar.gz
Installing collected packages: Django, python-openid, oauthlib, requests-oauthlib, django-allauth, webassets, django-assets, django-contact-form, django-contrib-comments, sphinx-me, django-overextends, django-redis, django-rq, django-transaction-hooks, cssmin, diff-match-patch, six, dirsync, urllib3, elasticsearch, jsonfield, lxml, setuptools, python-levenshtein, scandir, translate-toolkit, Pootle
  Running setup.py install for python-openid ... done
  Running setup.py install for oauthlib ... done
  Running setup.py install for django-allauth ... done
  Running setup.py install for webassets ... done
  Running setup.py install for django-assets ... done
  Running setup.py install for django-contact-form ... done
  Running setup.py install for django-redis ... done
  Running setup.py install for django-transaction-hooks ... done
  Running setup.py install for cssmin ... done
  Running setup.py install for diff-match-patch ... done
  Running setup.py install for dirsync ... done
  Running setup.py install for jsonfield ... done
  Running setup.py install for lxml ... done
  Running setup.py install for python-levenshtein ... done
  Running setup.py install for scandir ... done
  Running setup.py install for translate-toolkit ... done
  Running setup.py install for Pootle ... done
Successfully installed Django-1.8.13 Pootle-2.8.0b1 cssmin-0.2.0 diff-match-patch-20121119 dirsync-2.2.2 django-allauth-0.25.2 django-assets-0.11 django-contact-form-1.0 django-contrib-comments-1.7.1 django-overextends-0.4.1 django-redis-4.4.3 django-rq-0.9.1 django-transaction-hooks-0.2 elasticsearch-1.9.0 jsonfield-1.0.3 lxml-3.6.0 oauthlib-1.1.2 python-levenshtein-0.12.0 python-openid-2.2.5 requests-oauthlib-0.6.1 scandir-1.2 setuptools-24.0.2 six-1.10.0 sphinx-me-0.3 translate-toolkit-1.13.0 urllib3-1.16 webassets-0.11
(pootle-2.8.0)root@snail:/opt/virtualenvs# pootle --version
Traceback (most recent call last):
  File "/opt/virtualenvs/pootle-2.8.0/bin/pootle", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/virtualenvs/pootle-2.8.0/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/opt/virtualenvs/pootle-2.8.0/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/virtualenvs/pootle-2.8.0/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: rq>=0.5.0,<=0.5.6
```

**Comment by multiwebinc** [comment]
Same error with Pootle 2.7.6

**Comment by multiwebinc** [comment]
```
# pip freeze --local | grep rq
django-rq==0.9.0
rq==0.5.6
```

**Comment by multiwebinc** [comment]
OK, another update. I saw from [this comment](https://github.com/translate/pootle/issues/3986#issuecomment-132116411) that using `virtualenvwrapper` got rid of the problem for that user and their instructions were:

> run "mkvirtualenv pootle", "workon pootle" "pip install pootle".

I did that, however before `pip install pootle` I issued a `pip install pip --upgrade` and I got the same exact error. However, if I omit this line, it worked:

```
# pootle --version
Pootle 2.8.0b1 (Django 1.9c1, Translate Toolkit 1.13.0)
```

It would appear there is a problem to do with the version of pip installed. 

This version works:
```
# pip --version
pip 1.1 from /root/.virtualenvs/pootle/lib/python2.7/site-packages/pip-1.1-py2.7.egg (python 2.7)
```

This doesn't:
```
# pip --version
pip 8.1.2 from /root/.virtualenvs/test/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by dwaynebailey** [comment]
@multiwebinc we've had similar bugs in #3986 and #3980 which would be nice to trackdown.  I'm really not sure how the pip version could impact this, but it does seem like the installs with `pip 8.1.2` are installing to `$venv/local/lib/...` vs `pip 1.1` installing to `$venv/lib/...`

I suspect though something deeper.  Would you be able to run the install with [pip logging](https://pip.pypa.io/en/stable/reference/pip/#file-logging) enabled?  Hopefully that might reveal installation issues if they exist.

**Comment by multiwebinc** [comment]
OK here's the log file:

[logfile.txt](https://github.com/translate/pootle/files/351050/logfile.txt)

**Comment by dwaynebailey** [comment]
@multiwebinc that didn't seem to catch the `rq` build, likely it reused the wheel.  Which might explain the 8.1.2 issue, it makes use of cache and wheels.  While 1.1 doesn't have any of that.  So a miscompile could hang around in the cache and keep on getting reused.

**Comment by multiwebinc** [comment]
@dwaynebailey I don't know what a wheel is. Do you have any idea how I could force it to not use the cache or the wheel? Unfortunately with the old version of pip, I'm unable to run the RQ worker:

```
# pootle rqworker --config /etc/pootle/pootle.conf &
[1] 26668
(pootle)root@snail:/opt/pootle# 2016-07-06 18:38:06,611 INFO Loading custom settings from '/etc/pootle/pootle.conf'...
2016-07-06 22:38:06,752 WARNING /opt/pootle/local/lib/python2.7/site-packages/django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning)

2016-07-06 22:38:06,798 INFO Using Python PO
Traceback (most recent call last):
  File "/opt/pootle/bin/pootle", line 9, in <module>
    load_entry_point('Pootle==2.8.0b1', 'console_scripts', 'pootle')()
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 314, in main
    django_settings_module='pootle.settings')
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/runner.py", line 294, in run_app
    management.execute_from_command_line(command)
  File "/opt/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/opt/pootle/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/opt/pootle/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/pootle/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/apps.py", line 20, in ready
    importlib.import_module("pootle_store.getters")
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/getters.py", line 18, in <module>
    from .unit.search import DBSearchBackend
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/unit/search.py", line 14, in <module>
    from pootle_store.views import SIMPLY_SORTED
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/views.py", line 32, in <module>
    from pootle.core.views import PootleJSON
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/core/views.py", line 39, in <module>
    from pootle_store.forms import UnitExportForm
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/forms.py", line 37, in <module>
    from .form_fields import (
  File "/opt/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_store/form_fields.py", line 10, in <module>
    from django.utils.datastructures import MergeDict, MultiValueDict
ImportError: cannot import name MergeDict
^C
[1]+  Exit 1                  pootle rqworker --config /etc/pootle/pootle.conf
```

**Comment by dwaynebailey** [comment]
I wonder if `pip install --no-cache-dir --force-reinstall pootle` might force it to retry.

**Comment by dwaynebailey** [comment]
@multiwebinc I'm afraid pip has nothing to do with rqworker.  You don't seem to be running any of these in a virtualenv.  Also I'm not sure sure there is `local` in `/opt/pootle/local/lib`

**Comment by multiwebinc** [comment]
> You don't seem to be running any of these in a virtualenv

Yes, I'm running these commands in a virtualenv, but I just left out everything before the `#`. 

I tried `pip install --no-cache-dir --force-reinstall pootle --upgrade` and `pip install --no-cache-dir --force-reinstall rq==0.5.6 --upgrade`, but I still get the same error:

```
(pootle-test)root@snail:/opt/pootle-test# pootle --version
Traceback (most recent call last):
  File "/opt/pootle-test/bin/pootle", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/pootle-test/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/opt/pootle-test/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/pootle-test/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: rq>=0.5.0,<=0.5.6
```

**Comment by multiwebinc** [comment]
The only thing in `/opt/pootle/local/lib/` is `python2.7`.

**Comment by dwaynebailey** [comment]
This is really odd since we deploy all the time on Ubuntu.  But interwebs seem to indicate bad interaction with easy_install.  So last suggestion `virtualenv --no-site-packages` just to make sure this is actually an isolated venv.  Off to bed.

**Comment by multiwebinc** [comment]
@dwaynebailey Same thing happens. Also:

> The --no-site-packages flag is deprecated; it is now the default behavior.

**Comment by phlax** [comment]
hi @multiwebinc if you pop into our support channel - https://gitter.im/translate/pootle we can give you more immediate support

**Comment by dwaynebailey** [comment]
This is caused by a conflict between `setuptools` and `distribute`.  These two can normally coexist but since we use a wrapper for the `pootle` command they cannot.  To solve simply uninstall distribute from your virtual environment.

`pip uninstall distribute`

**Comment by phlax** [comment]
wow @dwaynebailey you beat me to it!

**Comment by multiwebinc** [comment]
@dwaynebailey You don't sleep much, do you? Thanks for the help. @phlax was able to figure that out as well in the chat.

So is this a bug? Maybe there is some way to check for this conflict to output a meaningful error to the console. Or perhaps it's something that should be added to the documentation?

**Comment by phlax** [comment]
@multiwebinc fair point - ill reopen till we have addressed either in docs or install

**Comment by phlax** [comment]
@multiwebinc it seems this problem can be avoided by adding the flag `--setuptools` when setting up the virtualenv (see here https://virtualenv.pypa.io/en/stable/reference/#cmdoption--setuptools).

Im pretty sure that this will work with virtualenvwrapper - but ill check this, and add to docs on wheezy install
