### ISSUE TITLE
Upgrade from 2.5.0 to 2.6.1 to 2.7.6 fails with Internal Server error

### ISSUE THREAD

**Issue by itcab** [translate/pootle#4955]
Upgrade Process
Ubuntu 12.04 LTS 
Apache2 and mysql db
```shell
source /var/www/pootle/env/bin/activate
pip install --upgrade pip
pip install --upgrade "Pootle>=2.6,<2.7"
pootle setup

(env) $ pyclean .
pip install --upgrade Pootle
```

New conf file
```shell
pootle init --db mysql --db-name pootle --db-user pootle
```
customized conf file..

```shell
cp /root/.pootle/pootle.conf  /var/www/pootle/your_custom_settings.conf
chown -R www-data:www-data /var/www/pootle
```

```shell
apt-get install -y python-software-properties
add-apt-repository -y ppa:rwky/redis
apt-get update
apt-get install -y redis-server
```

```shell
pootle rqworker &
```

```shell
pootle check
 pootle check
2016-07-22 15:41:20,061 INFO Loading custom settings from '/root/.pootle/pootle.conf'...
2016-07-22 13:41:20,418 INFO Using Python PO
System check identified no issues (0 silenced).
```
```shell
/etc/init.d/apache2 restart
```

The following error Occurs in Apache Log:
```apache
[Fri Jul 22 13:42:48 2016] [error] 2016-07-22 13:42:48,374 INFO Using Python PO
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109] mod_wsgi (pid=15211): Exception occurred processing WSGI script '/var/www/pootle/wsgi.py'.
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109] Traceback (most recent call last):
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/wsgi.py", line 51, in application
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]     _wsgi_application = get_wsgi_application()
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]     django.setup()
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]     apps.populate(settings.INSTALLED_APPS)
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]     app_config.import_models(all_models)
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]     self.models_module = import_module(models_module_name)
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]     __import__(name)
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_profile/models.py", line 33, in <module>
[Fri Jul 22 13:42:48 2016] [error] [client 10.10.1.109] ImportError: cannot import name cached_property
[Fri Jul 22 13:42:49 2016] [error] 2016-07-22 13:42:49,278 INFO Using Python PO
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109] mod_wsgi (pid=15210): Exception occurred processing WSGI script '/var/www/pootle/wsgi.py'.
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109] Traceback (most recent call last):
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/wsgi.py", line 51, in application
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]     _wsgi_application = get_wsgi_application()
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]     django.setup()
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]     apps.populate(settings.INSTALLED_APPS)
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]     app_config.import_models(all_models)
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]     self.models_module = import_module(models_module_name)
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]     __import__(name)
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109]   File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_profile/models.py", line 33, in <module>
[Fri Jul 22 13:42:49 2016] [error] [client 10.10.1.109] ImportError: cannot import name cached_property
```

**Comment by julen** [comment]
I'm pretty sure this is running old code (i.e. not 2.7.6 definitely), as the traceback is referencing `pootle_profile.models`, which is long gone.

**Comment by julen** [comment]
By the way seeing this...
>2016-07-22 15:41:20,061 INFO Loading custom settings from '/root/.pootle/pootle.conf'...

You be aware that you should never ever run Pootle under the root user.

--

At the same time, it looks like your apache+mod_wsgi is using a system-wide Python interpreter and Pootle installation, as opposed to their counterparts from the virtualenv.

**Comment by itcab** [comment]
i do not start the pootle server as root. 
I only use it over the apache webserver.
Yes python is installed  but it should use the one in the env.

What can i do to solve this issues.
Old code is possible because i  try to upgrade my installation from pootle 2.5.0 to 2.7.6

**Comment by dwaynebailey** [comment]
@itcab you might want to visit out chat channel https://gitter.im/translate/pootle for more immediate help.

I did a quick check base on [above comment](https://github.com/translate/pootle/issues/4955#issuecomment-234550162) and `pootle/apps/pootle_profile/models.py` was last seen in 2.5 days.  So there is definately a mixup of versions.

A potential fix would be to remove your virtualenv and recreate it to remove any potential for conflict.

**Comment by itcab** [comment]
Hi Dwayne,

ok i will try this, i delete the /var/www/pootle/env   and recreate it.
The only thing i have to backup is the po or translate folder?
/var/www/pootle/env/lib/python2.7/site-packages/pootle/po

**Comment by itcab** [comment]
I have done this now and created a new env with a new pootle installation.
And i think it is working  with 2.7.6.
I will check the installation and data now,

Thank you for the fast and good help.

**Comment by dwaynebailey** [comment]
@itcab excellent.  My only flag for future readers is that I'd backup `po` directory and the database if you're using sqlite.

**Comment by unho** [comment]
Closing this. @itcab if you experience this again please reopen it.
