### ISSUE TITLE
Missing project causes Pootle FS traceback

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#5385]
``` pytb
(pootle)~/dev/pootle $ pootle fs rm

Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/pootle/bin/pootle", line 11, in <module>
    load_entry_point('Pootle', 'console_scripts', 'pootle')()
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 313, in main
    django_settings_module='pootle.settings')
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 293, in run_app
    management.execute_from_command_line(command)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dwayne/dev/pootle/pootle/core/management/subcommands.py", line 138, in run_from_argv
    known, __ = parser.parse_known_args(argv[2:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1942, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1898, in consume_positionals
    take_action(action, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1096, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py", line 1950, in _parse_known_args
    self.error(_('too few arguments'))
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 65, in error
    raise CommandError("Error: %s" % message)
django.core.management.base.CommandError: Error: too few arguments
```

**Comment by phlax** [comment]
this seems to be fixed
```
(pootle)phlax@e194c80ba6f7:~/.virtualenvs/pootle/pootle$ pootle fs state foo
2017-01-24 13:06:42,541 INFO Loading custom settings from '/home/phlax/.pootle/pootle.conf'...
CommandError: Project matching query does not exist.
(pootle)1 phlax@e194c80ba6f7:~/.virtualenvs/pootle/pootle$ pootle fs state    
2017-01-24 13:06:45,904 INFO Loading custom settings from '/home/phlax/.pootle/pootle.conf'...
CommandError: Error: too few arguments
```
