### ISSUE TITLE
Django Traceback issue exporting xliff format

### ISSUE THREAD

**Issue by v60fan** [translate/pootle#5828]
I'm getting the below error suddenly on some of my projects in xliff format. It seems related to previous issues reported many years ago like: [1643](https://github.com/translate/pootle/issues/1643) and [1445](https://github.com/translate/pootle/issues/1445)

Is there something I can adjust on my side to prevent this?

```pytb
Traceback (most recent call last):
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/import_export/views.py", line 42, in export
    contents = BytesIO(store.serialize())
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1882, in serialize
    store = self.convert(storeclass)
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 2037, in convert
    output.addunit(unit.convert(output.UnitClass))
  File "/var/www/pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 609, in convert
    newunit.target = self.target
  File "/var/www/pootle/env/lib/python2.7/site-packages/translate/storage/lisa.py", line 154, in settarget
    languageNode = self.createlanguageNode(lang, text, "target")
  File "/var/www/pootle/env/lib/python2.7/site-packages/translate/storage/xliff.py", line 106, in createlanguageNode
    langset.text = text
  File "src/lxml/lxml.etree.pyx", line 1031, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:51697)
  File "src/lxml/apihelpers.pxi", line 711, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:23071)
  File "src/lxml/apihelpers.pxi", line 699, in lxml.etree._createTextNode (src/lxml/lxml.etree.c:22931)
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8 (src/lxml/lxml.etree.c:30219)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by v60fan** [comment]
Pootle 2.7.6 ; Translate Toolkit 1.13.0
I aim to share a file which causes the error with the Pootle team via email/Gitter private room

**Comment by phlax** [comment]
not sure what we need to handle this correctly - but i figure this is related http://stackoverflow.com/questions/17138088/french-and-lxml-text

**Comment by unho** [comment]
Setting some characters triggers this error:

```python
(Pdb) langset.text = u'Een\r\n'
(Pdb) langset.text = u'Een\b'
*** ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
(Pdb) langset.text = u'Een\a'
*** ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
(Pdb) langset.text = u'Een\t'
(Pdb) langset.text = u'Een\v'
*** ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
(Pdb) langset.text = u'Een\r'
(Pdb)
```

**Comment by unho** [comment]
@v60fan Fixed by https://github.com/translate/translate/pull/3551 We will publish a TTK release soon with this fix.

**Comment by unho** [comment]
Landed a followup https://github.com/translate/translate/pull/3555
