### ISSUE TITLE
Adding languages to a pootle_fs localfs projects produces a traceback

### ISSUE THREAD

**Issue by marcoceppi** [translate/pootle#6300]
After adding a project to pootle_fs localfs, rq throws the following exception when adding a new language:

```pytb
[2017-04-26T22:01:36]   default: pootle_project.forms.update_translation_project(<TranslationProject: /ay/silph-web/>, True, 'http://t.sil.ph/') (c9af6b17-5897-47c0-b345-802caf2851c4)
2017-04-26 22:01:36,555 INFO Scanning for new files in /ay/silph-web/
[2017-04-26T22:01:37]   AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/home/ubuntu/pootle/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/home/ubuntu/pootle/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/ubuntu/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_project/forms.py", line 47, in update_translation_project
    raise e
AttributeError: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/home/ubuntu/pootle/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/home/ubuntu/pootle/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/ubuntu/pootle/local/lib/python2.7/site-packages/pootle/apps/pootle_project/forms.py", line 47, in update_translation_project
    raise e
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Tracing the code,

1. `pootle_project.forms.update_translation_project(<TranslationProject: /ay/silph-web/>, True, 'http://t.sil.ph/')` is executed in the RQ.
2. This eventually invokes `pootle_translationproject.models.TranslationProject.update_from_disk()`.
3. This in turn calls `TranslationProject.scan_files()`
4. Which [eventually invokes](https://github.com/translate/pootle/blob/master/pootle/apps/pootle_translationproject/models.py#L402) `pootle_app.project_tree.add_files`, passing in `self.real_path` which is `None` by design for pootle_fs projects.

Since `add_files` calls `pootle_app.project_tree.to_podir_path` to get the `realpath` and the path is None it results in a NoneType has not attribute startswith.

It seems a similar work around may be needed for as what was placed in #5899

**Comment by unho** [comment]
Fix landed in #6308, so closing.
