### ISSUE TITLE
Deleting constraints badly broken

### ISSUE THREAD

**Issue by agaida** [translate/pootle#6420]
Version 2.8.0-rc5

Hi,
we would like to delete some languages from a new project with the web client - it is not possible for some languages:

```
{õ_õ}
Serverfehler
Ein Server-Fehler ist aufgetreten. Danke für Ihre Geduld.
Ausnahme: update or delete on table "pootle_store_qualitycheck" violates foreign key constraint "quality_check_id_refs_id_30436eab" on table "pootle_app_submission" DETAIL: Key (id)=(434591) is still referenced from table "pootle_app_submission".
```
Any idea how to work around it without hard touching the database?

**Comment by agaida** [comment]
Backtrace:
```
update or delete on table "pootle_store_qualitycheck" violates foreign key constraint "quality_check_id_refs_id_30436eab" on table "pootle_app_submission"
DETAIL:  Key (id)=(434591) is still referenced from table "pootle_app_submission".


Traceback (most recent call last):
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/core/views/decorators.py", line 49, in method_wrapper
    return f(self, request, *args, **kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/core/views/decorators.py", line 71, in method_wrapper
    return f(self, request, *args, **kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/core/views/base.py", line 119, in dispatch
    return super(PootleAdminView, self).dispatch(request, *args, **kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/core/views/base.py", line 126, in post
    return self.get(*args, **kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 116, in get
    context = self.get_context_data(object=self.object)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/apps/pootle_project/views.py", line 226, in get_context_data
    self.process_formset()
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/apps/pootle_project/views.py", line 258, in process_formset
    formset.save()
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/forms/models.py", line 651, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/forms/models.py", line 767, in save_existing_objects
    self.delete_existing(obj, commit=commit)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/forms/models.py", line 638, in delete_existing
    obj.delete()
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/models.py", line 257, in delete
    super(TranslationProject, self).delete(*args, **kwargs)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/models/base.py", line 958, in delete
    return collector.delete()
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 306, in delete
    count = query.delete_batch(pk_list, self.using)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 46, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/models/sql/subqueries.py", line 28, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/pootle/pootle.env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: update or delete on table "pootle_store_qualitycheck" violates foreign key constraint "quality_check_id_refs_id_30436eab" on table "pootle_app_submission"
DETAIL:  Key (id)=(434591) is still referenced from table "pootle_app_submission".



<WSGIRequest: POST '/projects/lxhotkey/admin/languages/'
```>

**Comment by phlax** [comment]
hi @agaida i have tested this out with current master (and iirc i tested once before) and it seem to work as expected.

im wondering if its possible that you have a django version mismatch, as django introduced the need to explicitly declare cascade deletion of foreign keys some time back.

either way, as i wasnt able to reproduce on current master (which we are about to release), im gonna close the ticket, but please do reopen if the problem persists, and the correct deps are definitely in place

**Comment by agaida** [comment]
it was a pip install in a clean machine - so i guess all dependencies were fullfilled - anyways, thanks
