### ISSUE TITLE
Traceback when running refresh_stats

### ISSUE THREAD

**Issue by unho** [translate/pootle#6423]
Traceback when running `refresh_stats`:

```pytb
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/sites/mozilla/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/__init__.py", line 124, in handle
    return self._handle(**options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/__init__.py", line 151, in _handle
    self.handle_all(**options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/__init__.py", line 162, in handle_all
    self._handle_atomic_tps(**options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/__init__.py", line 204, in _handle_atomic_tps
    self.do_translation_project(tp, **options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/__init__.py", line 97, in do_translation_project
    self.handle_all_stores(tp, **options)
  File "/var/www/sites/mozilla/src/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 33, in handle_all_stores
AttributeError: 'Store' object has no attribute 'update_all_cache'
```

**Comment by unho** [comment]
The command is gone. So closing.
