### ISSUE TITLE
AttributeError: DjangoTranslation instance has no attribute 'plural'

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#6441]
https://sentry.io/pootle-dev/pootle-master/issues/280870390/

```pytb
AttributeError: DjangoTranslation instance has no attribute 'plural'
(51 additional frame(s) were not displayed)
...
  File "django/templatetags/i18n.py", line 149, in render
    result = translation.ungettext(singular, plural, count)
  File "django/utils/translation/__init__.py", line 89, in ungettext
    return _trans.ungettext(singular, plural, number)
  File "django/utils/translation/trans_real.py", line 394, in ungettext
    return do_ntranslate(singular, plural, number, 'ungettext')
  File "django/utils/translation/trans_real.py", line 371, in do_ntranslate
    return getattr(t, translation_function)(singular, plural, number)
  File "python2.7/gettext.py", line 409, in ungettext
    tmsg = self._catalog[(msgid1, self.plural(n))]

AttributeError: DjangoTranslation instance has no attribute 'plural'
```

**Comment by dwaynebailey** [comment]
This occurs at this URL `http://localhost:8000/af/admin/suggestions/` for various locales including ach, son.  But not strangely for af.

This is for the `u'Showing %(n)s result per page'` string.  Neither ach, son nor af have this string translated in their files, in fact they have no MO file build.

My deep suspicion is that we're injecting a field into the string when rendering, which might be confirmed by another TB for some other languages notably:

```python
Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/library.py", line 245, in render
    return t.render(new_context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/templatetags/i18n.py", line 149, in render
    result = translation.ungettext(singular, plural, count)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 89, in ungettext
    return _trans.ungettext(singular, plural, number)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 394, in ungettext
    return do_ntranslate(singular, plural, number, 'ungettext')
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 371, in do_ntranslate
    return getattr(t, translation_function)(singular, plural, number)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 412, in ungettext
    tmsg = self._catalog[(msgid1, self.plural(n))]
  File "<string>", line 1, in <lambda>
TypeError: unsupported operand type(s) for %: 'BoundField' and 'int'
```
