### ISSUE TITLE
Pootle 2.7.6 Migration error

### ISSUE THREAD

**Issue by AKFourSeven** [translate/pootle#6514]
Hello,

# Issue:
I was trying to move from SQLite to MySQL and followed some guideline here and there (particularly on the pootle documentation) and when I tried to do a 

    pootle loaddata data.json

Being a Django neophyte I am not sure of what I am supposed to do with this outcome:

```
Traceback (most recent call last):
  File "/Users/akougblenou/PROJECTS/Pootle/env/bin/pootle", line 11, in <module>
    load_entry_point('Pootle==2.7.6', 'console_scripts', 'pootle')()
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/pootle/runner.py", line 319, in main
    django_settings_module='pootle.settings')
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/pootle/runner.py", line 299, in run_app
    management.execute_from_command_line(command)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 91, in loaddata
    self.load_label(fixture_label)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 148, in load_label
    obj.save(using=self.using)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/pootle/apps/virtualfolder/models.py", line 468, in relate_unit
    pootle_path = instance.store.pootle_path
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/db/models/fields/related.py", line 572, in __get__
    rel_obj = qs.get()
  File "/Users/akougblenou/PROJECTS/Pootle/env/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
pootle_store.models.DoesNotExist: Problem installing fixture '/Users/akougblenou/PROJECTS/Pootle/data.json': Store matching query does not exist.
```
It seems that there is some error possibly from my data.json but this is a dump coming from pootle sqlite quick install, so I wonder what really went wrong, when and how !!

# Environment:
* Pootle version: Pootle 2.7.6 (Django 1.7.11, Translate Toolkit 1.13.0)
* Database and version: mysql  Ver 14.14 Distrib 5.7.18, for osx10.12 (x86_64) using  EditLine wrapper
* Operating System and version: macOS Sierra

**Comment by phlax** [comment]
hi @AKFourSeven i havent tried to do this before - so not clear if any instructions that we have work.

id be happy to help to get loaded into mysql tho - if you can ping us on https://gitter.im/translate/pootle we can try and work out how to do the conversion

**Comment by dwaynebailey** [comment]
@AKFourSeven just looking at our dev docs on [database migration](http://docs.translatehouse.org/projects/pootle/en/latest/server/database_migration.html) we specifically try to avoid load/dumpdata and suggest some other tools.

**Comment by dwaynebailey** [comment]
Just some notes of possible solutions:

* Our own docs point to some [migration tools](http://docs.translatehouse.org/projects/pootle/en/latest/server/database_migration.html)
* https://stackoverflow.com/questions/3034910/whats-the-best-way-to-migrate-a-django-db-from-sqlite-to-mysql
* https://stackoverflow.com/questions/35257550/migrating-to-mysql-in-django

But like @phlax said above, we'd love to help on the Gitter channel.
