### ISSUE TITLE
pootle refresh_scores: Column 'date_joined' cannot be null

### ISSUE THREAD

**Issue by Mixaill** [translate/pootle#6516]
when upgrading from 2.8-rc5 to 2.8-rc6

```
(env) xvm-pootle@alles:~$ pootle refresh_scores --reset
(env) xvm-pootle@alles:~$ pootle refresh_scores
Traceback (most recent call last):
  File "/home/xvm-pootle/env/bin/pootle", line 11, in <module>
    sys.exit(main())
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 322, in main
    django_settings_module='pootle.settings')
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/runner.py", line 297, in run_app
    management.execute_from_command_line(command)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/refresh_scores.py", line 45, in handle
    score_updater.get(get_user_model())().refresh_scores(users)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_score/updater.py", line 393, in refresh_scores
    self.update(users=users)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/core/contextmanagers.py", line 205, in bulk_operations
    yield
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/contextlib.py", line 121, in nested
    if exit(*exc):
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/core/contextmanagers.py", line 197, in bulk_context
    callback_handler(model, updated)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/core/contextmanagers.py", line 171, in _callback_handler
    update_fields=updated.update_fields)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/apps/accounts/receivers.py", line 21, in handle_account_user_update
    crud.get(User).update(**kwargs)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/core/bulk.py", line 188, in update
    updated = self.update_object_dict(objects, kwargs.get("updates"), fields)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/core/bulk.py", line 174, in update_object_dict
    fields=fields)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/pootle/core/bulk.py", line 53, in bulk_update
    update_fields=fields)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/bulk_update/helper.py", line 179, in bulk_update
    connection.cursor().execute(sql, parameters)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 115, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/xvm-pootle/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
django.db.utils.IntegrityError: (1048, "Column 'date_joined' cannot be null")
```

**Comment by phlax** [comment]
hi @Mixaill thanks for reporting this - ill fix asap

if you need a workaround in the interim - give us a shout on https://gitter.im/translate/pootle and we can work something out

**Comment by Mixaill** [comment]
When I performed the migration from PostgreSQL to MariaDB I accidentally drop the date_joined column in accounts_user table.

So I replaced all 0000.00.00 to 1970.01.01 and then pootle refresh_scores was executed without any error.
