### ISSUE TITLE
Migrating 2.7.x to master causes Traceback in terminology

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#6591]
# Steps to reproduce:
1. setup `stable/2.7.x` branch
2. Change `Terminology` project checkerstyle to `standard` from `terminology`
3. Move to `master`
4. `pootle migrate`

# Results (Expected/Actual):

```pytb
  Applying pootle_word.0003_add_word_stems...
Traceback (most recent call last):
  File "/Users/dwayne/dev/envs/pootle/bin/pootle", line 11, in <module>
    load_entry_point('Pootle', 'console_scripts', 'pootle')()
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 335, in main
    django_settings_module='pootle.settings')
  File "/Users/dwayne/dev/pootle/pootle/runner.py", line 310, in run_app
    management.execute_from_command_line(command)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/dwayne/dev/pootle/pootle/apps/pootle_word/migrations/0003_add_word_stems.py", line 39, in stem_terminology_words
    Stem.objects.bulk_create([Stem(root=st) for st in stems], batch_size=1000)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 452, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 1068, in _batched_insert
    self._insert(item, fields=fields, using=self.db)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dwayne/dev/envs/pootle/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: too many terms in compound SELECT
```

# Environment (i.e. 'pootle --version', DB, OS, Browser):

`master`

**Comment by dwaynebailey** [comment]
Validated that this related to sqlite, it passes correctly on MySQL.  Since sqlite is not supported in production I'm closing this as WONTFIX
