### ISSUE TITLE
Can't create table 'pootle.#sql-583f_137

### ISSUE THREAD

**Issue by xperseguers** [translate/pootle#6673]
# Steps to reproduce:

Upgrading from 2.7.6 to 2.9-beta (would have preferred 2.8.1 but upgrade instructions from http://docs.translatehouse.org/projects/pootle/en/latest/server/upgrading.html result into upgrading to 2.9-beta).

Using MySQL, when I run step

```
# pootle migrate --fake-initial
```

# Results (Expected/Actual):

I get this:

```
Operations to perform:
  Apply all migrations: account, accounts, auth, contenttypes, pootle_app, pootle_comment, pootle_config, pootle_data, pootle_format, pootle_fs, pootle_language, pootle_project, pootle_revision, pootle_score, pootle_statistics, pootle_store, pootle_translationproject, pootle_word, reports, sessions, sites, socialaccount, staticpages, virtualfolder
Running migrations:
  Applying pootle_project.0006_project_filetypes...Traceback (most recent call last):
  File "/opt/local/pootle/bin/pootle", line 11, in <module>
    load_entry_point('Pootle==2.9.0b2', 'console_scripts', 'pootle')()
  File "/opt/local/pootle/lib/python2.7/site-packages/pootle/runner.py", line 357, in main
    run_app(project='pootle', django_settings_module='pootle.settings')
  File "/opt/local/pootle/lib/python2.7/site-packages/pootle/runner.py", line 338, in run_app
    management.execute_from_command_line(command)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 92, in __exit__
    self.execute(sql)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/local/pootle/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/local/pootle/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1005, "Can't create table 'pootle.#sql-583f_137' (errno: 150)")
```

When I try to rerun, I get:

```
Operations to perform:
  Apply all migrations: account, accounts, auth, contenttypes, pootle_app, pootle_comment, pootle_config, pootle_data, pootle_format, pootle_fs, pootle_language, pootle_project, pootle_revision, pootle_score, pootle_statistics, pootle_store, pootle_translationproject, pootle_word, reports, sessions, sites, socialaccount, staticpages, virtualfolder
Running migrations:
  Applying pootle_project.0006_project_filetypes...Traceback (most recent call last):
  File "/opt/local/pootle/bin/pootle", line 11, in <module>
    load_entry_point('Pootle==2.9.0b2', 'console_scripts', 'pootle')()
  File "/opt/local/pootle/lib/python2.7/site-packages/pootle/runner.py", line 357, in main
    run_app(project='pootle', django_settings_module='pootle.settings')
  File "/opt/local/pootle/lib/python2.7/site-packages/pootle/runner.py", line 338, in run_app
    management.execute_from_command_line(command)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 43, in add_field
    super(DatabaseSchemaEditor, self).add_field(model, field)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 393, in add_field
    return self.create_model(field.remote_field.through)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 295, in create_model
    self.execute(sql, params or None)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/opt/local/pootle/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/local/pootle/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/local/pootle/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1050, "Table 'pootle_app_project_filetypes' already exists")
```

Deleting (empty) table `pootle_app_project_filetypes` results into the same first behaviour (cannot create table) when re-running.

# Environment (i.e. 'pootle --version', DB, OS, Browser):

* MySQL 5.5.53
* Debian 8.7
* Python 2.7.9

**Comment by phlax** [comment]
@xperseguers you shouldnt need `--fake-initial` when upgrading 2.7.6 -> 2.8 altho i dont think its the cause of your problem. if you can jump onto https://gitter.im/translate/pootle we can probs help

**Comment by phlax** [comment]
re upgrading, we need to fix the docs but to upgrade to 2.8.1 you need to miss out the `--pre` from the line here http://docs.translatehouse.org/projects/pootle/en/latest/server/upgrading.html#upgrading-from-version-2-6-x-or-later

so just:

```
(env) $ pip install --process-dependency-links --upgrade Pootle
```

**Comment by phlax** [comment]
ticket added re install docs https://github.com/translate/pootle/issues/6674

**Comment by unho** [comment]
The **latest** docs branch is for the `master` git branch (the development one), so it is correct that it tells you to use `--pre`.

**Comment by unho** [comment]
Changed RTD config so by visiting http://docs.translatehouse.org/projects/pootle/ you get redirected to newest stable docs instead of **latest**.

**Comment by phlax** [comment]
seems that this was related to some tables being myisam and not converted to innodb
