### ISSUE TITLE
 Search is failing when searching for non-ascii character

### ISSUE THREAD

**Issue by fareshabibi** [translate/pootle#6771]
When I try to search for a word containing a non-ascii character (é, è ...). I get "Error Server"  in the middle of the page and nothing else is displayed. I receive a mail containing pootle logs. 

# logs : 
Traceback (most recent call last):
 File ".../pootle/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
   return self.dispatch(request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
   response = view_func(request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
   return bound_func(*args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_misc/util.py", line 53, in wrapper
   return f(request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/views/decorators.py", line 49, in method_wrapper
   return f(self, request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/views/decorators.py", line 71, in method_wrapper
   return f(self, request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/views/base.py", line 133, in dispatch
   return super(PootleJSON, self).dispatch(request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/views/decorators.py", line 49, in method_wrapper
   return f(self, request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/views/decorators.py", line 71, in method_wrapper
   return f(self, request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/views/base.py", line 91, in dispatch
   return super(PootleDetailView, self).dispatch(request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
   return handler(request, *args, **kwargs)
 File ".../pootle/env/lib/python2.7/site-packages/django/views/generic/detail.py", line 117, in get
   return self.render_to_response(context)
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/views/mixins.py", line 129, in render_to_response
   self.get_response_data(self.gather_context_data(context)),
 File ".../pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/views.py", line 538, in get_response_data
   'editor': self.render_edit_template(context),
 File ".../pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/views.py", line 421, in render_edit_template
   request=self.request)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
   return self.template.render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 208, in render
   return self._render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
   return self.nodelist.render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 994, in render
   bit = node.render_annotated(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
   return self.render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 315, in render
   return nodelist.render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 994, in render
   bit = node.render_annotated(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
   return self.render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/defaulttags.py", line 315, in render
   return nodelist.render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 994, in render
   bit = node.render_annotated(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
   return self.render(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 1044, in render
   output = self.filter_expression.resolve(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 711, in resolve
   obj = self.var.resolve(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 852, in resolve
   value = self._resolve_lookup(context)
 File ".../pootle/env/lib/python2.7/site-packages/django/template/base.py", line 915, in _resolve_lookup
   current = current()
 File ".../pootle/env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 352, in get_search_locations_url
   get_editor_filter(search=self.locations, sfields='locations'),
 File ".../pootle/env/lib/python2.7/site-packages/pootle/core/url_helpers.py", line 101, in get_editor_filter
   filter_string = '#search=%s' % urllib.quote_plus(search)
 File "/usr/local/lib/python2.7/urllib.py", line 1308, in quote_plus
   s = quote(s, safe + ' ')
 File "/usr/local/lib/python2.7/urllib.py", line 1303, in quote
   return ''.join(map(quoter, s))
KeyError: u'\xe9'
<WSGIRequest: GET '/xhr/units/34792/edit/'>
# Results (Expected/Actual):
I was expecting pootle to display the result of my search, but a server error message that appears
# Environment 
Pootle version: 2.9, DB: Mysql 5.7 , Os: centos 6 , Browser: google chrome

**Comment by comradekingu** [comment]
Works on Pootle 2.9.0rc1, Translate Toolkit 2.2.5.
Describe more closely what it is you are doing if the problem persists.

**Comment by jasminlapalme** [comment]
We have to make this kind of query :
`http://server.pootle.com/projects/translate/#search=é&sfields=source,target`
