### ISSUE TITLE
Cannot configure project with git FS backend

### ISSUE THREAD

**Issue by satabin** [translate/pootle#6781]
# Steps to reproduce:

 * Install pootle
 * Install pootle_fs git (using workaround described in #6759)
 * Create a project with fs backend
 * Try to save

# Results (Expected/Actual):

The server crashes with the following exception:
```shell
Traceback (most recent call last):
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/pootle/core/views/mixins.py", line 30, in dispatch
    **kwargs)
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/pootle/core/views/api.py", line 120, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/pootle/core/views/api.py", line 184, in put
    if form.is_valid():
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 169, in is_valid
    return self.is_bound and not self.errors
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 161, in errors
    self.full_clean()
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 371, in full_clean
    self._clean_form()
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 398, in _clean_form
    cleaned_data = self.clean()
  File "/home/lucas/pootle/env/local/lib/python2.7/site-packages/pootle/apps/pootle_app/forms.py", line 126, in clean
    validator = fs_url_validator.get(plugin)()
TypeError: 'NoneType' object is not callable

[2017-10-27T10:45:44]	"PUT /xhr/admin/projects/3 HTTP/1.1" 500 44
2017-10-27 10:45:44,163 ERROR "PUT /xhr/admin/projects/3 HTTP/1.1" 500 44
```

# Environment (i.e. 'pootle --version', DB, OS, Browser):

 * Pootle 2.9.0rc1 (Django 1.10.8, Translate Toolkit 2.2.5)
 * Debian
 * pip freeze:
Babel==2.5.0
bleach==2.0.0
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
cssmin==0.2.0
diff-match-patch==20121119
dirsync==2.2.2
Django==1.10.8
django-allauth==0.33.0
django-appconf==1.0.2
django-assets==0.12
django-bulk-update==2.2.0
django-contact-form==1.4.2
django-contrib-comments==1.7.3
django-overextends==0.4.3
django-redis==4.8.0
django-rq==0.9.6
django-sortedm2m==1.5.0
django-statici18n==1.4.0
gitdb2==2.0.3
GitPython==2.1.1
html5lib==1.0b10
idna==2.6
jsonfield==2.0.2
lxml==3.8.0
Markdown==2.6.9
oauthlib==2.0.6
pathlib==1.0.1
pkg-resources==0.0.0
Pootle==2.9.0rc1
-e git+https://github.com/translate/pootle_fs_git@723778d1aec2617155fbef457aa58acfcda088fc#egg=pootle_fs_git
psycopg2==2.7.3.1
pycountry==17.5.14
python-dateutil==2.6.1
python-Levenshtein==0.12.0
python-openid==2.2.5
pytz==2017.2
redis==2.10.6
requests==2.18.4
requests-oauthlib==0.8.0
rq==0.8.2
scandir==1.5
six==1.11.0
smmap2==2.0.3
stemming==1.0.1
translate-toolkit==2.2.5
urllib3==1.22
webassets==0.12.1
webencodings==0.5.1

**Comment by jason-p-pickering** [comment]
Same happens with me as well.

**Comment by maxep** [comment]
Same context, same issue

**Comment by LarsMichelsen** [comment]
Have a look at https://github.com/translate/pootle_fs_git/pull/37
