### ISSUE TITLE
ERROR Failed to run update_stores over /fr/messages.po

### ISSUE THREAD

**Issue by yasirhashmi15** [translate/pootle#6814]
# Steps to reproduce:
There was a empty string in one file which cause below error

fr_FR.utf8/messages.po.old:25849: duplicate message definition...
fr_FR.utf8/messages.po.old:2: ...this is the location of the first definition
msgmerge: found 1 fatal error

And when i remove that line and upload that file again and running pootle update_stores i am getting below.

# Results (Expected/Actual):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 87, in do_translation_project
    self.handle_store(store, **options)
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_app/management/commands/update_stores.py", line 63, in handle_store
    store.update_from_disk(overwrite=options["overwrite"])
  File "/usr/local/lib/python2.7/dist-packages/pootle/apps/pootle_store/models.py", line 1833, in update_from_disk
    store_revision=store_revision,
TypeError: 'NoneType' object is not iterable

# Environment (i.e. 'pootle --version', DB, OS, Browser):
Version 2.7

**Comment by jampy** [comment]
I'm facing the exact same problem. Did you solve it?
