### ISSUE TITLE
Unable to install on Debian 10 (Buster)

### ISSUE THREAD

**Issue by mzch** [translate/pootle#6899]
# Steps to reproduce:
pootle initdb

# Results (Expected/Actual):
TypeError: 'NoneType' object is not callable

# Environment (i.e. 'pootle --version', DB, OS, Browser):
pootle: Pootle 2.9.0rc1 (Django 1.10.8, Translate Toolkit 2.2.5)
OS: Debian GNU/Linux 10 (Buster)
Python: Python 2.7.16

-- pootle.conf
```
# -*- coding: utf-8 -*-

"""Sample configuration file.

This file includes the settings that administrators will likely change.
You can find the defaults in the ``*.conf`` files for more advanced settings.
"""

from pootle.i18n.gettext import ugettext_lazy as _

#
# Base
#

# Site title
POOTLE_TITLE = _(u'Pootle Translation Server')

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# If running in a Windows environment this must be set to the same as your
# system time zone.
TIME_ZONE = 'UTC'

# Make this unique, and don't share it with anybody.
SECRET_KEY = '********'

# A list of strings representing the host/domain names that this Pootle server
# can serve. This is a Django's security measure.
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'renderere.com',
    'www.renderere.com',
]

# Set this to a canonical url for your site *without trailing slash*
# This will be used when deriving urls to send out emails
# If you use the `django.contrib.sites` framework set this to blank
POOTLE_CANONICAL_URL = "https://renderere.com"

#
# Backends
#

# Database backend settings
DATABASES = {
    'default': {
        # Replace 'sqlite3' with 'postgresql' or 'mysql'.
        'ENGINE': 'django.db.backends.postgresql',
        # Database name or path to database file if using sqlite3.
        'NAME': 'pootle',
        # Not used with sqlite3.
        'USER': 'pootle',
        # Not used with sqlite3.
        'PASSWORD': '*******',
        # Set to empty string for localhost. Not used with sqlite3.
        'HOST': '192.168.207.11',
        # Set to empty string for default. Not used with sqlite3.
        'PORT': '5432',
        # See https://docs.djangoproject.com/en/1.10/topics/db/transactions/
        # required for Django + sqlite
        'ATOMIC_REQUESTS': True,
        #'OPTIONS' : {
        #    # MySQL:
        #    # https://docs.djangoproject.com/en/1.10/ref/databases/#setting-sql-mode
        #    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        #},
        #'TEST': {
        #    'NAME': 'test_pootle',
        #}
    }
}


# Cache Backend settings

# For more information, check
# https://docs.djangoproject.com/en/1.10/topics/cache/#setting-up-the-cache
# and http://niwibe.github.io/django-redis/
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://192.168.207.13:6379/1',
        'TIMEOUT': 60,
    },
    'redis': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://192.168.207.13:6379/2',
        'TIMEOUT': None,
    },
    'lru': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://192.168.207.13:6379/3',
        'TIMEOUT': 604800,  # 1 week
    },
   'exports': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': working_path('exports/'),
        'TIMEOUT': 259200,  # 3 days.
    },
}

#
# Local Translation Memory service
#

# Setup for connection to the ElasticSearch server for translation memory based
# on the projects hosted on Pootle.
# You may want to set AMAGAMA_URL to '' (empty string) if using this service.
#
POOTLE_TM_SERVER = {
    'local': {
        'ENGINE': 'pootle.core.search.backends.ElasticSearchBackend',
        'HOST': 'localhost',
        'PORT': 9200,
        # Every TM server must have its own unique index.
        'INDEX_NAME': 'translations',
        # Provides a weighting factor to alter the final score for TM results
        # from this TM server. Valid values are between ``0.0`` and ``1.0``,
        # both included. Defaults to ``1.0`` if not provided.
        'WEIGHT': 1.0,
    },
    'external': {
        'ENGINE': 'pootle.core.search.backends.ElasticSearchBackend',
        'HOST': 'localhost',
        'PORT': 9200,
        'INDEX_NAME': 'external-translations',
        'WEIGHT': 0.9,
    },
}

#
# Logging
#

# The directory where Pootle writes its logs
POOTLE_LOG_DIRECTORY = working_path('log')


#
# Site
#

# This Pootle server admins
ADMINS = (
    ('Koichi MATSUMOTO', 'mzch@mac.com'),
)

# Mail settings

# Default email address to use for messages sent by Pootle.
DEFAULT_FROM_EMAIL = 'no-reply@renderere.com'

# Address to receive messages sent by contact form.
POOTLE_CONTACT_EMAIL = 'admin@renderere.com'
POOTLE_CONTACT_ENABLED = True

# Email address to report string errors to, unless a report email was set for
# the project for which the string error is being reported.
# Use this as a way to forward string error reports to an address
# different from the general contact address.
POOTLE_CONTACT_REPORT_EMAIL = 'string_errors_manager@YOUR_DOMAIN.com'

# Whether to email reviewer's feedback to suggesters.
POOTLE_EMAIL_FEEDBACK_ENABLED = False

# Mail server settings

# By default Pootle uses the SMTP server on localhost. If the server is not
# configured for sending emails, uncomment and use these settings to setup an
# external outgoing SMTP server.

# Example for Google as an external SMTP server
EMAIL_HOST_USER = '*****@*****.com'
EMAIL_HOST_PASSWORD = '*****'
EMAIL_HOST = 'mx1.mail-services.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


#
# Translation
#

# The directory where the translation files are kept
POOTLE_TRANSLATION_DIRECTORY = working_path('translations')

# Two-tuple defining the markup filter to apply in certain textareas.
#
# - Accepted values for the first element are 'markdown' and
#   'html' (deprecated).
# - The second element should be a dictionary of keyword arguments that will be
#   passed to the markup function.
#
POOTLE_MARKUP_FILTER = ('markdown', {})

# Set the backends you want to use to enable translation suggestions through
# several online services. To disable this feature completely just comment all
# the lines to set an empty list [] to the POOTLE_MT_BACKENDS setting.
#
# The second parameter for each backend option is the API key, which will
# be used in case the service supports using an API key.
#
# Available options are:
# 'CAIGHDEAN_TRANSLATE': Caighdeán Translate service.
#             Provides translation from Manx Gaelic (gv) and
#             Scottish Gaelic (gd), into Irish Gaelic (ga-IE)
#             See more at https://github.com/kscanne/caighdean
# 'GOOGLE_TRANSLATE': Google Translate service.
#             For this service you need to set the API key.
#             Note that Google Translate API is a paid service
#             See more at https://cloud.google.com/translate/v2/pricing
# 'WELSH_TRANSLATE': Welsh Translate service.
#             Provides translation from English (en) to Welsh (cy)
#             For this service you need an API key.
#             See more at http://techiaith.cymru/api/translation/?lang=en
# 'YANDEX_TRANSLATE': Yandex Translate service.
#             For this service you need to set the API key.
#             See more at https://tech.yandex.com/translate/
#
POOTLE_MT_BACKENDS = [
#    ('CAIGHDEAN_TRANSLATE', ''),
#    ('GOOGLE_TRANSLATE', ''),
#    ('WELSH_TRANSLATE', ''),
#    ('YANDEX_TRANSLATE', ''),
]


# Custom templates directories
#
TEMPLATES[0]['DIRS'] = [
    # working_path(os.path.join('custom', 'templates')),
]
```

# Output
```
Populating the database.
2019-06-28 06:52:46,827 INFO [dirsync] 102 directories parsed, 71 files copied
2019-06-28 06:52:46,827 INFO [dirsync] 75 directories were created.
2019-06-28 06:52:46,909 WARNING Could not import files for languages: lg
2019-06-28 06:52:47,013 WARNING Could not import files for languages: lg
Traceback (most recent call last):
  File "/srv/pootle/.local/bin/pootle", line 10, in <module>
    sys.exit(main())
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/runner.py", line 365, in main
    run_app(project='pootle', django_settings_module='pootle.settings')
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/runner.py", line 346, in run_app
    management.execute_from_command_line(command)
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/initdb.py", line 36, in handle
    InitDB().init_db(options["create_projects"])
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/core/initdb.py", line 37, in init_db
    self._init_db(create_projects)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/core/initdb.py", line 51, in _init_db
    self.create_terminology_project()
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/core/initdb.py", line 256, in create_terminology_project
    plugin.sync()
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_fs/decorators.py", line 58, in method_wrapper
    return f(self, state, response, **kwargs)
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_fs/plugin.py", line 546, in sync
    state, response, fs_path=fs_path, pootle_path=pootle_path)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_fs/decorators.py", line 58, in method_wrapper
    return f(self, state, response, **kwargs)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_fs/decorators.py", line 25, in method_wrapper
    result = f(self, state, response, **kwargs)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_fs/plugin.py", line 465, in sync_pull
    store_fs.file.pull(user=self.pootle_user)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_fs/files.py", line 166, in pull
    merge=merge, pootle_wins=pootle_wins)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_fs/files.py", line 253, in _sync_to_pootle
    resolve_conflict=resolve_conflict)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 961, in update
    allow_add_and_obsolete=allow_add_and_obsolete)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 318, in update
    return self._update(*args, **kwargs)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 341, in _update
    allow_add_and_obsolete)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 417, in update_from_diff
    update_revision=update_revision)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 992, in addunit
    changed_with=changed_with)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 332, in save
    self.change.save()
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/db/models/base.py", line 833, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/srv/pootle/.local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/receivers.py", line 116, in handle_unit_change
    unit.update_tmserver()
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 632, in update_tmserver
    get_tm_broker().update(self.store.translation_project.language.code,
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 61, in get_tm_broker
    TM_BROKER = SearchBroker()
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/core/search/broker.py", line 38, in __init__
    _search_class)(server)
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/core/search/backends/elasticsearch.py", line 69, in __init__
    self._es = self._get_es_server()
  File "/srv/pootle/.local/lib/python2.7/site-packages/pootle/core/search/backends/elasticsearch.py", line 77, in _get_es_server
    'port': self._settings['PORT']},
TypeError: 'NoneType' object is not callable
```

**Comment by mzch** [comment]
miss configuration...
